define({
    // Saving Status
    ModifyingMessage: "正在保存...",
    ModifiedMessage: "已保存",
    PeriodicSavedMessage: "已保存",
    FailedToPeriodicSaveMessage: "正在保存...",

    // Message Box or Message Bar
    OpenFailConversionFailMessage: "打开文档时出错。请关闭文档，然后再次打开它。",
    OpenFailInvalidURLMessage: "打开文档时出错。请关闭文档，然后再次打开它。",
    OpenFailLockFailMessage: "打开文档时出错。请关闭文档，然后再次打开它。",
    OpenFailAnotherUserConvertingMessage: "打开文档时出错。请关闭文档，然后再次打开它。",
    OpenFailNotSupportedFormatMessage: "<p style=\"display: inline; margin: 0px\">此文档包含不受支持的功能。请使用客户端编辑此文档。<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">此处</a>提供了不受支持的功能的完整列表。</p>",
    OpenFailNotSupportedEnvironmentMessage: "此浏览器不支持在线编辑功能。",
    OT3Message: "您的更改已临时存储。单击“确定”可还原。",
    OT5Message: "您的更改已临时存储。单击“确定”可还原。",
    ER1Message: "您的更改无法保存。请重试。",
    PleaseWait: "",
    PleaseTryAgain: "",
    PrintFinishMessage: "",
    DeleteSheetTitle: "警告",
    DeleteChartTitle: "警告",
    FormulaValidateErrorMessageCommon: "此公式中存在错误。",

    AddColumnError: "超出允许添加的列的最大数目。",
    ArrayFormulaEditError: "无法更改带数组公式的单元格内容。",
    BrowserZoomErrorTitle: "<p style=\"display: inline; margin: 0px\">浏览器和计算机显示器的显示比例需要设置为 100%。有关更多信息，请单击<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360002932653-Thinkfree-Office-Cell-Online-Limitations\" target=\"_blank\">此处</a>。</p>",
    CannotGuaranteeEditMessage: "<p style=\"display: inline; margin: 0px\">此文档超出了大小限制。请参考<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">此页</a>。保存此文档时出错。</p>",
    CopyLimitMessage: "复制/粘贴超出大小限制。",
    DeleteSheetConfirm: "删除工作表操作不能撤消。是否要继续?",
    DragAndDropLimit: "复制/粘贴/移动超出 $$ 单元格限制。",
    FileOpenErrorHugeData: "文件超过最大单元格数或条件格式重新计算数。",
    FireFoxZoomError: "在 Firefox 浏览器中将缩放级别缩小到 100% 以下会导致边框错误显示。",
    InvalidSheetChangeError: "由于其他用户更改了工作表，因此，无法执行请求的任务。",
    LastVisibleColumnDeleteErrorMessage: "无法删除工作表上最后一个可见列。",
    LockRefreshFailTitle: "发生错误。",
    MaxSheetNameError: "超过允许的最大输入字符数(31)。",
    MergeErrorAutoFilter: "无法合并跨现有筛选的边框的单元格。",
    MergeErrorRow: "冻结的列/行不能与常规列/行合并。",
    OpenFailNotSupportedDataMessage: "<p style=\"display: inline; margin: 0px\">此文档包含无法在浏览器中编辑的内容 ${UnsupportedProps}。请在<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">此处</a>查找不受支持的内容的列表。</p>",
    OpenFailPasswordMessage: "这是受密码保护的文件。无法在线编辑受密码保护的文件。",
    OT1Message: "正在重新连接...",
    OT1MessageCannotSync: "与网络或服务器的连接已丢失。最后 1 分钟内进行的所有更改都不会保存。复制您的更改并刷新浏览器。",
    SynchronizationFailMessage: "与网络或服务器的连接已丢失。最后 1 分钟内进行的所有更改都不会保存。复制您的更改并刷新浏览器。",
    SynchronizationInProgress: "正在同步...",
    WordFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">此文档大小超出了大小限制。有关详细信息，请参阅<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">此页</a>。</p>",
    CellFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">此文档大小超出了大小限制。有关详细信息，请参阅<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">此页</a>。</p>",
    ShowFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">此文档大小超出了大小限制。有关详细信息，请参阅<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">此页</a>。</p>",
    TooManyFormulaError: "<p style=\"display: inline; margin: 0px\">文件包含许多公式。您可以使用计算机上安装的其他应用程序下载和编辑该文件。请在<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">此处</a>查找不受支持的内容的列表。</p>"
});