define({
    // Saving Status
    ModifyingMessage: "Saving...",
    ModifiedMessage: "Saved",
    PeriodicSavedMessage: "Saved",
    FailedToPeriodicSaveMessage: "Saving...",

    // Message Box or Message Bar
    OpenFailConversionFailMessage: "An error occurred while opening the document. Please close the document and open it again.",
    OpenFailInvalidURLMessage: "An error occurred while opening the document. Please close the document and open it again.",
    OpenFailLockFailMessage: "An error occurred while opening the document. Please close the document and open it again.",
    OpenFailAnotherUserConvertingMessage: "An error occurred while opening the document. Please close the document and open it again.",
    OpenFailNotSupportedFormatMessage: "<p style=\"display: inline; margin: 0px\">This document contains unsupported feature. Please use client to edit this document.&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">Here</a>&nbsp;is complete list of unsupported feature.</p>",
    OpenFailNotSupportedEnvironmentMessage: "This browser is not supported for online edit.",
    OT3Message: "Your changes are temporarily stored. Click “OK” to restore them.",
    OT5Message: "Your changes are temporarily stored. Click “OK” to restore them.",
    ER1Message: "Your changes could not be saved. Please try again.",
    PleaseWait: "",
    PleaseTryAgain: "",
    PrintFinishMessage: "",
    DeleteSheetTitle: "Warning",
    DeleteChartTitle: "Warning",
    FormulaValidateErrorMessageCommon: "There is an error on this formula.",

    AddColumnError: "Exceeds maximum number of columns allowed to be added.",
    ArrayFormulaEditError: "Content of cell with array formula can't be changed.",
    BrowserZoomErrorTitle: "<p style=\"display: inline; margin: 0px\">The browser and the computer display need to be at 100% zoom. Click <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360002932653-Thinkfree-Office-Cell-Online-Limitations\" target=\"_blank\">here</a> for more information.</p>",
    CannotGuaranteeEditMessage: "<p style=\"display: inline; margin: 0px\">This document exceeds the size limit. Please refer to <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">this page</a>. An error may occur while saving this document.</p>",
    CopyLimitMessage: "Copy/paste exceeds size limit.",
    DeleteSheetConfirm: "Cannot undo deleting a sheet operation. Do you want to continue?",
    DragAndDropLimit: "Copy/Paste/Move exceeds $$ cell limit.",
    FileOpenErrorHugeData: "File exceeds maximum number of cells or conditional format recalculations.",
    FireFoxZoomError: "Decreasing Zoom level to less than 100% in Firefox browser, may result in incorrect display of border.",
    InvalidSheetChangeError: "The requested task cannot be performed because another user has changed the sheet(s).",
    LastVisibleColumnDeleteErrorMessage: "Last visible column on a sheet can't be deleted.",
    LockRefreshFailTitle: "An error occurred.",
    MaxSheetNameError: "Exceeded the maximum input characters allowed (31).",
    MergeErrorAutoFilter: "Cells that cross the borders of an existing filter can't be merged.",
    MergeErrorRow: "Frozen columns/rows cannot be merged with normal columns/rows.",
    OpenFailNotSupportedDataMessage: "<p style=\"display: inline; margin: 0px\">This document contains content${UnsupportedProps} that can’t be edited in a browser. Please find list of unsupported content <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">here</a>.</p>",
    OpenFailPasswordMessage: "This is a password protected file. Password protected files can't be edited online.",
    OT1Message: "Reconnecting...",
    OT1MessageCannotSync: "Connection to network or server was lost. Any changes in the last 1 minute will not be saved.  Copy your changes and refresh the browser.",
    SynchronizationFailMessage: "Connection to network or server was lost. Any changes in the last 1 minute will not be saved.  Copy your changes and refresh the browser.",
    SynchronizationInProgress: "Synchronizing...",
    WordFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">This document size exceeds the size limit. Please refer to <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">this page</a> for details.</p>",
    CellFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">This document size exceeds the size limit. Please refer to <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">this page</a> for details.</p>",
    ShowFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">This document size exceeds the size limit. Please refer to <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">this page</a> for details.</p>",
    TooManyFormulaError: "<p style=\"display: inline; margin: 0px\">The file contains many formulas. You can download and edit the file using another application installed on your computer. Please find list of unsupported content&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">here</a>.</p>"
});