define({
    // Saving Status
    ModifyingMessage: "Salvando...",
    ModifiedMessage: "Salvo",
    PeriodicSavedMessage: "Salvo",
    FailedToPeriodicSaveMessage: "Salvando...",

    // Message Box or Message Bar
    OpenFailConversionFailMessage: "Ocorreu um erro ao abrir o documento. Feche o documento e depois abra-o novamente.",
    OpenFailInvalidURLMessage: "Ocorreu um erro ao abrir o documento. Feche o documento e depois abra-o novamente.",
    OpenFailLockFailMessage: "Ocorreu um erro ao abrir o documento. Feche o documento e depois abra-o novamente.",
    OpenFailAnotherUserConvertingMessage: "Ocorreu um erro ao abrir o documento. Feche o documento e depois abra-o novamente.",
    OpenFailNotSupportedFormatMessage: "<p style=\"display: inline; margin: 0px\">Este documento contém um recurso incompatível. Use o cliente para editar este documento.&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">Aqui</a>&nbsp;está a lista completa de recursos incompatíveis.</p>",
    OpenFailNotSupportedEnvironmentMessage: "Este navegador não tem suporte para edição online.",
    OT3Message: "Suas alterações estão armazenadas temporariamente. Clique em “OK” para restaurá-las.",
    OT5Message: "Suas alterações estão armazenadas temporariamente. Clique em “OK” para restaurá-las.",
    ER1Message: "Não foi possível salvar suas alterações. Tente novamente.",
    PleaseWait: "",
    PleaseTryAgain: "",
    PrintFinishMessage: "",
    DeleteSheetTitle: "Aviso",
    DeleteChartTitle: "Aviso",
    FormulaValidateErrorMessageCommon: "Há um erro nesta fórmula.",

    AddColumnError: "Excede o número máximo de colunas permitidas para adição.",
    ArrayFormulaEditError: "Não é possível alterar o conteúdo da célula com fórmula de matriz.",
    BrowserZoomErrorTitle: "<p style=\"display: inline; margin: 0px\">O navegador e a tela do computador precisam estar com zoom de 100%. Clique <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360002932653-Thinkfree-Office-Cell-Online-Limitations\" target=\"_blank\">aqui</a> para obter mais informações.</p>",
    CannotGuaranteeEditMessage: "<p style=\"display: inline; margin: 0px\">Este documento excede o limite de tamanho. Consulte <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">esta página</a>. Pode ocorrer um erro ao salvar o documento.</p>",
    CopyLimitMessage: "Copiar/colar excede o limite de tamanho.",
    DeleteSheetConfirm: "Não é possível desfazer a exclusão de uma operação de planilha. Deseja continuar?",
    DragAndDropLimit: "Copiar/colar/mover excede o limite de $$ células.",
    FileOpenErrorHugeData: "O arquivo excede o número máximo de células ou recálculos de formato condicional.",
    FireFoxZoomError: "A redução do nível de zoom para menos de 100% no navegador Firefox pode fazer a borda ser exibida incorretamente.",
    InvalidSheetChangeError: "A tarefa solicitada não pode ser executada porque outro usuário alterou a(s) planilha(s).",
    LastVisibleColumnDeleteErrorMessage: "Não é possível excluir a última coluna visível de uma planilha.",
    LockRefreshFailTitle: "Ocorreu um erro.",
    MaxSheetNameError: "Foi excedido o máximo permitido de caracteres de entrada (31).",
    MergeErrorAutoFilter: "Não é possível mesclar células que atravessam as bordas de um filtro existente.",
    MergeErrorRow: "Não é possível mesclar colunas/linhas congeladas com colunas/linhas normais.",
    OpenFailNotSupportedDataMessage: "<p style=\"display: inline; margin: 0px\">Este documento contém conteúdo${UnsupportedProps} que não pode ser editado em um navegador. Consulte a lista de conteúdos incompatíveis <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">aqui</a>.</p>",
    OpenFailPasswordMessage: "Este é um arquivo protegido por senha. Não é possível editar online arquivos protegidos por senha.",
    OT1Message: "Reconectando...",
    OT1MessageCannotSync: "A conexão de rede ou servidor foi perdida. Nenhuma alteração feita no último minuto será salva. Copie suas alterações e atualize o navegador.",
    SynchronizationFailMessage: "A conexão de rede ou servidor foi perdida. Nenhuma alteração feita no último minuto será salva. Copie suas alterações e atualize o navegador.",
    SynchronizationInProgress: "Sincronizando...",
    WordFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">Este documento excede o tamanho limite. Consulte <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">esta página</a> para obter detalhes.</p>",
    CellFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">Este documento excede o tamanho limite. Consulte <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">esta página</a> para obter detalhes.</p>",
    ShowFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">Este documento excede o tamanho limite. Consulte <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">esta página</a> para obter detalhes.</p>",
    TooManyFormulaError: "<p style=\"display: inline; margin: 0px\">O arquivo contém muitas fórmulas. Você pode baixar e editar o arquivo usando outro aplicativo instalado no seu computador. Consulte a lista de conteúdos incompatíveis&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">aqui</a>.</p>"
});