define({
    // Saving Status
    ModifyingMessage: "Bezig met opslaan...",
    ModifiedMessage: "Opgeslagen",
    PeriodicSavedMessage: "Opgeslagen",
    FailedToPeriodicSaveMessage: "Bezig met opslaan...",

    // Message Box or Message Bar
    OpenFailConversionFailMessage: "Er is een fout opgetreden bij het openen van het document. Sluit het document en open het vervolgens opnieuw.",
    OpenFailInvalidURLMessage: "Er is een fout opgetreden bij het openen van het document. Sluit het document en open het vervolgens opnieuw.",
    OpenFailLockFailMessage: "Er is een fout opgetreden bij het openen van het document. Sluit het document en open het vervolgens opnieuw.",
    OpenFailAnotherUserConvertingMessage: "Er is een fout opgetreden bij het openen van het document. Sluit het document en open het vervolgens opnieuw.",
    OpenFailNotSupportedFormatMessage: "<p style=\"display: inline; margin: 0px\">Dit document bevat een niet-ondersteunde functie. Gebruik de client om dit document te bewerken.&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">Hier</a>&nbsp;is een volledige lijst van niet-ondersteunde functies.</p>",
    OpenFailNotSupportedEnvironmentMessage: "Deze browser wordt niet ondersteund voor online bewerken.",
    OT3Message: "Uw wijzigingen zijn tijdelijk opgeslagen. Klik op 'OK' om ze te herstellen.",
    OT5Message: "Uw wijzigingen zijn tijdelijk opgeslagen. Klik op 'OK' om ze te herstellen.",
    ER1Message: "Uw wijzigingen konden niet worden opgeslagen. Probeer het opnieuw.",
    PleaseWait: "",
    PleaseTryAgain: "",
    PrintFinishMessage: "",
    DeleteSheetTitle: "Waarschuwing",
    DeleteChartTitle: "Waarschuwing",
    FormulaValidateErrorMessageCommon: "Er staat een fout in deze formule.",

    AddColumnError: "Het maximum aantal toe te voegen kolommen is overschreden.",
    ArrayFormulaEditError: "De celinhoud met formule kan niet worden veranderd.",
    BrowserZoomErrorTitle: "<p style=\"display: inline; margin: 0px\">De browser- en computerweergave moeten op 100% zoom zijn ingesteld. Klik <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360002932653-Thinkfree-Office-Cell-Online-Limitations\" target=\"_blank\">hier</a> voor meer informatie.</p>",
    CannotGuaranteeEditMessage: "<p style=\"display: inline; margin: 0px\">Dit document overschrijdt de groottebeperking. Raadplaag <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">deze pagina</a>. Er kan een fout optreden bij het opslaan van dit document.</p>",
    CopyLimitMessage: "Kopiëren/plakken overschrijdt de groottebeperking.",
    DeleteSheetConfirm: "Het verwijderen van een blad kan niet ongedaan worden gemaakt. Wilt u doorgaan?",
    DragAndDropLimit: "Kopiëren/plakken/verplaatsen overschrijdt cellimiet van $$.",
    FileOpenErrorHugeData: "Maximum aantal toegestane cellen of voorwaardelijke indelingsherberekeningen overschreden in bestand.",
    FireFoxZoomError: "Als u het zoomniveau verlaagt tot minder dan 100% in de Firefox-browser, worden randen mogelijk niet op de juiste manier weergegeven.",
    InvalidSheetChangeError: "De aangevraagde taak kan niet worden uitgevoerd omdat een andere gebruiker het blad heeft gewijzigd.",
    LastVisibleColumnDeleteErrorMessage: "U kunt de laatste zichtbare kolom op een blad niet verwijderen.",
    LockRefreshFailTitle: "Er is een fout opgetreden.",
    MaxSheetNameError: "U hebt het maximale aantal toegestane invoertekens overschreden (31).",
    MergeErrorAutoFilter: "Cellen die zich buiten het bereik van een bestaand filter bevinden, kunnen niet worden samengevoegd.",
    MergeErrorRow: "Geblokkeerde kolommen/rijen kunnen niet worden samengevoegd met normale kolommen/rijen.",
    OpenFailNotSupportedDataMessage: "<p style=\"display: inline; margin: 0px\">Dit document bevat inhoud${UnsupportedProps} die niet kan worden bewerkt in een browser. <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">Hier</a> vindt u een lijst van niet-ondersteunde functies.</p>",
    OpenFailPasswordMessage: "Dit is een bestand dat met een wachtwoord is beveiligd. Bestanden die met een wachtwoord zijn beveiligd kunnen niet online worden bewerkt.",
    OT1Message: "Opnieuw verbinding maken...",
    OT1MessageCannotSync: "De verbinding met het netwerk of de server is verbroken. Alle wijzigingen die in de laatste minuut zijn aangebracht, worden niet opgeslagen.  Kopieer uw wijzigingen en vernieuw de browser.",
    SynchronizationFailMessage: "De verbinding met het netwerk of de server is verbroken. Alle wijzigingen die in de laatste minuut zijn aangebracht, worden niet opgeslagen.  Kopieer uw wijzigingen en vernieuw de browser.",
    SynchronizationInProgress: "Synchroniseren...",
    WordFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">Dit document overschrijdt de groottebeperking. Raadpleeg <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">deze pagina</a> voor details.</p>",
    CellFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">Dit document overschrijdt de groottebeperking. Raadpleeg <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">deze pagina</a> voor details.</p>",
    ShowFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">Dit document overschrijdt de groottebeperking. Raadpleeg <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">deze pagina</a> voor details.</p>",
    TooManyFormulaError: "<p style=\"display: inline; margin: 0px\">Het bestand bevat veel formules. U kunt het bestand downloaden en met een andere toepassing op uw computer bewerken. &nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">Hier</a> vindt u een lijst van niet-ondersteunde functies.</p>"
});