define({
    // Saving Status
    ModifyingMessage: "กำลังบันทึก...",
    ModifiedMessage: "บันทึกแล้ว",
    PeriodicSavedMessage: "บันทึกแล้ว",
    FailedToPeriodicSaveMessage: "กำลังบันทึก...",

    // Message Box or Message Bar
    OpenFailConversionFailMessage: "เกิดข้อผิดพลาดขณะเปิดเอกสาร โปรดปิดเอกสาร แล้วเปิดใหม่อีกครั้ง",
    OpenFailInvalidURLMessage: "เกิดข้อผิดพลาดขณะเปิดเอกสาร โปรดปิดเอกสาร แล้วเปิดใหม่อีกครั้ง",
    OpenFailLockFailMessage: "เกิดข้อผิดพลาดขณะเปิดเอกสาร โปรดปิดเอกสาร แล้วเปิดใหม่อีกครั้ง",
    OpenFailAnotherUserConvertingMessage: "เกิดข้อผิดพลาดขณะเปิดเอกสาร โปรดปิดเอกสาร แล้วเปิดใหม่อีกครั้ง",
    OpenFailNotSupportedFormatMessage: "<p style=\"display: inline; margin: 0px\">เอกสารนี้มีคุณลักษณะที่ไม่ได้รับการสนับสนุน โปรดใช้ไคลเอนต์เพื่อแก้ไขเอกสารนี้&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">ต่อไปนี้</a>&nbsp;คือรายการคุณลักษณะที่ไม่ได้รับการสนับสนุนทั้งหมด</p>",
    OpenFailNotSupportedEnvironmentMessage: "เบราว์เซอร์นี้ไม่ได้รับการสนับสนุนให้แก้ไขแบบออนไลน์",
    OT3Message: "บันทึกการเปลี่ยนแปลงไว้ชั่วคราวแล้ว คลิก \"ตกลง\" เพื่อคืนค่า",
    OT5Message: "บันทึกการเปลี่ยนแปลงไว้ชั่วคราวแล้ว คลิก “ตกลง” เพื่อคืนค่า",
    ER1Message: "ไม่สามารถบันทึกการเปลี่ยนแปลงได้ โปรดลองอีกครั้ง",
    PleaseWait: "",
    PleaseTryAgain: "",
    PrintFinishMessage: "",
    DeleteSheetTitle: "คำเตือน",
    DeleteChartTitle: "คำเตือน",
    FormulaValidateErrorMessageCommon: "มีข้อผิดพลาดในสูตรนี้",

    AddColumnError: "เกินจำนวนคอลัมน์สูงสุดที่อนุญาตให้เพิ่มได้",
    ArrayFormulaEditError: "ไม่สามารถเปลี่ยนเนื้อหาของเซลล์ที่มีสูตรอาร์เรย์ได้",
    BrowserZoomErrorTitle: "<p style=\"display: inline; margin: 0px\">เบราว์เซอร์และจอแสดงผลของคอมพิวเตอร์นี้ต้องซูมที่ 100% คลิก<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360002932653-Thinkfree-Office-Cell-Online-Limitations\" target=\"_blank\">ที่นี่</a> ถ้าต้องการข้อมูลเพิ่มเติม</p>",
    CannotGuaranteeEditMessage: "<p style=\"display: inline; margin: 0px\">เอกสารนี้มีขนาดเกินขีดจำกัด โปรดดูที่<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">หน้านี้</a> อาจเกิดข้อผิดพลาดขณะบันทึกเอกสารนี้</p>",
    CopyLimitMessage: "คัดลอก/วางรายการที่มีขนาดเกินขีดจำกัด",
    DeleteSheetConfirm: "ไม่สามารถยกเลิกการลบแผ่นงานได้ คุณต้องการดำเนินการต่อหรือไม่",
    DragAndDropLimit: "คัดลอก/วาง/ย้ายเซลล์เกินขีดจำกัดที่ $$ เซลล์",
    FileOpenErrorHugeData: "ไฟล์มีจำนวนเซลล์หรือมีจำนวนการคำนวณใหม่ตามการจัดรูปแบบแบบมีเงื่อนไขเกินขีดจำกัดที่อนุญาต",
    FireFoxZoomError: "การลดระดับการซูมลงเหลือน้อยกว่า 100% ในเบราว์เซอร์ Firefox อาจทำให้แสดงเส้นขอบไม่ถูกต้อง",
    InvalidSheetChangeError: "ทำงานที่ขอไม่ได้เพราะผู้ใช้คนอื่นเปลี่ยนแผ่นงานไปแล้ว",
    LastVisibleColumnDeleteErrorMessage: "ไม่สามารถลบคอลัมน์ที่มองเห็นได้คอลัมน์สุดท้ายบนแผ่นงาน",
    LockRefreshFailTitle: "เกิดข้อผิดพลาด",
    MaxSheetNameError: "ป้อนอักขระเกินจำนวนสูงสุดที่อนุญาต (31)",
    MergeErrorAutoFilter: "ไม่สามารถผสานเซลล์ที่ข้ามเส้นขอบของตัวกรองที่มีอยู่ได้",
    MergeErrorRow: "ไม่สามารถผสานคอลัมน์/แถวที่ถูกตรึงกับคอลัมน์/แถวปกติได้",
    OpenFailNotSupportedDataMessage: "<p style=\"display: inline; margin: 0px\">เอกสารนี้มีเนื้อหา${UnsupportedProps}ที่ไม่สามารถแก้ไขได้ในเบราว์เซอร์ โปรดดูรายการเนื้อหาที่ไม่สนับสนุน<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">ที่นี่</a></p>",
    OpenFailPasswordMessage: "นี่คือไฟล์ที่มีการป้องกันด้วยรหัสผ่าน ไฟล์ที่ป้องกันด้วยรหัสผ่านไม่สามารถแก้ไขทางออนไลน์ได้",
    OT1Message: "กำลังเชื่อมต่อใหม่...",
    OT1MessageCannotSync: "ไม่มีการเชื่อมต่อไปยังเครือข่ายหรือเซิร์ฟเวอร์ การเปลี่ยนแปลงใน 1 นาทีสุดท้ายจะไม่ถูกบันทึก คัดลอกการเปลี่ยนแปลงแล้วรีเฟรชเบราว์เซอร์",
    SynchronizationFailMessage: "ไม่มีการเชื่อมต่อไปยังเครือข่ายหรือเซิร์ฟเวอร์ การเปลี่ยนแปลงใน 1 นาทีสุดท้ายจะไม่ถูกบันทึก คัดลอกการเปลี่ยนแปลงแล้วรีเฟรชเบราว์เซอร์",
    SynchronizationInProgress: "กำลังซิงค์โครไนซ์...",
    WordFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">เอกสารนี้มีขนาดเกินขีดจำกัด โปรดดูรายละเอียดที่<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">หน้านี้</a></p>",
    CellFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">เอกสารนี้มีขนาดเกินขีดจำกัด โปรดดูรายละเอียดที่<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">หน้านี้</a></p>",
    ShowFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">เอกสารนี้มีขนาดเกินขีดจำกัด โปรดดูรายละเอียดที่<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">หน้านี้</a></p>",
    TooManyFormulaError: "<p style=\"display: inline; margin: 0px\">ไฟล์นี้มีหลายสูตร คุณสามารถดาวน์โหลดและแก้ไขไฟล์โดยใช้แอปพลิเคชันอื่นที่ติดตั้งบนคอมพิวเตอร์ โปรดดูรายการเนื้อหาที่ไม่สนับสนุน&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">ที่นี่</a></p>"
});