define({
    // Saving Status
    ModifyingMessage: "Guardando...",
    ModifiedMessage: "Guardado",
    PeriodicSavedMessage: "Guardado",
    FailedToPeriodicSaveMessage: "Guardando...",

    // Message Box or Message Bar
    OpenFailConversionFailMessage: "Error al abrir el documento. Cierre el documento y, a continuación, ábralo de nuevo.",
    OpenFailInvalidURLMessage: "Error al abrir el documento. Cierre el documento y, a continuación, ábralo de nuevo.",
    OpenFailLockFailMessage: "Error al abrir el documento. Cierre el documento y, a continuación, ábralo de nuevo.",
    OpenFailAnotherUserConvertingMessage: "Error al abrir el documento. Cierre el documento y, a continuación, ábralo de nuevo.",
    OpenFailNotSupportedFormatMessage: "<p style=\"display: inline; margin: 0px\">Este documento contiene características no admitidas. Use el cliente para editar este documento.&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">Esta</a>&nbsp;es una lista completa de las características no admitidas.</p>",
    OpenFailNotSupportedEnvironmentMessage: "No se admite la edición en línea con este navegador.",
    OT3Message: "Los cambios están almacenados temporalmente. Haga clic en el botón “Aceptar” para restaurarlos.",
    OT5Message: "Los cambios están almacenados temporalmente. Haga clic en el botón “Aceptar” para restaurarlos.",
    ER1Message: "No se pudieron guardar los cambios. Inténtelo de nuevo.",
    PleaseWait: "",
    PleaseTryAgain: "",
    PrintFinishMessage: "",
    DeleteSheetTitle: "Advertencia",
    DeleteChartTitle: "Advertencia",
    FormulaValidateErrorMessageCommon: "Hay un error en esta fórmula.",

    AddColumnError: "Supera el número máximo de columnas que se pueden agregar.",
    ArrayFormulaEditError: "No se puede cambiar el contenido de la celda con fórmula de matriz.",
    BrowserZoomErrorTitle: "<p style=\"display: inline; margin: 0px\">El navegador y la pantalla de la computadora deben tener un zoom de 100 %. Haga clic <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360002932653-Thinkfree-Office-Cell-Online-Limitations\" target=\"_blank\">aquí</a> para obtener más información.</p>",
    CannotGuaranteeEditMessage: "<p style=\"display: inline; margin: 0px\">El tamaño de este documento supera el tamaño máximo. Consulte <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">esta página</a>. Es posible que ocurra un error al guardar este documento.</p>",
    CopyLimitMessage: "Copiar/pegar supera el tamaño máximo.",
    DeleteSheetConfirm: "La eliminación de hojas no se puede deshacer. ¿Desea continuar?",
    DragAndDropLimit: "Copiar/pegar/mover supera el límite de $$ celdas.",
    FileOpenErrorHugeData: "El archivo supera la cantidad máxima de celdas o de actualizaciones de formato condicional.",
    FireFoxZoomError: "Si reduce el zoom a menos del 100 % en el navegador Firefox, puede provocar que el borde no se muestre correctamente.",
    InvalidSheetChangeError: "La tarea solicitada no se puede ejecutar porque otro usuario cambió la(s) hoja(s).",
    LastVisibleColumnDeleteErrorMessage: "No se puede eliminar la última columna visible de la hoja.",
    LockRefreshFailTitle: "Ocurrió un error.",
    MaxSheetNameError: "Se superó el número máximo de caracteres de entrada (31).",
    MergeErrorAutoFilter: "No se pueden combinar celdas que sobrepasen los bordes de un filtro existente.",
    MergeErrorRow: "Las columnas o filas inmovilizadas no se pueden combinar con las columnas o filas normales.",
    OpenFailNotSupportedDataMessage: "<p style=\"display: inline; margin: 0px\">Este documento tiene contenido${UnsupportedProps} que no se puede editar en un navegador. Podrá encontrar una lista del contenido no admitido <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">aquí</a>.</p>",
    OpenFailPasswordMessage: "Este es un archivo protegido por contraseña. Los archivos protegidos por contraseña no se pueden editar en línea.",
    OT1Message: "Reconectando...",
    OT1MessageCannotSync: "Se perdió la conexión con la red o el servidor. No se guardará ningún cambio realizado en el último minuto. Copie sus cambios y actualice el navegador.",
    SynchronizationFailMessage: "Se perdió la conexión con la red o el servidor. No se guardará ningún cambio realizado en el último minuto. Copie sus cambios y actualice el navegador.",
    SynchronizationInProgress: "Sincronizando...",
    WordFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">El tamaño de este documento supera el tamaño máximo. Consulte <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">esta página</a> para obtener detalles.</p>",
    CellFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">El tamaño de este documento supera el tamaño máximo. Consulte <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">esta página</a> para obtener detalles.</p>",
    ShowFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">El tamaño de este documento supera el tamaño máximo. Consulte <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">esta página</a> para obtener detalles.</p>",
    TooManyFormulaError: "<p style=\"display: inline; margin: 0px\">El archivo tiene muchas fórmulas. Puede descargar el archivo y editarlo con otra aplicación instalada su computadora. Podrá encontrar una lista del contenido no admitido&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">aquí</a>.</p>"
});