define({
    // Saving Status
    ModifyingMessage: "Wird gespeichert...",
    ModifiedMessage: "Gespeichert",
    PeriodicSavedMessage: "Gespeichert",
    FailedToPeriodicSaveMessage: "Wird gespeichert...",

    // Message Box or Message Bar
    OpenFailConversionFailMessage: "Fehler beim Öffnen des Dokuments. Schließen Sie das Dokument, und öffnen Sie es erneut.",
    OpenFailInvalidURLMessage: "Fehler beim Öffnen des Dokuments. Schließen Sie das Dokument, und öffnen Sie es erneut.",
    OpenFailLockFailMessage: "Fehler beim Öffnen des Dokuments. Schließen Sie das Dokument, und öffnen Sie es erneut.",
    OpenFailAnotherUserConvertingMessage: "Fehler beim Öffnen des Dokuments. Schließen Sie das Dokument, und öffnen Sie es erneut.",
    OpenFailNotSupportedFormatMessage: "<p style=\"display: inline; margin: 0px\">Dieses Dokument enthält nicht unterstützte Funktionen. Verwenden Sie den Client, um dieses Dokument zu bearbeiten.&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">Hier</a>&nbsp;finden Sie eine vollständige Liste der nicht unterstützten Funktionen.</p>",
    OpenFailNotSupportedEnvironmentMessage: "Dieser Browser wird für die Online-Bearbeitung nicht unterstützt.",
    OT3Message: "Ihre Änderungen werden temporär gespeichert. Klicken Sie zum Wiederherstellen auf \"OK\".",
    OT5Message: "Ihre Änderungen werden temporär gespeichert. Klicken Sie zum Wiederherstellen auf “OK“.",
    ER1Message: "Ihre Änderungen konnten nicht gespeichert werden. Bitte versuchen Sie es erneut.",
    PleaseWait: "",
    PleaseTryAgain: "",
    PrintFinishMessage: "",
    DeleteSheetTitle: "Warnung",
    DeleteChartTitle: "Warnung",
    FormulaValidateErrorMessageCommon: "Fehler in dieser Formel.",

    AddColumnError: "Überschreitet die maximale Spaltenanzahl, die hinzugefügt werden können.",
    ArrayFormulaEditError: "Inhalt der Zelle mit Matrixformel kann nicht geändert werden.",
    BrowserZoomErrorTitle: "<p style=\"display: inline; margin: 0px\">Die Anzeige des Browsers und des Computers muss auf einen Zoomfaktor von 100 % eingestellt sein. Weitere Informationen dazu finden Sie <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360002932653-Thinkfree-Office-Cell-Online-Limitations\" target=\"_blank\">hier</a>.</p>",
    CannotGuaranteeEditMessage: "<p style=\"display: inline; margin: 0px\">Dieses Dokument überschreitet die maximal zulässige Größe. Nähere Hinweise finden Sie auf <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">dieser Seite</a>. Beim Speichern dieses Dokuments kann ein Fehler auftreten.</p>",
    CopyLimitMessage: "Kopieren/Einfügen überschreitet die maximal zulässige Größe.",
    DeleteSheetConfirm: "Das Löschen eines Blatts kann nicht rückgängig gemacht werden. Möchten Sie den Vorgang fortsetzen?",
    DragAndDropLimit: "Kopieren/Einfügen/Verschieben überschreitet das Limit von $$ Zellen.",
    FileOpenErrorHugeData: "Datei überschreitet die maximale Anzahl von Zellen oder Neuberechnungen von bedingter Formatierung.",
    FireFoxZoomError: "Wenn Sie im Browser Firefox die Vergrößerungsstufe auf unter 100 % senken, werden die Rahmen ggf. nicht richtig dargestellt.",
    InvalidSheetChangeError: "Die angeforderte Aufgabe konnte nicht durchgeführt werden, da ein anderer Benutzer die Blätter geändert hat.",
    LastVisibleColumnDeleteErrorMessage: "Die letzte sichtbare Spalte eines Blatts kann nicht gelöscht werden.",
    LockRefreshFailTitle: "Ein Fehler ist aufgetreten.",
    MaxSheetNameError: "Die maximal unterstützte Zeichenzahl (31) wurde überschritten.",
    MergeErrorAutoFilter: "Zellen, die die Ränder eines vorhandenen Filters schneiden, können nicht zusammengeführt werden.",
    MergeErrorRow: "Fixierte Spalten/Zeilen können nicht mit normalen Spalten/Zeilen zusammengeführt werden.",
    OpenFailNotSupportedDataMessage: "<p style=\"display: inline; margin: 0px\">Dieses Dokument enthält Inhalt${UnsupportedProps}, der nicht in einem Browser bearbeitet werden kann. Eine Liste der nicht unterstützten Inhalte finden Sie <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">hier</a>.</p>",
    OpenFailPasswordMessage: "Diese Datei ist kennwortgeschützt. Kennwortgeschützte Dateien können online nicht bearbeitet werden.",
    OT1Message: "Verbindung wird wiederhergestellt...",
    OT1MessageCannotSync: "Die Verbindung mit dem Netzwerk oder Server wurde getrennt. Alle Änderungen, die innerhalb der letzten Minute vorgenommen wurden, werden nicht gespeichert. Kopieren Sie Ihre Änderungen, und aktualisieren Sie den Browser.",
    SynchronizationFailMessage: "Die Verbindung mit dem Netzwerk oder Server wurde getrennt. Alle Änderungen, die innerhalb der letzten Minute vorgenommen wurden, werden nicht gespeichert. Kopieren Sie Ihre Änderungen, und aktualisieren Sie den Browser.",
    SynchronizationInProgress: "Wird synchronisiert...",
    WordFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">Dieses Dokument überschreitet die maximal erlaubte Größe. Weitere Informationen finden Sie auf <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">dieser Seite</a>.</p>",
    CellFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">Dieses Dokument überschreitet die maximal erlaubte Größe. Weitere Informationen finden Sie auf <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">dieser Seite</a>.</p>",
    ShowFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">Dieses Dokument überschreitet die maximal erlaubte Größe. Weitere Informationen finden Sie auf <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">dieser Seite</a>.</p>",
    TooManyFormulaError: "<p style=\"display: inline; margin: 0px\">Die Datei enthält viele Formeln. Sie können die Datei herunterladen und mit einer anderen Anwendung bearbeiten, die auf Ihrem Computer installiert ist. Eine Liste der nicht unterstützten Inhalte finden Sie &nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">hier</a>.</p>"
});