define({
    // Saving Status
    ModifyingMessage: "保存中...",
    ModifiedMessage: "保存されました",
    PeriodicSavedMessage: "保存されました",
    FailedToPeriodicSaveMessage: "保存中...",

    // Message Box or Message Bar
    OpenFailConversionFailMessage: "文書を開くときにエラーが発生しました。文書を閉じて、もう一度開いてください。",
    OpenFailInvalidURLMessage: "文書を開くときにエラーが発生しました。文書を閉じて、もう一度開いてください。",
    OpenFailLockFailMessage: "文書を開くときにエラーが発生しました。文書を閉じて、もう一度開いてください。",
    OpenFailAnotherUserConvertingMessage: "文書を開くときにエラーが発生しました。文書を閉じて、もう一度開いてください。",
    OpenFailNotSupportedFormatMessage: "<p style=\"display: inline; margin: 0px\">この文書にはサポートされていない機能が含まれています。この文書を編集するには、クライアントを使用してください。サポートされていない機能のすべての一覧は&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">こちら</a>&nbsp;をご覧ください。</p>",
    OpenFailNotSupportedEnvironmentMessage: "このブラウザーではオンライン編集はサポートされていません。",
    OT3Message: "変更は一時的に保存されています。復元するには、[OK] ボタンをクリックします。",
    OT5Message: "変更は一時的に保存されています。復元するには、[OK] ボタンをクリックします。",
    ER1Message: "変更内容を保存できませんでした。もう一度試してください。",
    PleaseWait: "",
    PleaseTryAgain: "",
    PrintFinishMessage: "",
    DeleteSheetTitle: "警告",
    DeleteChartTitle: "警告",
    FormulaValidateErrorMessageCommon: "この数式にエラーがあります。",

    AddColumnError: "追加できる列の最大数を超過しています。",
    ArrayFormulaEditError: "配列数式を含むセルの内容は変更できません。",
    BrowserZoomErrorTitle: "<p style=\"display: inline; margin: 0px\">ブラウザーとコンピューター画面のズームを 100% にする必要があります。詳細は、<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360002932653-Thinkfree-Office-Cell-Online-Limitations\" target=\"_blank\">ここ</a>をクリックしてください。</p>",
    CannotGuaranteeEditMessage: "<p style=\"display: inline; margin: 0px\">この文書はサイズが上限を超えています。<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">こちらのページ</a>を参照してください。この文書の保存中にエラーが発生する可能性があります。</p>",
    CopyLimitMessage: "コピー/貼り付けのサイズが上限を超えています。",
    DeleteSheetConfirm: "シートを削除する操作は元に戻すことはできません。続行しますか?",
    DragAndDropLimit: "コピー/貼り付け/移動の上限である $$ セルを超えています。",
    FileOpenErrorHugeData: "ファイルにおけるセルの最大数または条件付き書式の再計算の最大数を超えています。",
    FireFoxZoomError: "Firefox ブラウザーでズーム レベルを 100% より下げると、罫線が適切に表示されない可能性があります。",
    InvalidSheetChangeError: "ワークシートは他のユーザーによって変更されているため、要求されたタスクを実行できません。",
    LastVisibleColumnDeleteErrorMessage: "シート上の最後の表示列は削除できません。",
    LockRefreshFailTitle: "エラーが発生しました。",
    MaxSheetNameError: "入力できる文字数の上限 (31) を超えています。",
    MergeErrorAutoFilter: "既存のフィルターの罫線と交差するセルは結合できません。",
    MergeErrorRow: "固定された列/行は、通常の列/行に結合できません。",
    OpenFailNotSupportedDataMessage: "<p style=\"display: inline; margin: 0px\">この文書には、ブラウザーでは編集できないコンテンツ ${UnsupportedProps} が含まれています。サポートされていないコンテンツのすべての一覧は<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">こちら</a>をご覧ください。</p>",
    OpenFailPasswordMessage: "このファイルはパスワードで保護されています。パスワードで保護されたファイルは、オンラインで編集できません。",
    OT1Message: "接続中...",
    OT1MessageCannotSync: "ネットワークまたはサーバーへの接続が切断されました。直前の 1 分間に行われた変更は保存されません。変更内容をコピーしてブラウザーを更新してください。",
    SynchronizationFailMessage: "ネットワークまたはサーバーへの接続が切断されました。直前の 1 分間に行われた変更は保存されません。変更内容をコピーしてブラウザーを更新してください。",
    SynchronizationInProgress: "同期しています...",
    WordFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">この文書はサイズが上限を超えています。詳細は、<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">こちらのページ</a>を参照してください。</p>",
    CellFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">この文書はサイズが上限を超えています。詳細は、<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">こちらのページ</a>を参照してください。</p>",
    ShowFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">この文書はサイズが上限を超えています。詳細は、<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">こちらのページ</a>を参照してください。</p>",
    TooManyFormulaError: "<p style=\"display: inline; margin: 0px\">ファイルに含まれる数式が多すぎます。ファイルをダウンロードし、コンピューターにインストールされている別のアプリケーションを使用して編集してください。サポートされていないコンテンツのすべての一覧は&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">こちら</a></p>をご覧ください。"
});