define({
    // Saving Status
    ModifyingMessage: "儲存中...",
    ModifiedMessage: "已儲存",
    PeriodicSavedMessage: "已儲存",
    FailedToPeriodicSaveMessage: "儲存中...",

    // Message Box or Message Bar
    OpenFailConversionFailMessage: "開啟文件時發生錯誤。請關閉該文件，然後再開啟文件。",
    OpenFailInvalidURLMessage: "開啟文件時發生錯誤。請關閉該文件，然後再開啟文件。",
    OpenFailLockFailMessage: "開啟文件時發生錯誤。請關閉該文件，然後再開啟文件。",
    OpenFailAnotherUserConvertingMessage: "開啟文件時發生錯誤。請關閉該文件，然後再開啟文件。",
    OpenFailNotSupportedFormatMessage: "<p style=\"display: inline; margin: 0px\">此文件包含不支援的功能。請使用用戶端編輯此文件。<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">以下</a>是不支援功能的完整清單。</p>",
    OpenFailNotSupportedEnvironmentMessage: "線上編輯不支援此瀏覽器。",
    OT3Message: "系統已暫時儲存您的變更。按一下「確定」按鈕，即可還原變更。",
    OT5Message: "系統已暫時儲存您的變更。按一下 [確定] 按鈕，即可還原變更。",
    ER1Message: "無法儲存您的變更。請再試一次。",
    PleaseWait: "",
    PleaseTryAgain: "",
    PrintFinishMessage: "",
    DeleteSheetTitle: "警告",
    DeleteChartTitle: "警告",
    FormulaValidateErrorMessageCommon: "此公式出現錯誤。",

    AddColumnError: "超過允許新增的欄數上限。",
    ArrayFormulaEditError: "無法變更包含陣列公式的儲存格內容。",
    BrowserZoomErrorTitle: "<p style=\"display: inline; margin: 0px\">瀏覽器和電腦顯示必須設為 100% 縮放。按一下<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360002932653-Thinkfree-Office-Cell-Online-Limitations\" target=\"_blank\">這裡</a>即可取得更多資訊。</p>",
    CannotGuaranteeEditMessage: "<p style=\"display: inline; margin: 0px\">此文件超過大小上限。請參閱<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">此頁面</a>。儲存此文件時可能會發生錯誤。</p>",
    CopyLimitMessage: "複製/貼上超過大小上限。",
    DeleteSheetConfirm: "無法復原刪除工作表作業。要繼續嗎?",
    DragAndDropLimit: "複製/貼上/移動超過 $$ 個儲存格上限。",
    FileOpenErrorHugeData: "檔案超過儲存格數目或條件格式重新計算次數上限。",
    FireFoxZoomError: "如果在 Firefox 瀏覽器中將縮放比例減少到 100% 以下，可能會錯誤顯示框線。",
    InvalidSheetChangeError: "另一位使用者已變更工作表，所以無法執行要求的工作。",
    LastVisibleColumnDeleteErrorMessage: "無法刪除工作表上最後一個可見的欄。",
    LockRefreshFailTitle: "發生錯誤",
    MaxSheetNameError: "已超過允許的輸入字元上限 (31)。",
    MergeErrorAutoFilter: "無法合併跨越現有篩選框線的儲存格。",
    MergeErrorRow: "已凍結的欄/列無法與一般的欄/列合併。",
    OpenFailNotSupportedDataMessage: "<p style=\"display: inline; margin: 0px\">此文件包含無法在瀏覽器編輯的 content${UnsupportedProps}。請在<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">這裡</a>尋找不支援的內容清單。</p>",
    OpenFailPasswordMessage: "這是密碼保護的檔案。無法線上編輯受密碼保護的檔案。",
    OT1Message: "正在重新連線...",
    OT1MessageCannotSync: "網路或伺服器的連線已中斷。在最後一分鐘所做的任何變更都將不會儲存。請複製您的變更並重新整理瀏覽器。",
    SynchronizationFailMessage: "網路或伺服器的連線已中斷。在最後一分鐘所做的任何變更都將不會儲存。請複製您的變更並重新整理瀏覽器。",
    SynchronizationInProgress: "正在同步處理...",
    WordFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">本文件大小超過大小上限。請參閱<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">此頁面</a>，以取得詳細資料。</p>",
    CellFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">本文件大小超過大小上限。請參閱<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">此頁面</a>，以取得詳細資料。</p>",
    ShowFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">本文件大小超過大小上限。請參閱<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">此頁面</a>，以取得詳細資料。</p>",
    TooManyFormulaError: "<p style=\"display: inline; margin: 0px\">檔案包含許多公式。您可以使用電腦上安裝的其他應用程式來下載和編輯檔案。請在<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">這裡</a>尋找不支援的內容清單。</p>"
});