function htmlTagRevision(a,b,c){if(0<KEDITORTOP.G_CURRKEDITOR._config.htmlCorrectionLimitLength&&a.length>KEDITORTOP.G_CURRKEDITOR._config.htmlCorrectionLimitLength)return a;var d=a;if(""!=d&&(KEDITORTOP.RAONKEDITOR.browser.ie&&11>=KEDITORTOP.RAONKEDITOR.browser.ieVersion||KEDITORTOP.RAONKEDITOR.browser.gecko))try{var e=d.toLowerCase().indexOf("<body"),g=d.toLowerCase().lastIndexOf("<body");if(-1<e&&-1<g&&e!=g)return a;if(-1<d.indexOf("mso-fareast-font-family")){var f=RegExp("<[^>]+style=(.*?)>",
"gi"),h="",e=!1;try{var k=d.match(f);if(k){for(var l=k.length,f=0;f<l;f++)d=d.replace(k[f],"_KE_T_S{"+f+"}_");for(f=0;f<l;f++){var m=k[f];-1<m.indexOf("-font-family")&&(m=m.replace("-font-family","-font-ktemp-family"));g=!1;0>m.indexOf("font-family")&&(g=!0);-1<m.indexOf("-font-ktemp-family")&&(m=m.replace("-font-ktemp-family","-font-family"));g&&(m=m.replace(/mso-fareast-font-family/gi,"font-family"));d=d.replace("_KE_T_S{"+f+"}_",m)}}}catch(r){e=!0}e&&(d=a)}b&&(d=RAONK_EDITOR.HTMLParser.RemoveOfficeTag(d,
c));var h=d.toLowerCase(),p=realValue2=d,n=h.lastIndexOf("<body"),q=h.indexOf("</body");if(-1<n&&-1<q)try{var t=p.substring(q),u=p.substring(n).indexOf(">"),v=p.substring(0,n+u+1),d=p.substring(n+u+1,q)}catch(w){n=q=-1,d=realValue2}realValue2=null;d=RAONK_EDITOR.HTMLParser.HTMLtoXML(d,c);-1<n&&-1<q&&(d=v+d+t)}catch(x){return a}else if(d="1"==KEDITORTOP.G_CURRKEDITOR._config.removeComment?d.replace(/(<style[^>]*>\s*\x3c!--)|(\x3c!--.*?--\x3e)|(\x3c!--[\w\W\n\s]+?--\x3e)/gi,"$1"):d.replace(/--\x3e\s</gi,
"--\x3e<"),"1"==KEDITORTOP.G_CURRKEDITOR._config.removeCarriageReturnInTag)try{for(f=RegExp("(<[^>]*?)\n([^]*?>)","gi");f.test(d);)d=d.replace(f,"$1 $2")}catch(y){}return d}var G_wordProcessorType="";
function SetCorrectOfficeHtml(a){var b=a;if(-1<a.indexOf("<meta name=ProgId content=Word.Document>")||-1<a.indexOf('<meta name=Generator content="Microsoft Word'))G_wordProcessorType="DOC",a=GetMsWordHtml(a);else if(-1<a.indexOf("<meta name=ProgId content=Excel.Sheet>"))G_wordProcessorType="XLS",a=GetMsExcelHtml(a);else if(-1<a.indexOf("<meta name=ProgId content=PowerPoint.Slide>")){if(G_wordProcessorType="PPT",a=GetMsPptHtml2(a),"1"==KEDITORTOP.G_CURRKEDITOR._config.removeTdStyleInPastePpt){for(var c=
RegExp("<(td|th)([^>]*?)style='([^']*?)(font-size:18.0pt;)([^']*?)'>","gi");c.test(a);)a=a.replace(c,"<$1$2style='$3$5'>");for(c=RegExp('<(td|th)([^>]*?)style="([^"]*?)(font-size:18.0pt;)([^"]*?)">',"gi");c.test(a);)a=a.replace(c,'<$1$2style="$3$5">');for(c=RegExp("<(td|th)([^>]*?)style='([^']*?)(font-family:Arial;)([^']*?)'>","gi");c.test(a);)a=a.replace(c,"<$1$2style='$3$5'>");for(c=RegExp('<(td|th)([^>]*?)style="([^"]*?)(font-family:Arial;)([^"]*?)">',"gi");c.test(a);)a=a.replace(c,'<$1$2style="$3$5">')}}else if(-1<
a.indexOf('<meta name=Generator content="Jungum Global">'))G_wordProcessorType="GUL",a=GetJungumHtml(a);else if(isHwpPasteAction(a))G_wordProcessorType="HWP",a=GetHanHwpHtml(a);else if(-1<a.indexOf(' xmlns:m="http://schemas.microsoft.com/office/')){if(G_wordProcessorType="PPT",a=GetMsPptHtml2(a),"1"==KEDITORTOP.G_CURRKEDITOR._config.removeTdStyleInPastePpt){for(c=RegExp("<(td|th)([^>]*?)style='([^']*?)(font-size:18.0pt;)([^']*?)'>","gi");c.test(a);)a=a.replace(c,"<$1$2style='$3$5'>");for(c=RegExp('<(td|th)([^>]*?)style="([^"]*?)(font-size:18.0pt;)([^"]*?)">',
"gi");c.test(a);)a=a.replace(c,'<$1$2style="$3$5">');for(c=RegExp("<(td|th)([^>]*?)style='([^']*?)(font-family:Arial;)([^']*?)'>","gi");c.test(a);)a=a.replace(c,"<$1$2style='$3$5'>");for(c=RegExp('<(td|th)([^>]*?)style="([^"]*?)(font-family:Arial;)([^"]*?)">',"gi");c.test(a);)a=a.replace(c,'<$1$2style="$3$5">')}}else-1<a.indexOf('<meta name=Generator content="Microsoft')?(G_wordProcessorType="DOC",a=GetMsWordHtml(a)):KEDITORTOP.RAONKEDITOR.browser.ie||(b=a.indexOf("\x3c!--StartFragment--\x3e"),c=
a.lastIndexOf("\x3c!--EndFragment--\x3e"),-1<b&&-1<c&&(b=a.substr(b+20),c=b.lastIndexOf("\x3c!--EndFragment--\x3e"),-1<c&&(a=b=b.substring(0,c))));a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![if !supportEmptyParas]>","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![endif]>","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\x3c!--[if !supportEmptyParas]--\x3e","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\x3c!--[if !supportLists]--\x3e","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\x3c!--[endif]--\x3e",
"");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\x3c!--StartFragment--\x3e","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\x3c!--EndFragment--\x3e","");return a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![if ppt]>","")}
function GetMsWordHtml(a){var b=a,c,b=a.indexOf("/* Style Definitions */"),d=a.indexOf("</head>");-1<b&&-1<d&&(b=a.substr(b+23),d=b.indexOf("</head>"),-1<d&&(c=b.substring(0,d),c=GetStyleMap(c)));var b=a,d=!1,e="\x3c!--StartFragment--\x3e",g="\x3c!--EndFragment--\x3e",f=a.indexOf(e),h=a.indexOf(g);if(-1==f&&-1==h){var e="<body ",g="</body>",k=a.indexOf(e);-1<k&&(h=a.indexOf(">",k),e=a.Mid(k,h-k+1),f=a.indexOf(e),h=a.indexOf(g))}if(-1<f&&-1<h&&(b=a.substr(f+e.length),h=b.indexOf(g),-1<h)){for(;;)if(a=
b.indexOf(g,h+g.length),-1<a)h=a;else break;a=b=b.substring(0,h);d=!0}if(d){a=b;var l="<div class=WordSection1>",g=a.indexOf(l);-1==g&&(l='<div class="WordSection1">',g=a.indexOf(l));-1<g&&(l=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,l,""),l.length!=a.length&&(a=l,l=a.lastIndexOf("/"),-1<l&&(a=a.substring(0,l-1))));e="\x3c!--[if supportFields]>";for(g="<![endif]--\x3e";;){f=a.indexOf(e);-1<f&&(h=a.indexOf(g,f+e.length));l=a.length;if(f>l||h>l)break;if(-1<f&&-1<h){if(f<h){var m,b=a.substring(0,f);m=
a.substr(h+g.length);a=b+m}}else break;h=-1}}if(d){e="\x3c!--[if gte vml 1]>";g="<![if !vml]>";try{f=a.indexOf(e),-1<f&&(h=a.indexOf(g,f+e.length)),-1<f&&-1<h&&(a=a.replace(/\x3c!--\[if gte vml 1\]>(.|\s|\n)*?<!\[if !vml\]>/gi,""))}catch(r){}}e="\x3c!--[if gte mso 9]>";g="<![endif]--\x3e";try{for(;;){f=a.indexOf(e);-1<f&&(h=a.indexOf(g,f+e.length));l=a.length;if(f>l||h>l){a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,e,"");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,g,"");break}if(-1<f&&-1<h)f>h?(b=a.substring(0,
f),m=a.substr(f),b=KEDITORTOP.RAONKEDITOR.util.replaceAll(b,g,"")):(b=a.substring(0,f),m=a.substr(h+g.length)),a=b+m;else break}}catch(p){}d&&(a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"><![endif]></span>"," /></span>"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![endif]></span>","</span>"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"</span><![endif]>","</span>"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![endif]>",""),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![if !vml]>",""));a=RepaireSpanInImageTag4MsWord(a);
if(0<KEDITORTOP.G_CURRKEDITOR._config.clipImageHex.length){try{var n=RegExp("<img[^>]+file://[^>]+>","gi"),q=a.match(n);if(q){var t=q.length;if(t==KEDITORTOP.G_CURRKEDITOR._config.clipImageHex.length)for(m=0;m<t;m++){var u=KEDITORTOP.RAONKEDITOR.util.hexToBytes(KEDITORTOP.G_CURRKEDITOR._config.clipImageHex[m].hex),u=KEDITORTOP.RAONKEDITOR.util.bytesToBase64(u),n=/<img[^>]*src=["']?([^>"']+)["']?[^>]*>/;if(n.test(q[m])){var v=q[m].replace(RegExp.$1,"data:"+KEDITORTOP.G_CURRKEDITOR._config.clipImageHex[m].type+
";base64,"+u);a=a.replace(q[m],v)}}}}catch(w){}KEDITORTOP.G_CURRKEDITOR._config.clipImageHex=[]}a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<v:rect ","<div ");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"</v:rect>","</div>");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<v:shadow ","<hr ");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<v:shape ","<span ");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"</v:shape>","</span>");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<v:imagedata","<img border=0");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,
"<![if !supportLists]>","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![endif]>","");return a=setPasteClassStyle(c,a,!0)}
function GetMsExcelHtml(a){var b=a,c,b=a.indexOf("<style>"),d=a.indexOf("</head>");-1<b&&-1<d&&(b=a.substr(b+7),d=b.indexOf("</head>"),-1<d&&(c=b.substring(0,d),c=GetStyleMap(c)));var b=a,d=!1,e="</body>",g=a.indexOf("<table"),f=a.indexOf(e);-1<g&&-1<f&&(b=a.substr(g),f=b.indexOf(e),-1<f&&(b=b.substring(0,f),d=!0));if(d){d=!1;a=b;b="\x3c!--[if gte vml 1]>";e="<![if !vml]>";try{g=a.indexOf(b),-1<g&&(f=a.indexOf(e,g+b.length)),-1<g&&-1<f&&(a=a.replace(/\x3c!--\[if gte vml 1\]>(.|\s|\n)*?<!\[if !vml\]>/gi,
""))}catch(h){}}d&&(a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"></span><![endif]>"," /></span>"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"</span><![endif]>","</span>"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![endif]>",""),b=_T("<![if !vml]>"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,b,""));a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<v:rect ","<div ");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"</v:rect>","</div>");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<v:shadow ","<hr ");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,
"<v:shape ","<span ");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"</v:shape>","</span>");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<v:imagedata","<img border=0");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\x3c!--StartFragment--\x3e","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\x3c!--EndFragment--\x3e","");b=a.indexOf("<col ");-1<b&&(a=a.substring(0,b)+"\n<colgroup>\n"+a.substring(b,a.length+1));b=a.indexOf("<tr ");-1<b&&(a=a.substring(0,b)+"\n<tbody>\n"+a.substring(b,a.length+1),b=a.lastIndexOf("</table>"),
-1<b&&(a=a.substring(0,b)+"\n</tbody>\n"+a.substring(b,a.length+1)));a=setPasteClassStyle(c,a,!1,!0);"1"==KEDITORTOP.G_CURRKEDITOR._config.officeLineFix&&(a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"border-left:none;",""),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"border-top:none;",""),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"border-right:none;",""),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"border-bottom:none;",""));a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"\r","");return a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,
"\n","")}
function GetMsPptHtml2(a){var b=a,c,b=a.indexOf("\x3c!--tr"),d=a.indexOf("</head>");-1<b&&-1<d&&(b=a.substr(b+6),d=b.indexOf("</head>"),-1<d&&(c=b.substring(0,d),c=GetStyleMap(c)));b=a.indexOf("\x3c!--StartFragment--\x3e");d=a.indexOf("\x3c!--EndFragment--\x3e");if(-1<b&&-1<d&&(b=a.substr(b+20),d=b.indexOf("\x3c!--EndFragment--\x3e"),-1<d)){for(;;)if(a=b.indexOf("\x3c!--EndFragment--\x3e",d+18),-1<a)d=a;else break;a=b=b.substring(0,d)}a=setPasteClassStyle(c,a);"1"==KEDITORTOP.G_CURRKEDITOR._config.officeLineFix&&(a=
KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"border-right:none;",""));c=RegExp("<spanstyle","ig");a=a.replace(c,"<span style");return a=a.replace(c,"<p style")}
function GetJungumHtml(a){if("1"==KEDITORTOP.G_CURRKEDITOR._config.useHtmlProcessByWorker)return a;var b=a.indexOf("<body>"),c=a.indexOf("</body>"),d=!1;-1<b&&-1<c&&(strTemp=a.substr(b+6),c=strTemp.indexOf("</body>"),-1<c&&(a=strTemp=strTemp.substring(0,c),d=!0));if(d){b=document.createElement("div");b.innerHTML=a;a=b.getElementsByTagName("table");for(var c=a.length,e,g,d=0;d<c;d++)""!=a[d].getAttribute("width")&&(e=parseInt(a[d].getAttribute("width"),10)),""!=a[d].getAttribute("height")&&(g=parseInt(a[d].getAttribute("height"),
10)),e&&(a[d].style.width=e+"px"),g&&(a[d].style.height=g+"px");a=b.innerHTML}return a}
function GetHanHwpHtml(a){var b=a,b=">\x3c!--p.0",c="</head>",d,e=a.indexOf(b),g=a.indexOf(c);-1==e&&(b=">\r\n\x3c!--p.0",e=a.indexOf(b));-1==e&&(b="\x3c!--p.0",e=a.indexOf(b));-1==g&&(c="</HEAD>",g=a.indexOf(c));-1<e&&-1<g&&(b=a.substr(e+(b.length-3)),g=b.indexOf(c),-1<g&&(d=b.substring(0,g),d=GetStyleMap(d)));var b=a,f=!1,h="\x3c!--StartFragment--\x3e",c="\x3c!--EndFragment--\x3e",g=a.indexOf(h),e=a.indexOf(c);if(-1<g&&-1<e&&(b=a.substr(g+h.length),e=b.indexOf(c),-1<e)){for(;;)if(f=b.indexOf(c,
e+c.length),-1<f)e=f;else break;b=b.substring(0,e);f=!0}if(f){f=!1;a=b;h="\x3c!--[if gte vml 1]>";c="<![if !vml]>";try{for(;;){g=a.indexOf(h);-1<g&&(e=a.indexOf(c,g+h.length));var k=a.length;if(k>g||k>e){a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,h,"");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,c,"");break}if(-1<g&&-1<e)if(g>e){var l,b=a.substring(0,g);l=a.substr(g);b=KEDITORTOP.RAONKEDITOR.util.replaceAll(b,c,"");a=b+l}else b=a.substring(0,g),l=a.substr(e+c.length),a=b+l,f=!0;else break}}catch(m){}}a=
setPasteClassStyle(d,a);f&&(a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"/><![endif]>"," />"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"</span><![endif]>","</span>"),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![endif]>",""),a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![if !vml]>",""));a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![if !supportEmptyParas]>&nbsp;<![endif]>","");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"<![endif]>","");for(k=RegExp("(<p [^>]*)(background:#000000;)","gi");k.test(a);)a=
a.replace(k,"$1");for(k=RegExp("(<[^>]*)(background:#ffffff;)","gi");k.test(a);)a=a.replace(k,"$1");for(k=RegExp("(<[^>]*)(mso-fareast-)","gi");k.test(a);)a=a.replace(k,"$1");for(k=RegExp("(<[^>]*)(mso-hansi-)","gi");k.test(a);)a=a.replace(k,"$1");for(k=RegExp("(<[^>]*)(mso-ascii-)","gi");k.test(a);)a=a.replace(k,"$1");for(k=RegExp("(<[^>]*)(mso-bidi-)","gi");k.test(a);)a=a.replace(k,"$1");for(k=RegExp("(<[^>]*)(mso-)","gi");k.test(a);)a=a.replace(k,"$1");return a}
function GetStyleMap(a){var b={};a=a.split("}");for(var c="",d=a.length,e=0;e<d;e++){var g=a[e].split("{"),f=g.length;if(2==f)for(var h=0;h<f-1;h++){var k=g[h],l=g[h+1],k=k.replace(/\r\n/g,""),k=k.replace(/\r/g,""),k=k.replace(/\n/g,""),k=k.replace(/\t/g,""),l=l.replace(/\r\n/g,""),l=l.replace(/\r/g,""),l=l.replace(/\n/g,""),l=l.replace(/\t/g,"");""==c&&"td"==k&&(c=l=KEDITORTOP.RAONKEDITOR.util.replaceAll(l,"'",'"'));0<k.length&&(l=KEDITORTOP.RAONKEDITOR.util.replaceAll(l,"'",'"'),"."==k.substring(0,
1)&&0<c.length?(l=l.replace(/font-family:&quot,/g,"font-family:"),b[k]=c+l):b[k]=l)}}return b}
function RepaireSpanInImageTag4MsWord(a){for(var b,c,d,e,g;;)if(b="<v:shape ",c=a.indexOf(b),-1==c&&(b="<v:shape\r\n",c=a.indexOf(b)),-1<c)if(d=a.indexOf("</v:shape>",c+b.length),e=a.indexOf("<v:imagedata",c+b.length),-1<d&&-1<e&&e<d)if(g=a.indexOf("/>",e+12),-1<g)e=a.substring(0,c),c=a.substr(c,g-c+2),a=a.substr(d+10),c=KEDITORTOP.RAONKEDITOR.util.replaceAll(c,"<v:imagedata"," "),c=KEDITORTOP.RAONKEDITOR.util.replaceAll(c,b,"<v:imagedata "),c=KEDITORTOP.RAONKEDITOR.util.replaceAll(c,">"," "),c=KEDITORTOP.RAONKEDITOR.util.rtrim(c),
c+=">",c=KEDITORTOP.RAONKEDITOR.util.replaceAll(c,"/>"," />"),c=KEDITORTOP.RAONKEDITOR.util.replaceAll(c,"  "," "),a=e+c+a;else break;else break;else break;return a}
function setPasteClassStyle(a,b,c,d){var e=function(a){a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"hairline ","dotted ");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a," hairline;"," dotted;");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"dot-dot-dash ","dotted ");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a," dot-dot-dash;"," dotted;");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"dot-dash ","dotted ");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a," dot-dash;"," dotted;");a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,
"dot-dash-slanted ","dotted ");return a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a," dot-dash-slanted;"," dotted;")};if(d&&null!=a.td){var g=e(a.td);b=b.replace(RegExp("<td[^>]*(.*?)","gi"),function(a){return 0>a.indexOf("class")?setStyleToNonClass(a,"td",g):a})}for(var f in a){d=e(a[f]);f=f.split(",")[0];f=f.substring(f.indexOf("."));if("."==f.substring(0,1)){var h=new RegExp("<[^>]*class=(\"|'|)"+f.substr(1)+"(\"|'|) [\\s\\S]*?>","i");b=setStyleToClass(b,h,f,d);h=new RegExp("<[^>]*class=(\"|'|)"+
f.substr(1)+"(\"|'|)>","i");b=setStyleToClass(b,h,f,d)}if(c&&(h=f.toLowerCase(),(-1<h.indexOf("h1")||-1<h.indexOf("h2")||-1<h.indexOf("h3")||-1<h.indexOf("h4")||-1<h.indexOf("h5")||-1<h.indexOf("h6")||-1<h.indexOf("em"))&&""!=d&&(h=new RegExp("<"+f+"[^>]*>","igm"),h=b.match(h))))for(var k=h.length,l=0;k>l;l++){var m=b.substring(0,b.indexOf(h[l])),r=h[l];b=b.substring(b.indexOf(h[l])+h[l].length);var p=/(style=("|'|))/i,r=1==p.test(r)?r.replace(p,RegExp.$1+d):r.replace(new RegExp("<"+f,"i"),"<"+f+
" style='"+d+"'");b=m+r+b}}return b}
function setStyleToClass(a,b,c,d){for(var e;e=b.exec(a);){var g=a.substring(0,e.index),f=e[0].toString();a=a.substr(e.index+e[0].length);e=/style=("|'|)/i;if(1==e.test(f)){var h=RegExp.$1;"'"==h?d=d.replace(/'/gi,'"'):'"'==h&&(d=d.replace(/"/gi,"'"));f=f.replace(e,"style="+h+d+" ");e=new RegExp("class=(\"|'|)"+c.substr(1)+"(\"|'|)","i");f=f.replace(e,"")}else e=new RegExp("class=(\"|'|)"+c.substr(1)+"(\"|'|)","i"),f=f.replace(e,"style='"+d+"'");a=g+f+a}return a}
function setStyleToNonClass(a,b,c){b=/style=("|'|)/i;if(1==b.test(a)){var d=RegExp.$1;"'"==d?c=c.replace(/'/gi,'"'):'"'==d&&(c=c.replace(/"/gi,"'"));a=a.replace(b,"style="+d+c+" ")}else a+=" style='"+c+"'";return a}function GetFontSizeForWordH1ToH7Tag(a){var b="",c=a.indexOf("font-size");-1<c&&(a=a.substr(c),c=a.indexOf(";"),-1<c&&(b=a.substring(0,c),b+=";"));return b}
function isHwpPasteAction(a){return-1<a.indexOf(">\x3c!--p.")||-1<a.indexOf('<META NAME="Generator" CONTENT="Hancom HWP')||-1<a.indexOf("\x3c!--[if !supportEmptyParas]--\x3e")?!0:!1}
"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.officeClean&&(KEDITORTOP.RAONKEDITOR.util.officeClean=function(a,b){if(""==a||void 0==a)return"";var c=null,d=[];a=a.replace(/\.0px/g,"px");a=a.replace(/\t/g,"");a=KEDITORTOP.RAONKEDITOR.util.removeOfficeDummyTag(a,"\x3c!--[if supportFields]>","<![endif]--\x3e");c=RegExp("<o:p></o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p>\\s+</o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p ([^>]+)></o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p ([^>]+)>\\s+</o:p>","gi");
a=a.replace(c,"");c=RegExp("<w:sdt[^>]*>","gi");a=a.replace(c,"");c=RegExp("</w:sdt>","gi");a=a.replace(c,"");c=RegExp('<[^>]+(lang=["]?en-us["])[^>]*>',"gi");if(c=a.match(c))for(var d=c.length,e=0;e<d;e++){var g=c[e],f=RegExp('\\slang=[\\"]?en-us[\\"]?',"gi"),g=g.replace(f,"");a=a.replace(c[e],g)}c=RegExp("<[^>]+(mso)[^>]*>","gi");if(c=a.match(c))for(d=c.length,e=0;e<d;e++)g=c[e],"1"==KEDITORTOP.G_CURRKEDITOR._config.removeMsoClass&&(f=RegExp('\\sclass=[\\"]?(mso)\\w+[\\"]?',"gi"),g=g.replace(f,
"")),g=g.replace(/&quot;/gi,"^"),f=RegExp('(\\s+)?mso-number-format:(\\s+)?"(.+?)"(\\s+)?;',"gi"),g=g.replace(f,""),f=RegExp('(\\s+)?mso-number-format:(\\s+)?"(.+?)"(\\s+)?;?',"gi"),g=g.replace(f,""),f=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?'\"\\^@%\\.\\\\_]+; ?","gi"),g=g.replace(f,""),f=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?]+(['\"])","gi"),g=g.replace(f,"$1"),g=g.replace(/\^/gi,"&quot;"),a=a.replace(c[e],g);a=KEDITORTOP.RAONKEDITOR.util.replaceAll(a,"hairline","dotted");for(e=0;5>e;e++){d=["o:p",
"span","font"];f=d.length;for(g=0;g<f;g++)c=new RegExp("<"+d[g]+"[^>]*></"+d[g]+">","gi"),a=a.replace(c,""),c=new RegExp("<"+d[g]+"[^>]*>&nbsp;</"+d[g]+">","gi"),a=a.replace(c,"&nbsp;"),"span"!=d[g]&&(c=new RegExp("<"+d[g]+"[^>]*> </"+d[g]+">","gi"),a=a.replace(c,"&nbsp;"));d=["o","v","w","m","x"];f=d.length;for(g=0;g<f;g++)0==g&&(a=a.replace(/<o:p/gi,"<raonko:p")),-1<a.indexOf("<"+d[g])&&(c=new RegExp("<"+d[g]+":[^/>]+/>","gi"),a=a.replace(c,""),c=new RegExp("<"+d[g]+":[^>]+>[^<]*</"+d[g]+":[^>]+>",
"gi"),a=a.replace(c,""),"v"==d[g]&&(c=new RegExp("<"+d[g]+":[^>]+>","gi"),a=a.replace(c,""),c=new RegExp("</"+d[g]+":[^>]+>","gi"),a=a.replace(c,""))),g==f-1&&(a=a.replace(/<raonko:p/gi,"<o:p"))}a=a.replace(/style=""/gi,"");a=a.replace(/style=''/gi,"");a=a.replace(/\s>/gi,">");a=KEDITORTOP.RAONKEDITOR.util.replaceOneSpaceToNbsp(a);a=a.replace(/<\/td>&nbsp;<\/tr>/g,"</td></tr>");a=a.replace(/<\/td>&nbsp;<\/td>/g,"</td></td>");a=a.replace(/<\/th>&nbsp;<\/tr>/g,"</th></tr>");a=a.replace(/<\/th>&nbsp;<\/th>/g,
"</th></th>");if(KEDITORTOP.RAONKEDITOR.browser.ie&&10>KEDITORTOP.RAONKEDITOR.browser.ieVersion){var c=a.length,g=d=!1,h=f="",k="";if(-1==a.indexOf("<")&&-1==a.indexOf(">"))for(e=0;e<c;e++)f=a.charAt(e),h=a.charAt(e+1)," "!=f&&32!=f.charCodeAt(0)||" "!=h&&32!=h.charCodeAt(0)||(f="&nbsp;"),k+=f;else for(e=0;e<c;e++)f=a.charAt(e),h=a.charAt(e+1),"<"==f?(d=!1,g="p"==h.toLowerCase()?!0:!1):">"==f&&1==g?d=!0:1!=d||" "!=f&&32!=f.charCodeAt(0)||" "!=h&&32!=h.charCodeAt(0)||(f="&nbsp;"),k+=f;a=k}0==b&&(a=
KEDITORTOP.RAONKEDITOR.util.removeLocalFileImage(a));return a});"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.removeLocalFileImage&&(KEDITORTOP.RAONKEDITOR.util.removeLocalFileImage=function(a){return""==a||void 0==a?"":a=a.replace(RegExp("<img[^>]+file:///[^>]+>","gi"),"")});
"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.removeOfficeDummyTag&&(KEDITORTOP.RAONKEDITOR.util.removeOfficeDummyTag=function(a,b,c){var d=a;try{for(var e=a.indexOf(b),g=a.indexOf(c);-1<e&&-1<g;)var f=d.substring(0,e),h=d.substring(g+c.length),d=f+h,e=d.indexOf(b),g=d.indexOf(c)}catch(k){d=a}return d});"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.replaceAll&&(KEDITORTOP.RAONKEDITOR.util.replaceAll=function(a,b,c){a&&""!=a&&(a=a.split(b).join(c));return a});
"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.replaceOneSpaceToNbsp&&(KEDITORTOP.RAONKEDITOR.util.replaceOneSpaceToNbsp=function(a){if(3==KEDITORTOP.G_CURRKEDITOR.agentPasteFormatType&&"0"==KEDITORTOP.G_CURRKEDITOR._config.replaceOneSpaceToNbspInExcel)return a;var b=a,c,d="";try{for(var e="span font a b strong i em strike u sup sub".split(" "),g=e.length,f=0;f<g;f++){var h=!0,k=e[f];("font"==k||"b"==k||"em"==k||"sup"==k||"sub"==k)&&0>b.toLowerCase().indexOf("<"+k)&&(h=!1);if(h)for(var l=0;l<g;l++){d=
b;c=new RegExp("<"+e[f]+" *([^>?+])*>(\\s+)</"+e[l]+">","gi");reg_exp2="u"==e[l]?new RegExp("</"+e[f]+">(\\s+)<"+e[l]+"[^l]","gi"):new RegExp("</"+e[f]+">(\\s+)<"+e[l]+" *([^>?+])*>","gi");reg_exp3=new RegExp("<"+e[f]+" *([^>?+])*>(\\s+)<"+e[l]+">","gi");reg_exp4="u"==e[l]?new RegExp("</"+e[f]+">(\\s+)</"+e[l]+"[^l]","gi"):new RegExp("</"+e[f]+">(\\s+)</"+e[l]+" *([^>?+])*>","gi");try{var m=b.match(c);if(m)for(var r=m.length,p=0;p<r;p++){var n=m[p];if(!("b"==e[f]&&-1<n.toLowerCase().indexOf("<br")))var q=
/>\s+</.exec(n),t=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),n=n.replace(q,t),b=b.replace(m[p],n)}if(m=b.match(reg_exp2))for(r=m.length,p=0;p<r;p++)n=m[p],"b"==e[l]&&-1<n.toLowerCase().indexOf("<br")||(q=/>\s+</.exec(n),t=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),n=n.replace(q,t),b=b.replace(m[p],n));if(m=b.match(reg_exp3))for(r=m.length,p=0;p<r;p++)n=m[p],"b"==e[f]&&-1<n.toLowerCase().indexOf("<br")||(q=/>\s+</.exec(n),t=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),n=n.replace(q,
t),b=b.replace(m[p],n));if(m=b.match(reg_exp4))for(r=m.length,p=0;p<r;p++)n=m[p],q=/>\s+</.exec(n),t=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),n=n.replace(q,t),b=b.replace(m[p],n)}catch(u){b=d}}}for(f=0;f<g;f++)if(h=!0,k=e[f],("font"==k||"b"==k||"em"==k||"sup"==k||"sub"==k)&&0>b.toLowerCase().indexOf("<"+k)&&(h=!1),h){"b"==k?(b=b.replace(/<br/gi,"<temp_br"),b=b.replace(/<\/br/gi,"</temp_br")):"u"==k&&(b=b.replace(/<ul/gi,"<temp_ul"),b=b.replace(/<\/ul/gi,"</temp_ul"));for(l=0;l<g;l++)c=new RegExp("/"+
e[f]+">\\s<"+e[l],"gi"),b=b.replace(c,"/"+e[f]+">&nbsp;<"+e[l]),c=new RegExp("/"+e[f]+">\\s\\n<"+e[l],"gi"),b=b.replace(c,"/"+e[f]+">&nbsp;<"+e[l]);"b"==k?(b=b.replace(/<temp_br/gi,"<br"),b=b.replace(/<\/temp_br/gi,"</br")):"u"==k&&(b=b.replace(/<temp_ul/gi,"<ul"),b=b.replace(/<\/temp_ul/gi,"</ul"))}}catch(v){b=a}return b});"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.rtrim&&(KEDITORTOP.RAONKEDITOR.util.rtrim=function(a){return""==a?a:a.replace(/\s+$/,"")});
"undefined"!=typeof KEDITORTOP.RAONKEDITOR&&"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.hexToBytes&&(KEDITORTOP.RAONKEDITOR.util.hexToBytes=function(a){for(var b=[],c=a.length/2,d=0,d=0;d<c;d++)b.push(parseInt(a.substr(2*d,2),16));return b});
"undefined"!=typeof KEDITORTOP.RAONKEDITOR&&"undefined"==typeof KEDITORTOP.RAONKEDITOR.util.bytesToBase64&&(KEDITORTOP.RAONKEDITOR.util.bytesToBase64=function(a){for(var b="",c=a.length,d=0;d<c;d+=3){var e=a.slice(d,d+3),g=e.length,f=[],h=void 0;if(3>g)for(h=g;3>h;h++)e[h]=0;f[0]=(252&e[0])>>2;f[1]=(3&e[0])<<4|e[1]>>4;f[2]=(15&e[1])<<2|(192&e[2])>>6;f[3]=63&e[2];for(h=0;4>h;h++)b+=h<=g?"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(f[h]):"="}return b});
var htmlProcessUtilFunctionList={};htmlProcessUtilFunctionList.htmlTagRevision=htmlTagRevision;htmlProcessUtilFunctionList.SetCorrectOfficeHtml=SetCorrectOfficeHtml;htmlProcessUtilFunctionList.GetMsWordHtml=GetMsWordHtml;htmlProcessUtilFunctionList.GetMsExcelHtml=GetMsExcelHtml;htmlProcessUtilFunctionList.GetMsPptHtml2=GetMsPptHtml2;htmlProcessUtilFunctionList.GetJungumHtml=GetJungumHtml;htmlProcessUtilFunctionList.GetHanHwpHtml=GetHanHwpHtml;htmlProcessUtilFunctionList.GetStyleMap=GetStyleMap;
htmlProcessUtilFunctionList.RepaireSpanInImageTag4MsWord=RepaireSpanInImageTag4MsWord;htmlProcessUtilFunctionList.setPasteClassStyle=setPasteClassStyle;htmlProcessUtilFunctionList.setStyleToClass=setStyleToClass;htmlProcessUtilFunctionList.GetFontSizeForWordH1ToH7Tag=GetFontSizeForWordH1ToH7Tag;htmlProcessUtilFunctionList.isHwpPasteAction=isHwpPasteAction;htmlProcessUtilFunctionList["KEDITORTOP.RAONKEDITOR.util.officeClean"]=KEDITORTOP.RAONKEDITOR.util.officeClean;
