define({
    // Saving Status
    ModifyingMessage: "Salvataggio in corso...",
    ModifiedMessage: "Salvato",
    PeriodicSavedMessage: "Salvato",
    FailedToPeriodicSaveMessage: "Salvataggio in corso...",

    // Message Box or Message Bar
    OpenFailConversionFailMessage: "Errore durante l'apertura del documento. Chiudere e riaprire il documento.",
    OpenFailInvalidURLMessage: "Errore durante l'apertura del documento. Chiudere e riaprire il documento.",
    OpenFailLockFailMessage: "Errore durante l'apertura del documento. Chiudere e riaprire il documento.",
    OpenFailAnotherUserConvertingMessage: "Errore durante l'apertura del documento. Chiudere e riaprire il documento.",
    OpenFailNotSupportedFormatMessage: "<p style=\"display: inline; margin: 0px\">Il documento contiene una funzionalità non supportata. Per modificare il documento, utilizzare il client.&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">Qui</a>&nbsp;è disponibile l'elenco completo delle funzionalità non supportate.</p>",
    OpenFailNotSupportedEnvironmentMessage: "Il browser in uso non è supportato per la modifica online.",
    OT3Message: "Le modifiche apportate sono state salvate temporaneamente. Fare clic su \"OK\" per ripristinarle.",
    OT5Message: "Le modifiche apportate sono state salvate temporaneamente. Fare clic su “OK“ per ripristinarle.",
    ER1Message: "Impossibile salvare le modifiche. Riprovare.",
    PleaseWait: "",
    PleaseTryAgain: "",
    PrintFinishMessage: "",
    DeleteSheetTitle: "Avviso",
    DeleteChartTitle: "Avviso",
    FormulaValidateErrorMessageCommon: "La formula contiene un errore.",

    AddColumnError: "Numero massimo di colonne che è possibile aggiungere superato.",
    ArrayFormulaEditError: "Non è possibile modificare il contenuto di celle con formule matrice.",
    BrowserZoomErrorTitle: "<p style=\"display: inline; margin: 0px\">Impostare il livello di zoom del browser e dello schermo del computer su 100%. Per ulteriori informazioni, fare clic <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360002932653-Thinkfree-Office-Cell-Online-Limitations\" target=\"_blank\">qui</a>.</p>",
    CannotGuaranteeEditMessage: "<p style=\"display: inline; margin: 0px\">La dimensione del documento è superiore al limite massimo. Fare riferimento a <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">questa pagina</a>. Durante il salvataggio del documento potrebbe verificarsi un errore.</p>",
    CopyLimitMessage: "Il numero di celle da copiare/incollare supera il limite.",
    DeleteSheetConfirm: "Impossibile annullare la cancellazione di un'operazione su un foglio. Continuare?",
    DragAndDropLimit: "Il numero di celle da copiare/incollare/spostare supera il limite di $$ celle.",
    FileOpenErrorHugeData: "Il file supera il numero massimo consentito di celle o ricalcoli dei formati condizionali.",
    FireFoxZoomError: "Se si riduce lo zoom a un livello inferiore al 100% nel browser Firefox, i bordi potrebbero non venire visualizzati correttamente.",
    InvalidSheetChangeError: "Impossibile eseguire l'operazione richiesta poiché questo foglio è stato modificato da un altro utente.",
    LastVisibleColumnDeleteErrorMessage: "Impossibile eliminare l'ultima colonna visibile di un foglio.",
    LockRefreshFailTitle: "Si è verificato un errore.",
    MaxSheetNameError: "È stato superato il numero massimo di caratteri consentiti (31).",
    MergeErrorAutoFilter: "Impossibile unire celle che si intersecano con i bordi di un filtro esistente.",
    MergeErrorRow: "Impossibile unire colonne/righe bloccate con colonne/righe normali.",
    OpenFailNotSupportedDataMessage: "<p style=\"display: inline; margin: 0px\">Questo documento contiene contenuti${UnsupportedProps} non modificabili in un browser. L'elenco dei contenuti non supportati è disponibile <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">qui</a>.</p>",
    OpenFailPasswordMessage: "Il file è protetto da password. Non è possibile modificare online i file protetti da password.",
    OT1Message: "Riconnessione in corso...",
    OT1MessageCannotSync: "La connessione alla rete o al server è stata interrotta. Tutte le modifiche apportate nell'ultimo minuto non verranno salvate. Copiare le modifiche e aggiornare il browser.",
    SynchronizationFailMessage: "La connessione alla rete o al server è stata interrotta. Tutte le modifiche apportate nell'ultimo minuto non verranno salvate. Copiare le modifiche e aggiornare il browser.",
    SynchronizationInProgress: "Sincronizzazione in corso...",
    WordFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">La dimensione di questo documento è superiore al limite massimo. Per informazioni dettagliate, consultare <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">questa pagina</a>.</p>",
    CellFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">La dimensione di questo documento è superiore al limite massimo. Per informazioni dettagliate, consultare <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">questa pagina</a>.</p>",
    ShowFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">La dimensione di questo documento è superiore al limite massimo. Per informazioni dettagliate, consultare <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">questa pagina</a>.</p>",
    TooManyFormulaError: "<p style=\"display: inline; margin: 0px\">Il file contiene diverse formule. È possibile scaricare e modificare il file utilizzando un'altra applicazione installata nel computer in uso. L'elenco dei contenuti non supportati è disponibile&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">qui</a>.</p>"
});