define({
	// Saving Status
	ModifyingMessage: "저장 중...",
	ModifiedMessage: "저장됨",
	PeriodicSavedMessage: "저장됨",
	FailedToPeriodicSaveMessage: "저장 중...",

    // Message Box or Message Bar
    OpenFailConversionFailMessage: "문서를 여는 동안 오류가 발생했습니다. 문서를 종료한 다음 해당 문서를 다시 열어 주세요.",
    OpenFailInvalidURLMessage: "문서를 여는 동안 오류가 발생했습니다. 문서를 종료한 다음 해당 문서를 다시 열어 주세요.",
    OpenFailLockFailMessage: "문서를 여는 동안 오류가 발생했습니다. 문서를 종료한 다음 해당 문서를 다시 열어 주세요.",
    OpenFailAnotherUserConvertingMessage: "문서를 여는 동안 오류가 발생했습니다. 문서를 종료한 다음 해당 문서를 다시 열어 주세요.",
    OpenFailNotSupportedFormatMessage: "<p style=\"display: inline; margin: 0px\">이 문서에는 지원하지 않는 기능이 포함되어 있습니다. 이 문서를 편집하려면 데스크톱 프로그램을 이용해 주세요.&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/ko/articles/360003147033-Unsupported-features\" target=\"_blank\">여기</a>에서 지원하지 않는 기능 목록을 확인할 수 있습니다.</p>",
    OpenFailNotSupportedEnvironmentMessage: "이 브라우저는 온라인 편집을 지원하지 않습니다.",
    OT3Message: "편집 내용은 임시 저장되어 있습니다. “확인” 버튼을 누르면 복원할 수 있습니다.",
    OT5Message: "편집 내용은 임시 저장되어 있습니다. “확인” 버튼을 누르면 복원할 수 있습니다.",
    ER1Message: "수정한 내용이 저장되지 않을 수 있습니다. 다시 시도해 주세요.",
    PleaseWait: "",
    PleaseTryAgain: "",
    PrintFinishMessage: "",
    DeleteSheetTitle: "경고",
    DeleteChartTitle: "경고",
    FormulaValidateErrorMessageCommon: "입력한 수식에 문제가 있습니다.",

    AddColumnError: "최대 생성할 수 있는 열의 수를 초과 했습니다.",
    ArrayFormulaEditError: "배열이 포함된 셀을 변경할 수 없습니다.",
    BrowserZoomErrorTitle: "<p style=\"display: inline; margin: 0px\">브라우저와 컴퓨터 디스플레이는 100% 확대 상태여야 합니다. 자세한 내용을 보려면 &nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/ko/articles/360002932653-Thinkfree-Office-Cell-Online-Limitations\" target=\"_blank\">여기</a>&nbsp;를 클릭하십시오.</p>",
    CannotGuaranteeEditMessage: "<p style=\"display: inline; margin: 0px\">이 문서는 크기 제한을 초과했습니다. <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">이 페이지</a>를 참고하세요. 문서를 저장하는 중에 오류가 발생할 수 있습니다.</p>",
    CopyLimitMessage: "복사하기/붙이기 크기 제약을 초과했습니다.",
    DeleteSheetConfirm: "시트를 삭제하면 되돌릴 수 없습니다. 계속 하시겠습니까?",
    DragAndDropLimit: "최대 $$개 셀을 복사하기/붙이기/이동할 수 있습니다.",
    FileOpenErrorHugeData: "열 수 있는 셀 또는 조건부 서식 셀의 수를 초과했습니다.",
    FireFoxZoomError: "Firefox에서 화면을 100% 미만으로 축소하면 셀 테두리가 제대로 표현되지 않을 수 있습니다.",
    InvalidSheetChangeError: "다른 사용자가 시트를 변경해서 요청한 작업을 수행할 수 없습니다.",
    LastVisibleColumnDeleteErrorMessage: "시트의 마지막 보이는 열을 삭제할 수 없습니다.",
    LockRefreshFailTitle: "오류가 발생했습니다.",
    MaxSheetNameError: "입력할 수 있는 최대 글자수(31)를 초과 했습니다.",
    MergeErrorAutoFilter: "기존 필터와 교차되는 셀을 수직으로 병합할 수 없습니다.",
    MergeErrorRow: "고정된 행/열과 일반은 행/열을 병합할 수 없습니다.",
    OpenFailNotSupportedDataMessage: "<p style=\"display: inline; margin: 0px\">이 문서에는 브라우저에서 편집할 수 없는 내용${UnsupportedProps}이 포함되어 있습니다. <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">여기</a>에서 지원하지 않는 속성 목록을 확인할 수 있습니다.</p>",
    OpenFailPasswordMessage: "이 파일은 암호로 보호되어 있습니다. 암호로 보호된 파일은 온라인으로 편집할 수 없습니다.",
    OT1Message: "다시 연결 중...",
    OT1MessageCannotSync: "네트워크 또는 서버 연결이 끊겼습니다. 마지막 1분 간의 변경 내용은 저장되지 않습니다. 변경 내용을 저장하고 브라우저를 새로 고침합니다.",
    SynchronizationFailMessage: "네트워크 또는 서버 연결이 끊겼습니다. 마지막 1분 간의 변경 내용은 저장되지 않습니다. 변경 내용을 저장하고 브라우저를 새로 고침합니다.",
    SynchronizationInProgress: "동기화 중...",
    WordFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">문서 크기가 제한을 초과 했습니다.&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/ko/articles/360003070954-File-Limitations\" target=\"_blank\">이 페이지</a>를 참조하세요.</p>",
    CellFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">문서 크기가 제한을 초과 했습니다.&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/ko/articles/360003070954-File-Limitations\" target=\"_blank\">이 페이지</a>를 참조하세요.</p>",
    ShowFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">문서 크기가 제한을 초과 했습니다.&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/ko/articles/360003070954-File-Limitations\" target=\"_blank\">이 페이지</a>를 참조하세요.</p>",
    TooManyFormulaError: "<p style=\"display: inline; margin: 0px\">문서에 많은 양의 수식이 포함되어 있습니다. 문서를 다운로드한 다음 컴퓨터에 설치된 다른 프로그램을 이용해 편집할 수 있습니다.&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/ko/articles/360003147033-Unsupported-features\" target=\"_blank\">여기</a>에서 지원하지 않는 기능 목록을 확인할 수 있습니다.</p>"

});