define([], function () {
	return {
		TEMPLATE_VALUES: {
			ruler_numbers: [
				{classVal:'span37', text:' 25 '},
				{text:' 24 '},
				{text:' 23 '},
				{text:' 22 '},
				{text:' 21 '},
				{classVal:'span37', text:' 20 '},
				{text:' 19 '},
				{text:' 18 '},
				{text:' 17" '},
				{text:' 16 '},
				{classVal:'span37', text:' 15 '},
				{text:' 14 '},
				{text:' 13 '},
				{text:' 12 '},
				{text:' 11 '},
				{classVal:'span37', text:' 10 '},
				{text:' 9 '},
				{text:' 8 '},
				{text:' 7 '},
				{text:' 6 '},
				{classVal:'span37', text:' 5 '},
				{text:' 4 '},
				{text:' 3 '},
				{text:' 2 '},
				{text:' 1 '},
				{text:' 0 '},
				{text:' 1 '},
				{text:' 2 '},
				{text:' 3 '},
				{text:' 4 '},
				{classVal:'span37', text:' 5 '},
				{text:' 6 '},
				{text:' 7 '},
				{text:' 8 '},
				{text:' 9 '},
				{classVal:'span37', text:' 10 '},
				{text:' 11 '},
				{text:' 12 '},
				{text:' 13 '},
				{text:' 14 '},
				{classVal:'span37', text:' 15 '},
				{text:' 16 '},
				{text:' 17 '},
				{text:' 18 '},
				{text:' 19 '},
				{classVal:'span37', text:' 20 '},
				{text:' 21 '},
				{text:' 22 '},
				{text:' 23 '},
				{text:' 24 '},
				{classVal:'span37', text:' 25 '},
				{text:' 26 '},
				{text:' 27 '},
				{text:' 28 '},
				{text:' 29 '},
				{classVal:'span37', text:' 30 '},
				{text:' 31 '},
				{text:' 32 '},
				{text:' 33 '},
				{text:' 34 '},
				{classVal:'span37', text:' 35 '},
				{text:' 36 '},
				{text:' 37 '},
				{text:' 38 '},
				{text:' 39 '},
				{classVal:'span37', text:' 40 '},
				{text:' 41 '},
				{text:' 42 '},
				{text:' 43 '},
				{text:' 44 '},
				{classVal:'span37', text:' 45 '}
			],
			symbol_general_punctuation: [
				{val:'2013', text:'–'},
				{val:'2014', text:'—'},
				{val:'2015', text:'―'},
				{val:'2018', text:'‘'},
				{val:'2019', text:'’'},
				{val:'201A', text:'‚'},
				{val:'201C', text:'“'},
				{val:'201D', text:'”'},
				{val:'201E', text:'„'},
				{val:'2020', text:'†'},
				{val:'2021', text:'‡'},
				{val:'2022', text:'•'},
				{val:'2025', text:'‥'},
				{val:'2026', text:'…'},
				{val:'2030', text:'‰'},
				{val:'2032', text:'′'},
				{val:'2033', text:'″'},
				{val:'2039', text:'‹'},
				{val:'203A', text:'›'},
				{val:'203B', text:'※'},
				{val:'00B7', text:'·'}
			],
			symbol_letter_like: [
				{val:'2103', text:'℃'},
				{val:'2109', text:'℉'},
				{val:'2113', text:'ℓ'},
				{val:'2116', text:'№'},
				{val:'2121', text:'℡'},
				{val:'2122', text:'™'},
				{val:'2126', text:'Ω'},
				{val:'212B', text:'Å'}
			],
			symbol_numeric_format: [
				{val:'2153', text:'⅓'},
				{val:'2154', text:'⅔'},
				{val:'215B', text:'⅛'},
				{val:'215C', text:'⅜'},
				{val:'215D', text:'⅝'},
				{val:'215E', text:'⅞'},
				{val:'2160', text:'Ⅰ'},
				{val:'2161', text:'Ⅱ'},
				{val:'2162', text:'Ⅲ'},
				{val:'2163', text:'Ⅳ'},
				{val:'2164', text:'Ⅴ'},
				{val:'2165', text:'Ⅵ'},
				{val:'2166', text:'Ⅶ'},
				{val:'2167', text:'Ⅷ'},
				{val:'2168', text:'Ⅸ'},
				{val:'2169', text:'Ⅹ'},
				{val:'2170', text:'ⅰ'},
				{val:'2171', text:'ⅱ'},
				{val:'2172', text:'ⅲ'},
				{val:'2173', text:'ⅳ'},
				{val:'2174', text:'ⅴ'},
				{val:'2175', text:'ⅵ'},
				{val:'2176', text:'ⅶ'},
				{val:'2177', text:'ⅷ'},
				{val:'2178', text:'ⅸ'},
				{val:'2179', text:'ⅹ'}
			],
			symbol_arrow: [
				{val:'2190', text:'←'},
				{val:'2191', text:'↑'},
				{val:'2192', text:'→'},
				{val:'2193', text:'↓'},
				{val:'2194', text:'↔'},
				{val:'2195', text:'↕'},
				{val:'2196', text:'↖'},
				{val:'2197', text:'↗'},
				{val:'2198', text:'↘'},
				{val:'2199', text:'↙'},
				{val:'21D2', text:'⇒'},
				{val:'21D4', text:'⇔'}
			],
			symbol_box_drawing: [
				{val:'2500', text:'─'},
				{val:'2501', text:'━'},
				{val:'2502', text:'│'},
				{val:'2503', text:'┃'},
				{val:'250C', text:'┌'},
				{val:'250D', text:'┍'},
				{val:'250E', text:'┎'},
				{val:'250F', text:'┏'},
				{val:'2510', text:'┐'},
				{val:'2511', text:'┑'},
				{val:'2512', text:'┒'},
				{val:'2513', text:'┓'},
				{val:'2514', text:'└'},
				{val:'2515', text:'┕'},
				{val:'2516', text:'┖'},
				{val:'2517', text:'┗'},
				{val:'2518', text:'┘'},
				{val:'2519', text:'┙'},
				{val:'251A', text:'┚'},
				{val:'251B', text:'┛'},
				{val:'251D', text:'┝'},
				{val:'251E', text:'┞'},
				{val:'251F', text:'┟'},
				{val:'2520', text:'┠'},
				{val:'2521', text:'┡'},
				{val:'2522', text:'┢'},
				{val:'2523', text:'┣'},
				{val:'2524', text:'┤'},
				{val:'2525', text:'┥'},
				{val:'2526', text:'┦'},
				{val:'2527', text:'┧'},
				{val:'2528', text:'┨'},
				{val:'2529', text:'┩'},
				{val:'252A', text:'┪'},
				{val:'252B', text:'┫'},
				{val:'252C', text:'┬'},
				{val:'252D', text:'┭'},
				{val:'252E', text:'┮'},
				{val:'252F', text:'┯'},
				{val:'2530', text:'┰'},
				{val:'2531', text:'┱'},
				{val:'2532', text:'┲'},
				{val:'2533', text:'┳'},
				{val:'2534', text:'┴'},
				{val:'2535', text:'┵'},
				{val:'2536', text:'┶'},
				{val:'2537', text:'┷'},
				{val:'2538', text:'┸'},
				{val:'2539', text:'┹'},
				{val:'253A', text:'┺'},
				{val:'253B', text:'┻'},
				{val:'253C', text:'┼'},
				{val:'253D', text:'┽'},
				{val:'253E', text:'┾'},
				{val:'253F', text:'┿'},
				{val:'2540', text:'╀'},
				{val:'2541', text:'╁'},
				{val:'2542', text:'╂'},
				{val:'2543', text:'╃'},
				{val:'2544', text:'╄'},
				{val:'2545', text:'╅'},
				{val:'2546', text:'╆'},
				{val:'2547', text:'╇'},
				{val:'2548', text:'╈'},
				{val:'254A', text:'╊'},
				{val:'254B', text:'╋'}
			],
			symbol_auto_shapes: [
				{val:'25A0', text:'■'},
				{val:'25A1', text:'□'},
				{val:'25A3', text:'▣'},
				{val:'25A4', text:'▤'},
				{val:'25A5', text:'▥'},
				{val:'25A6', text:'▦'},
				{val:'25A7', text:'▧'},
				{val:'25A8', text:'▨'},
				{val:'25A9', text:'▩'},
				{val:'25B2', text:'▲'},
				{val:'25B3', text:'△'},
				{val:'25B6', text:'▶'},
				{val:'25B7', text:'▷'},
				{val:'25BC', text:'▼'},
				{val:'25BD', text:'▽'},
				{val:'25C0', text:'◀'},
				{val:'25C1', text:'◁'},
				{val:'25C6', text:'◆'},
				{val:'25C7', text:'◇'},
				{val:'25C8', text:'◈'},
				{val:'25CB', text:'○'},
				{val:'25CE', text:'◎'},
				{val:'25D0', text:'◐'},
				{val:'25D1', text:'◑'}
			],
			symbol_miscellaneous: [
				{val:'2605', text:'★'},
				{val:'2606', text:'☆'},
				{val:'260E', text:'☎'},
				{val:'260F', text:'☏'},
				{val:'261C', text:'☜'},
				{val:'261E', text:'☞'},
				{val:'2640', text:'♀'},
				{val:'2642', text:'♂'},
				{val:'2660', text:'♠'},
				{val:'2661', text:'♡'},
				{val:'2663', text:'♣'},
				{val:'2664', text:'♤'},
				{val:'2665', text:'♥'},
				{val:'2667', text:'♧'},
				{val:'2668', text:'♨'},
				{val:'2669', text:'♩'},
				{val:'266A', text:'♪'},
				{val:'266C', text:'♬'},
				{val:'266D', text:'♭'}
			],
			symbol_cjk_and_punctuation: [
				{val:'3000', text:'　'},
				{val:'3001', text:'、'},
				{val:'3002', text:'。'},
				{val:'3003', text:'〃'},
				{val:'3008', text:'〈'},
				{val:'3009', text:'〉'},
				{val:'300A', text:'《'},
				{val:'300B', text:'》'},
				{val:'300C', text:'「'},
				{val:'300D', text:'」'},
				{val:'300E', text:'『'},
				{val:'300F', text:'』'},
				{val:'3010', text:'【'},
				{val:'3011', text:'】'},
				{val:'3013', text:'〓'},
				{val:'3014', text:'〔'},
				{val:'3015', text:'〕'}
			],
			symbol_1: [
				{val:'3000', text:'　'},
				{val:'3001', text:'、'},
				{val:'3002', text:'。'},
				{val:'00B7', text:'·'},
				{val:'2025', text:'‥'},
				{val:'2026', text:'…'},
				{val:'00A8', text:'¨'},
				{val:'3003', text:'〃'},
				{val:'2015', text:'―'},
				{val:'2225', text:'∥'},
				{val:'FF3C', text:'＼'},
				{val:'223C', text:'∼'},
				{val:'2018', text:'‘'},
				{val:'2019', text:'’'},
				{val:'201C', text:'“'},
				{val:'201D', text:'”'},
				{val:'3014', text:'〔'},
				{val:'3015', text:'〕'},
				{val:'3008', text:'〈'},
				{val:'3009', text:'〉'},
				{val:'300A', text:'《'},
				{val:'300B', text:'》'},
				{val:'300C', text:'「'},
				{val:'300D', text:'」'},
				{val:'300E', text:'『'},
				{val:'300F', text:'』'},
				{val:'3010', text:'【'},
				{val:'3011', text:'】'},
				{val:'00B1', text:'±'},
				{val:'00D7', text:'×'},
				{val:'00F7', text:'÷'},
				{val:'2260', text:'≠'},
				{val:'2264', text:'≤'},
				{val:'2265', text:'≥'},
				{val:'221E', text:'∞'},
				{val:'2234', text:'∴'},
				{val:'00B0', text:'°'},
				{val:'2032', text:'′'},
				{val:'2033', text:'″'},
				{val:'2103', text:'℃'},
				{val:'212B', text:'Å'},
				{val:'FFE0', text:'￠'},
				{val:'FFE1', text:'￡'},
				{val:'FFE5', text:'￥'},
				{val:'2642', text:'♂'},
				{val:'2640', text:'♀'},
				{val:'2220', text:'∠'},
				{val:'22A5', text:'⊥'},
				{val:'2312', text:'⌒'},
				{val:'2202', text:'∂'},
				{val:'2207', text:'∇'},
				{val:'2261', text:'≡'},
				{val:'2252', text:'≒'},
				{val:'00A7', text:'§'},
				{val:'203B', text:'※'},
				{val:'2606', text:'☆'},
				{val:'2605', text:'★'},
				{val:'25CB', text:'○'},
				{val:'25CF', text:'●'},
				{val:'25CE', text:'◎'},
				{val:'25C7', text:'◇'},
				{val:'25C6', text:'◆'},
				{val:'25A1', text:'□'},
				{val:'25A0', text:'■'},
				{val:'25B3', text:'△'},
				{val:'25B2', text:'▲'},
				{val:'25BD', text:'▽'},
				{val:'25BC', text:'▼'},
				{val:'2192', text:'→'},
				{val:'2190', text:'←'},
				{val:'2191', text:'↑'},
				{val:'2193', text:'↓'},
				{val:'2194', text:'↔'},
				{val:'3013', text:'〓'},
				{val:'226A', text:'≪'},
				{val:'226B', text:'≫'},
				{val:'221A', text:'√'},
				{val:'223D', text:'∽'},
				{val:'221D', text:'∝'},
				{val:'2235', text:'∵'},
				{val:'222B', text:'∫'},
				{val:'222C', text:'∬'},
				{val:'2208', text:'∈'},
				{val:'220B', text:'∋'},
				{val:'2286', text:'⊆'},
				{val:'2287', text:'⊇'},
				{val:'2282', text:'⊂'},
				{val:'2283', text:'⊃'},
				{val:'222A', text:'∪'},
				{val:'2229', text:'∩'},
				{val:'2227', text:'∧'},
				{val:'2228', text:'∨'},
				{val:'FFE2', text:'￢'}
			],
			symbol_2: [
				{val:'21D2', text:'⇒'},
				{val:'21D4', text:'⇔'},
				{val:'2200', text:'∀'},
				{val:'2203', text:'∃'},
				{val:'00B4', text:'´'},
				{val:'02DC', text:'˜'},
				{val:'02C7', text:'ˇ'},
				{val:'02D8', text:'˘'},
				{val:'02DD', text:'˝'},
				{val:'02DA', text:'˚'},
				{val:'02D9', text:'˙'},
				{val:'00B8', text:'¸'},
				{val:'02DB', text:'˛'},
				{val:'00A1', text:'¡'},
				{val:'00BF', text:'¿'},
				{val:'02D0', text:'ː'},
				{val:'222E', text:'∮'},
				{val:'2211', text:'∑'},
				{val:'220F', text:'∏'},
				{val:'00A4', text:'¤'},
				{val:'2109', text:'℉'},
				{val:'2030', text:'‰'},
				{val:'25C1', text:'◁'},
				{val:'25C0', text:'◀'},
				{val:'25B7', text:'▷'},
				{val:'25B6', text:'▶'},
				{val:'2664', text:'♤'},
				{val:'2660', text:'♠'},
				{val:'2661', text:'♡'},
				{val:'2665', text:'♥'},
				{val:'2667', text:'♧'},
				{val:'2663', text:'♣'},
				{val:'25C9', text:'◉'},
				{val:'25C8', text:'◈'},
				{val:'25A3', text:'▣'},
				{val:'25D0', text:'◐'},
				{val:'25D1', text:'◑'},
				{val:'2592', text:'▒'},
				{val:'25A4', text:'▤'},
				{val:'25A5', text:'▥'},
				{val:'25A8', text:'▨'},
				{val:'25A7', text:'▧'},
				{val:'25A6', text:'▦'},
				{val:'25A9', text:'▩'},
				{val:'2668', text:'♨'},
				{val:'260F', text:'☏'},
				{val:'260E', text:'☎'},
				{val:'261C', text:'☜'},
				{val:'261E', text:'☞'},
				{val:'00B6', text:'¶'},
				{val:'2020', text:'†'},
				{val:'2021', text:'‡'},
				{val:'2195', text:'↕'},
				{val:'2197', text:'↗'},
				{val:'2199', text:'↙'},
				{val:'2196', text:'↖'},
				{val:'2198', text:'↘'},
				{val:'266D', text:'♭'},
				{val:'2669', text:'♩'},
				{val:'266A', text:'♪'},
				{val:'266C', text:'♬'},
				{val:'327F', text:'㉿'},
				{val:'321C', text:'㈜'},
				{val:'2116', text:'№'},
				{val:'33C7', text:'㏇'},
				{val:'2122', text:'™'},
				{val:'33C2', text:'㏂'},
				{val:'33D8', text:'㏘'},
				{val:'2121', text:'℡'},
				{val:'20AC', text:'€'},
				{val:'00AE', text:'®'}
			],
			symbol_unit: [
				{val:'3380', text:'㎀'},
				{val:'3381', text:'㎁'},
				{val:'3382', text:'㎂'},
				{val:'3383', text:'㎃'},
				{val:'3384', text:'㎄'},
				// {val:'3385', text:'㎅'},
				// {val:'3386', text:'㎆'},
				// {val:'3387', text:'㎇'},
				{val:'3388', text:'㎈'},
				{val:'3389', text:'㎉'},
				{val:'338A', text:'㎊'},
				{val:'338B', text:'㎋'},
				{val:'338C', text:'㎌'},
				{val:'338D', text:'㎍'},
				{val:'338E', text:'㎎'},
				{val:'338F', text:'㎏'},
				{val:'3390', text:'㎐'},
				{val:'3391', text:'㎑'},
				{val:'3392', text:'㎒'},
				{val:'3393', text:'㎓'},
				{val:'3394', text:'㎔'},
				{val:'3399', text:'㎙'},
				{val:'339A', text:'㎚'},
				{val:'339B', text:'㎛'},
				{val:'339C', text:'㎜'},
				{val:'339D', text:'㎝'},
				{val:'339E', text:'㎞'},
				{val:'339F', text:'㎟'},
				{val:'33A0', text:'㎠'},
				{val:'33A1', text:'㎡'},
				{val:'33A2', text:'㎢'},
				{val:'33A3', text:'㎣'},
				{val:'33A4', text:'㎤'},
				{val:'33A5', text:'㎥'},
				{val:'33A6', text:'㎦'},
				{val:'33A7', text:'㎧'},
				{val:'33A8', text:'㎨'},
				{val:'33A9', text:'㎩'},
				{val:'33AA', text:'㎪'},
				{val:'33AB', text:'㎫'},
				{val:'33AC', text:'㎬'},
				{val:'33C2', text:'㏂'},
				{val:'33D8', text:'㏘'},
				{val:'33AD', text:'㎭'},
				{val:'33AE', text:'㎮'},
				{val:'33AF', text:'㎯'},
				{val:'33B0', text:'㎰'},
				{val:'33B1', text:'㎱'},
				{val:'33B2', text:'㎲'},
				{val:'33B3', text:'㎳'},
				{val:'3395', text:'㎕'},
				{val:'3396', text:'㎖'},
				{val:'3397', text:'㎗'},
				{val:'2113', text:'ℓ'},
				{val:'3398', text:'㎘'},
				{val:'33B4', text:'㎴'},
				{val:'33B5', text:'㎵'},
				{val:'33B6', text:'㎶'},
				{val:'33B7', text:'㎷'},
				{val:'33B8', text:'㎸'},
				{val:'33B9', text:'㎹'},
				{val:'33BA', text:'㎺'},
				{val:'33BB', text:'㎻'},
				{val:'33BC', text:'㎼'},
				{val:'33BD', text:'㎽'},
				{val:'33BE', text:'㎾'},
				{val:'33BF', text:'㎿'},
				{val:'2126', text:'Ω'},
				{val:'33C0', text:'㏀'},
				{val:'33C1', text:'㏁'},
				{val:'33C3', text:'㏃'},
				{val:'33C4', text:'㏄'},
				{val:'33C5', text:'㏅'},
				{val:'33C6', text:'㏆'},
				{val:'33C7', text:'㏇'},
				{val:'33C8', text:'㏈'},
				{val:'33C9', text:'㏉'},
				{val:'33CA', text:'㏊'},
				// {val:'33CB', text:'㏋'},
				// {val:'33CC', text:'㏌'},
				// {val:'33CD', text:'㏍'},
				// {val:'33CE', text:'㏎'},
				{val:'33CF', text:'㏏'},
				{val:'33D0', text:'㏐'},
				// {val:'33D1', text:'㏑'},
				// {val:'33D2', text:'㏒'},
				{val:'33D3', text:'㏓'},
				// {val:'33D4', text:'㏔'},
				// {val:'33D5', text:'㏕'},
				{val:'33D6', text:'㏖'},
				// {val:'33D7', text:'㏗'},
				// {val:'33D9', text:'㏙'},
				// {val:'33DA', text:'㏚'},
				{val:'33DB', text:'㏛'},
				{val:'33DC', text:'㏜'},
				{val:'33DD', text:'㏝'}
				// {val:'33DE', text:'㏞'},
				// {val:'33DF', text:'㏟'},
				// {val:'3371', text:'㍱'},
				// {val:'3372', text:'㍲'},
				// {val:'3373', text:'㍳'},
				// {val:'3374', text:'㍴'},
				// {val:'3375', text:'㍵'},
				// {val:'3376', text:'㍶'},
				// {val:'2109', text:'℉'},
				// {val:'212A', text:'K'},
				// {val:'00B5', text:'µ'}
			],
			symbol_circle_character: [
				{val:'3260', text:'㉠'},
				{val:'3261', text:'㉡'},
				{val:'3262', text:'㉢'},
				{val:'3263', text:'㉣'},
				{val:'3264', text:'㉤'},
				{val:'3265', text:'㉥'},
				{val:'3266', text:'㉦'},
				{val:'3267', text:'㉧'},
				{val:'3268', text:'㉨'},
				{val:'3269', text:'㉩'},
				{val:'326A', text:'㉪'},
				{val:'326B', text:'㉫'},
				{val:'326C', text:'㉬'},
				{val:'326D', text:'㉭'},
				{val:'326E', text:'㉮'},
				{val:'326F', text:'㉯'},
				{val:'3270', text:'㉰'},
				{val:'3271', text:'㉱'},
				{val:'3272', text:'㉲'},
				{val:'3273', text:'㉳'},
				{val:'3274', text:'㉴'},
				{val:'3275', text:'㉵'},
				{val:'3276', text:'㉶'},
				{val:'3277', text:'㉷'},
				{val:'3278', text:'㉸'},
				{val:'3279', text:'㉹'},
				{val:'327A', text:'㉺'},
				{val:'327B', text:'㉻'},
				// {val:'24B6', text:'Ⓐ'},
				// {val:'24B7', text:'Ⓑ'},
				// {val:'24B8', text:'Ⓒ'},
				// {val:'24B9', text:'Ⓓ'},
				// {val:'24BA', text:'Ⓔ'},
				// {val:'24BB', text:'Ⓕ'},
				// {val:'24BC', text:'Ⓖ'},
				// {val:'24BD', text:'Ⓗ'},
				// {val:'24BE', text:'Ⓘ'},
				// {val:'24BF', text:'Ⓙ'},
				// {val:'24C0', text:'Ⓚ'},
				// {val:'24C1', text:'Ⓛ'},
				// {val:'24C2', text:'Ⓜ'},
				// {val:'24C3', text:'Ⓝ'},
				// {val:'24C4', text:'Ⓞ'},
				// {val:'24C5', text:'Ⓟ'},
				// {val:'24C6', text:'Ⓠ'},
				// {val:'24C7', text:'Ⓡ'},
				// {val:'24C8', text:'Ⓢ'},
				// {val:'24C9', text:'Ⓣ'},
				// {val:'24CA', text:'Ⓤ'},
				// {val:'24CB', text:'Ⓥ'},
				// {val:'24CC', text:'Ⓦ'},
				// {val:'24CD', text:'Ⓧ'},
				// {val:'24CE', text:'Ⓨ'},
				// {val:'24CF', text:'Ⓩ'},
				{val:'24D0', text:'ⓐ'},
				{val:'24D1', text:'ⓑ'},
				{val:'24D2', text:'ⓒ'},
				{val:'24D3', text:'ⓓ'},
				{val:'24D4', text:'ⓔ'},
				{val:'24D5', text:'ⓕ'},
				{val:'24D6', text:'ⓖ'},
				{val:'24D7', text:'ⓗ'},
				{val:'24D8', text:'ⓘ'},
				{val:'24D9', text:'ⓙ'},
				{val:'24DA', text:'ⓚ'},
				{val:'24DB', text:'ⓛ'},
				{val:'24DC', text:'ⓜ'},
				{val:'24DD', text:'ⓝ'},
				{val:'24DE', text:'ⓞ'},
				{val:'24DF', text:'ⓟ'},
				{val:'24E0', text:'ⓠ'},
				{val:'24E1', text:'ⓡ'},
				{val:'24E2', text:'ⓢ'},
				{val:'24E3', text:'ⓣ'},
				{val:'24E4', text:'ⓤ'},
				{val:'24E5', text:'ⓥ'},
				{val:'24E6', text:'ⓦ'},
				{val:'24E7', text:'ⓧ'},
				{val:'24E8', text:'ⓨ'},
				{val:'24E9', text:'ⓩ'},
				// {val:'24EA', text:'⓪'},
				// {val:'24EB', text:'⓫'},
				// {val:'24EC', text:'⓬'},
				// {val:'24ED', text:'⓭'},
				// {val:'24EE', text:'⓮'},
				// {val:'24EF', text:'⓯'},
				// {val:'24F0', text:'⓰'},
				// {val:'24F1', text:'⓱'},
				// {val:'24F2', text:'⓲'},
				// {val:'24F3', text:'⓳'},
				// {val:'24F4', text:'⓴'},
				// {val:'24F5', text:'⓵'},
				// {val:'24F6', text:'⓶'},
				// {val:'24F7', text:'⓷'},
				// {val:'24F8', text:'⓸'},
				// {val:'24F9', text:'⓹'},
				// {val:'24FA', text:'⓺'},
				// {val:'24FB', text:'⓻'},
				// {val:'24FC', text:'⓼'},
				// {val:'24FD', text:'⓽'},
				// {val:'24FE', text:'⓾'},
				{val:'2460', text:'①'},
				{val:'2461', text:'②'},
				{val:'2462', text:'③'},
				{val:'2463', text:'④'},
				{val:'2464', text:'⑤'},
				{val:'2465', text:'⑥'},
				{val:'2466', text:'⑦'},
				{val:'2467', text:'⑧'},
				{val:'2468', text:'⑨'},
				{val:'2469', text:'⑩'},
				{val:'246A', text:'⑪'},
				{val:'246B', text:'⑫'},
				{val:'246C', text:'⑬'},
				{val:'246D', text:'⑭'},
				{val:'246E', text:'⑮'}
				// {val:'246F', text:'⑯'},
				// {val:'2470', text:'⑰'},
				// {val:'2471', text:'⑱'},
				// {val:'2472', text:'⑲'},
				// {val:'2473', text:'⑳'},
				// {val:'3251', text:'㉑'},
				// {val:'3252', text:'㉒'},
				// {val:'3253', text:'㉓'},
				// {val:'3254', text:'㉔'},
				// {val:'3255', text:'㉕'},
				// {val:'3256', text:'㉖'},
				// {val:'3257', text:'㉗'},
				// {val:'3258', text:'㉘'},
				// {val:'3259', text:'㉙'},
				// {val:'325A', text:'㉚'},
				// {val:'325B', text:'㉛'},
				// {val:'325C', text:'㉜'},
				// {val:'325D', text:'㉝'},
				// {val:'325E', text:'㉞'},
				// {val:'325F', text:'㉟'},
				// {val:'32B1', text:'㊱'},
				// {val:'32B2', text:'㊲'},
				// {val:'32B3', text:'㊳'},
				// {val:'32B4', text:'㊴'},
				// {val:'32B5', text:'㊵'},
				// {val:'32B6', text:'㊶'},
				// {val:'32B7', text:'㊷'},
				// {val:'32B8', text:'㊸'},
				// {val:'32B9', text:'㊹'},
				// {val:'32BA', text:'㊺'},
				// {val:'32BB', text:'㊻'},
				// {val:'32BC', text:'㊼'},
				// {val:'32BD', text:'㊽'},
				// {val:'32BE', text:'㊾'},
				// {val:'32BF', text:'㊿'},
				// {val:'2776', text:'❶'},
				// {val:'2777', text:'❷'},
				// {val:'2778', text:'❸'},
				// {val:'2779', text:'❹'},
				// {val:'277A', text:'❺'},
				// {val:'277B', text:'❻'},
				// {val:'277C', text:'❼'},
				// {val:'277D', text:'❽'},
				// {val:'277E', text:'❾'},
				// {val:'277F', text:'❿'},
				// {val:'2780', text:'➀'},
				// {val:'2781', text:'➁'},
				// {val:'2782', text:'➂'},
				// {val:'2783', text:'➃'},
				// {val:'2784', text:'➄'},
				// {val:'2785', text:'➅'},
				// {val:'2786', text:'➆'},
				// {val:'2787', text:'➇'},
				// {val:'2788', text:'➈'},
				// {val:'2789', text:'➉'},
				// {val:'278A', text:'➊'},
				// {val:'278B', text:'➋'},
				// {val:'278C', text:'➌'},
				// {val:'278D', text:'➍'},
				// {val:'278E', text:'➎'},
				// {val:'278F', text:'➏'},
				// {val:'2790', text:'➐'},
				// {val:'2791', text:'➑'},
				// {val:'2792', text:'➒'},
				// {val:'2793', text:'➓'},
				// {val:'F080', text:''},
				// {val:'F081', text:''},
				// {val:'F082', text:''},
				// {val:'F083', text:''},
				// {val:'F084', text:''},
				// {val:'F085', text:''},
				// {val:'F086', text:''},
				// {val:'F087', text:''},
				// {val:'F088', text:''},
				// {val:'F089', text:''},
				// {val:'F08A', text:''},
				// {val:'F08B', text:''},
				// {val:'F08C', text:''},
				// {val:'F08D', text:''},
				// {val:'F08E', text:''},
				// {val:'F08F', text:''},
				// {val:'F090', text:''},
				// {val:'F091', text:''},
				// {val:'F092', text:''},
				// {val:'F093', text:''},
				// {val:'F094', text:''},
				// {val:'F095', text:''},
				// {val:'3280', text:'㊀'},
				// {val:'3281', text:'㊁'},
				// {val:'3282', text:'㊂'},
				// {val:'3283', text:'㊃'},
				// {val:'3284', text:'㊄'},
				// {val:'3285', text:'㊅'},
				// {val:'3286', text:'㊆'},
				// {val:'3287', text:'㊇'},
				// {val:'3288', text:'㊈'},
				// {val:'3289', text:'㊉'},
				// {val:'328A', text:'㊊'},
				// {val:'328B', text:'㊋'},
				// {val:'328C', text:'㊌'},
				// {val:'328D', text:'㊍'},
				// {val:'328E', text:'㊎'},
				// {val:'328F', text:'㊏'},
				// {val:'3290', text:'㊐'},
				// {val:'3291', text:'㊑'},
				// {val:'3292', text:'㊒'},
				// {val:'3293', text:'㊓'},
				// {val:'3294', text:'㊔'},
				// {val:'3295', text:'㊕'},
				// {val:'3296', text:'㊖'},
				// {val:'3297', text:'㊗'},
				// {val:'3298', text:'㊘'},
				// {val:'3299', text:'㊙'},
				// {val:'329A', text:'㊚'},
				// {val:'329B', text:'㊛'},
				// {val:'329C', text:'㊜'},
				// {val:'329D', text:'㊝'},
				// {val:'329E', text:'㊞'},
				// {val:'329F', text:'㊟'},
				// {val:'32A0', text:'㊠'},
				// {val:'32A1', text:'㊡'},
				// {val:'32A2', text:'㊢'},
				// {val:'32A3', text:'㊣'},
				// {val:'32A4', text:'㊤'},
				// {val:'32A5', text:'㊥'},
				// {val:'32A6', text:'㊦'},
				// {val:'32A7', text:'㊧'},
				// {val:'32A8', text:'㊨'},
				// {val:'32A9', text:'㊩'},
				// {val:'32AA', text:'㊪'},
				// {val:'32AA', text:'㊫'},
				// {val:'32AA', text:'㊬'},
				// {val:'32AA', text:'㊭'},
				// {val:'32AA', text:'㊮'},
				// {val:'32AA', text:'㊯'},
				// {val:'32B0', text:'㊰'}
			],
			symbol_currency: [
				{val:'0024', text:'$'},
				{val:'00A2', text:'¢'},
				{val:'00A3', text:'£'},
				{val:'00A4', text:'¤'},
				{val:'00A5', text:'¥'},
				{val:'0E3F', text:'฿'},
				{val:'20A0', text:'₠'},
				{val:'20A1', text:'₡'},
				{val:'20A2', text:'₢'},
				{val:'20A3', text:'₣'},
				{val:'20A4', text:'₤'},
				{val:'20A5', text:'₥'},
				{val:'20A6', text:'₦'},
				{val:'20A7', text:'₧'},
				{val:'20A8', text:'₨'},
				{val:'20A9', text:'₩'},
				{val:'20AA', text:'₪'},
				{val:'20AB', text:'₫'},
				{val:'20AC', text:'€'},
				{val:'20AD', text:'₭'},
				{val:'20AE', text:'₮'},
				{val:'20AF', text:'₯'},
				{val:'20B0', text:'₰'},
				{val:'20B1', text:'₱'},
				{val:'FF04', text:'＄'},
				{val:'FFE0', text:'￠'},
				{val:'FFE1', text:'￡'},
				{val:'FFE5', text:'￥'},
				{val:'FFE6', text:'￦'}
			],
			symbol_mathematical_operators: [
				{val:'002B', text:'+'},
				{val:'00B1', text:'±'},
				{val:'00F7', text:'÷'},
				{val:'00D7', text:'×'},
				{val:'003C', text:'<'},
				{val:'003E', text:'>'},
				{val:'003D', text:'='},
				{val:'007C', text:'|'},
				{val:'007B', text:'{'},
				{val:'007D', text:'}'},
				{val:'0028', text:'('},
				{val:'0029', text:')'},
				{val:'005B', text:'['},
				{val:'005D', text:']'},
				{val:'301A', text:'〚'},
				{val:'301B', text:'〛'},
				{val:'27E6', text:'⟦'},
				{val:'27E7', text:'⟧'},
				{val:'27E8', text:'⟨'},
				{val:'27E9', text:'⟩'},
				{val:'27EA', text:'⟪'},
				{val:'27EB', text:'⟫'},
				{val:'2576', text:'╶'},
				{val:'2577', text:'╷'},
				{val:'257A', text:'╺'},
				{val:'257B', text:'╻'},
				{val:'20A9', text:'₩'},
				{val:'2980', text:'⦀'},
				{val:'2981', text:'⦁'},
				{val:'2982', text:'⦂'},
				{val:'2983', text:'⦃'},
				{val:'2984', text:'⦄'},
				{val:'2985', text:'⦅'},
				{val:'2986', text:'⦆'},
				{val:'2987', text:'⦇'},
				{val:'2988', text:'⦈'},
				{val:'2989', text:'⦉'},
				{val:'298A', text:'⦊'},
				{val:'298B', text:'⦋'},
				{val:'298C', text:'⦌'},
				{val:'298D', text:'⦍'},
				{val:'298E', text:'⦎'},
				{val:'298F', text:'⦏'},
				{val:'2990', text:'⦐'},
				{val:'2991', text:'⦑'},
				{val:'2992', text:'⦒'},
				{val:'2993', text:'⦓'},
				{val:'2994', text:'⦔'},
				{val:'2995', text:'⦕'},
				{val:'2996', text:'⦖'},
				{val:'2997', text:'⦗'},
				{val:'2998', text:'⦘'},
				{val:'2999', text:'⦙'},
				{val:'2200', text:'∀'},
				{val:'2201', text:'∁'},
				{val:'2202', text:'∂'},
				{val:'2203', text:'∃'},
				{val:'2204', text:'∄'},
				{val:'2205', text:'∅'},
				{val:'2206', text:'∆'},
				{val:'2207', text:'∇'},
				{val:'2208', text:'∈'},
				{val:'2209', text:'∉'},
				{val:'220A', text:'∊'},
				{val:'220B', text:'∋'},
				{val:'220C', text:'∌'},
				{val:'220D', text:'∍'},
				{val:'220E', text:'∎'},
				{val:'220F', text:'∏'},
				{val:'2210', text:'∐'},
				{val:'2211', text:'∑'},
				{val:'2212', text:'−'},
				{val:'2213', text:'∓'},
				{val:'2214', text:'∔'},
				{val:'2215', text:'∕'},
				{val:'2216', text:'∖'},
				{val:'2217', text:'∗'},
				{val:'2218', text:'∘'},
				{val:'2219', text:'∙'},
				{val:'221A', text:'√'},
				{val:'221B', text:'∛'},
				{val:'221C', text:'∜'},
				{val:'221D', text:'∝'},
				{val:'221E', text:'∞'},
				{val:'221F', text:'∟'},
				{val:'2220', text:'∠'},
				{val:'2221', text:'∡'},
				{val:'2222', text:'∢'},
				{val:'2223', text:'∣'},
				{val:'2224', text:'∤'},
				{val:'2225', text:'∥'},
				{val:'2226', text:'∦'},
				{val:'2227', text:'∧'},
				{val:'2228', text:'∨'},
				{val:'2229', text:'∩'},
				{val:'222A', text:'∪'},
				{val:'222B', text:'∫'},
				{val:'222C', text:'∬'},
				{val:'222D', text:'∭'},
				{val:'222E', text:'∮'},
				{val:'222F', text:'∯'},
				{val:'2230', text:'∰'},
				{val:'2231', text:'∱'},
				{val:'2232', text:'∲'},
				{val:'2233', text:'∳'},
				{val:'2234', text:'∴'},
				{val:'2235', text:'∵'},
				{val:'2236', text:'∶'},
				{val:'2237', text:'∷'},
				{val:'2238', text:'∸'},
				{val:'2239', text:'∹'},
				{val:'223A', text:'∺'},
				{val:'223B', text:'∻'},
				{val:'223C', text:'∼'},
				{val:'223D', text:'∽'},
				{val:'223E', text:'∾'},
				{val:'223F', text:'∿'},
				{val:'2240', text:'≀'},
				{val:'2241', text:'≁'},
				{val:'2242', text:'≂'},
				{val:'2243', text:'≃'},
				{val:'2244', text:'≄'},
				{val:'2245', text:'≅'},
				{val:'2246', text:'≆'},
				{val:'2247', text:'≇'},
				{val:'2248', text:'≈'},
				{val:'2249', text:'≉'},
				{val:'224A', text:'≊'},
				{val:'224B', text:'≋'},
				{val:'224C', text:'≌'},
				{val:'224D', text:'≍'},
				{val:'224E', text:'≎'},
				{val:'224F', text:'≏'},
				{val:'2250', text:'≐'},
				{val:'2251', text:'≑'},
				{val:'2252', text:'≒'},
				{val:'2253', text:'≓'},
				{val:'2254', text:'≔'},
				{val:'2255', text:'≕'},
				{val:'2256', text:'≖'},
				{val:'2257', text:'≗'},
				{val:'2258', text:'≘'},
				{val:'2259', text:'≙'},
				{val:'225A', text:'≚'},
				{val:'225B', text:'≛'},
				{val:'225C', text:'≜'},
				{val:'225D', text:'≝'},
				{val:'225E', text:'≞'},
				{val:'225F', text:'≟'},
				{val:'2260', text:'≠'},
				{val:'2261', text:'≡'},
				{val:'2262', text:'≢'},
				{val:'2263', text:'≣'},
				{val:'2264', text:'≤'},
				{val:'2265', text:'≥'},
				{val:'2266', text:'≦'},
				{val:'2267', text:'≧'},
				{val:'2268', text:'≨'},
				{val:'2269', text:'≩'},
				{val:'226A', text:'≪'},
				{val:'226B', text:'≫'},
				{val:'226C', text:'≬'},
				{val:'226D', text:'≭'},
				{val:'226E', text:'≮'},
				{val:'226F', text:'≯'},
				{val:'2270', text:'≰'},
				{val:'2271', text:'≱'},
				{val:'2295', text:'⊕'},
				{val:'2296', text:'⊖'},
				{val:'2297', text:'⊗'},
				{val:'2298', text:'⊘'},
				{val:'2299', text:'⊙'},
				{val:'229A', text:'⊚'},
				{val:'229B', text:'⊛'},
				{val:'229C', text:'⊜'},
				{val:'229D', text:'⊝'}
			],
			symbol_greek: [
				{val:'2170', text:'ⅰ'},
				{val:'2171', text:'ⅱ'},
				{val:'2172', text:'ⅲ'},
				{val:'2173', text:'ⅳ'},
				{val:'2174', text:'ⅴ'},
				{val:'2175', text:'ⅵ'},
				{val:'2176', text:'ⅶ'},
				{val:'2177', text:'ⅷ'},
				{val:'2178', text:'ⅸ'},
				{val:'2179', text:'ⅹ'},
				// {val:'217A', text:'ⅺ'},
				// {val:'217B', text:'ⅻ'},
				{val:'2160', text:'Ⅰ'},
				{val:'2161', text:'Ⅱ'},
				{val:'2162', text:'Ⅲ'},
				{val:'2163', text:'Ⅳ'},
				{val:'2164', text:'Ⅴ'},
				{val:'2165', text:'Ⅵ'},
				{val:'2166', text:'Ⅶ'},
				{val:'2167', text:'Ⅷ'},
				{val:'2168', text:'Ⅸ'},
				{val:'2169', text:'Ⅹ'},
				// {val:'216A', text:'Ⅺ'},
				// {val:'216B', text:'Ⅻ'},
				{val:'0391', text:'Α'},
				{val:'0392', text:'Β'},
				{val:'0393', text:'Γ'},
				{val:'0394', text:'Δ'},
				{val:'0395', text:'Ε'},
				{val:'0396', text:'Ζ'},
				{val:'0397', text:'Η'},
				{val:'0398', text:'Θ'},
				{val:'0399', text:'Ι'},
				{val:'039A', text:'Κ'},
				{val:'039B', text:'Λ'},
				{val:'039C', text:'Μ'},
				{val:'039D', text:'Ν'},
				{val:'039E', text:'Ξ'},
				{val:'039F', text:'Ο'},
				{val:'03A0', text:'Π'},
				{val:'03A1', text:'Ρ'},
				{val:'03A3', text:'Σ'},
				{val:'03A4', text:'Τ'},
				{val:'03A5', text:'Υ'},
				{val:'03A6', text:'Φ'},
				{val:'03A7', text:'Χ'},
				{val:'03A8', text:'Ψ'},
				{val:'03A9', text:'Ω'},
				{val:'03B1', text:'α'},
				{val:'03B2', text:'β'},
				{val:'03B3', text:'γ'},
				{val:'03B4', text:'δ'},
				{val:'03B5', text:'ε'},
				{val:'03B6', text:'ζ'},
				{val:'03B7', text:'η'},
				{val:'03B8', text:'θ'},
				{val:'03B9', text:'ι'},
				{val:'03BA', text:'κ'},
				{val:'03BB', text:'λ'},
				{val:'03BC', text:'μ'},
				{val:'03BD', text:'ν'},
				{val:'03BE', text:'ξ'},
				{val:'03BF', text:'ο'},
				{val:'03C0', text:'π'},
				{val:'03C1', text:'ρ'},
				{val:'03C3', text:'σ'},
				{val:'03C4', text:'τ'},
				{val:'03C5', text:'υ'},
				{val:'03C6', text:'φ'},
				{val:'03C7', text:'χ'},
				{val:'03C8', text:'ψ'},
				{val:'03C9', text:'ω'}
			],
			symbol_enclosed_alphanumeric: [
				{val:'3200', text: '㈀'},
				{val:'3201', text: '㈁'},
				{val:'3202', text: '㈂'},
				{val:'3203', text: '㈃'},
				{val:'3204', text: '㈄'},
				{val:'3205', text: '㈅'},
				{val:'3206', text: '㈆'},
				{val:'3207', text: '㈇'},
				{val:'3208', text: '㈈'},
				{val:'3209', text: '㈉'},
				{val:'320A', text: '㈊'},
				{val:'320B', text: '㈋'},
				{val:'320C', text: '㈌'},
				{val:'320D', text: '㈍'},
				{val:'320E', text: '㈎'},
				{val:'320F', text: '㈏'},
				{val:'3210', text: '㈐'},
				{val:'3211', text: '㈑'},
				{val:'3212', text: '㈒'},
				{val:'3213', text: '㈓'},
				{val:'3214', text: '㈔'},
				{val:'3215', text: '㈕'},
				{val:'3216', text: '㈖'},
				{val:'3217', text: '㈗'},
				{val:'3218', text: '㈘'},
				{val:'3219', text: '㈙'},
				{val:'321A', text: '㈚'},
				{val:'321B', text: '㈛'},
				{val:'249C', text:'⒜'},
				{val:'249D', text:'⒝'},
				{val:'249E', text:'⒞'},
				{val:'249F', text:'⒟'},
				{val:'24A0', text:'⒠'},
				{val:'24A1', text:'⒡'},
				{val:'24A2', text:'⒢'},
				{val:'24A3', text:'⒣'},
				{val:'24A4', text:'⒤'},
				{val:'24A5', text:'⒥'},
				{val:'24A6', text:'⒦'},
				{val:'24A7', text:'⒧'},
				{val:'24A8', text:'⒨'},
				{val:'24A9', text:'⒩'},
				{val:'24AA', text:'⒪'},
				{val:'24AB', text:'⒫'},
				{val:'24AC', text:'⒬'},
				{val:'24AD', text:'⒭'},
				{val:'24AE', text:'⒮'},
				{val:'24AF', text:'⒯'},
				{val:'24B0', text:'⒰'},
				{val:'24B1', text:'⒱'},
				{val:'24B2', text:'⒲'},
				{val:'24B3', text:'⒳'},
				{val:'24B4', text:'⒴'},
				{val:'24B5', text:'⒵'},
				{val:'2474', text:'⑴'},
				{val:'2475', text:'⑵'},
				{val:'2476', text:'⑶'},
				{val:'2477', text:'⑷'},
				{val:'2478', text:'⑸'},
				{val:'2479', text:'⑹'},
				{val:'247A', text:'⑺'},
				{val:'247B', text:'⑻'},
				{val:'247C', text:'⑼'},
				{val:'247D', text:'⑽'},
				{val:'247E', text:'⑾'},
				{val:'247F', text:'⑿'},
				{val:'2480', text:'⒀'},
				{val:'2481', text:'⒁'},
				{val:'2482', text:'⒂'},
				// {val:'2483', text:'⒃'},
				// {val:'2484', text:'⒄'},
				// {val:'2485', text:'⒅'},
				// {val:'2486', text:'⒆'},
				// {val:'2487', text:'⒇'},
				{val:'321C', text:'㈜'}
				// {val:'3220', text:'㈠'},
				// {val:'3221', text:'㈡'},
				// {val:'3222', text:'㈢'},
				// {val:'3223', text:'㈣'},
				// {val:'3224', text:'㈤'},
				// {val:'3225', text:'㈥'},
				// {val:'3226', text:'㈦'},
				// {val:'3227', text:'㈧'},
				// {val:'3228', text:'㈨'},
				// {val:'3229', text:'㈩'},
				// {val:'322A', text:'㈪'},
				// {val:'322B', text:'㈫'},
				// {val:'322C', text:'㈬'},
				// {val:'322D', text:'㈭'},
				// {val:'322E', text:'㈮'},
				// {val:'322F', text:'㈯'},
				// {val:'3230', text:'㈰'},
				// {val:'3231', text:'㈱'},
				// {val:'3232', text:'㈲'},
				// {val:'3233', text:'㈳'},
				// {val:'3234', text:'㈴'},
				// {val:'3235', text:'㈵'},
				// {val:'3236', text:'㈶'},
				// {val:'3237', text:'㈷'},
				// {val:'3238', text:'㈸'},
				// {val:'3239', text:'㈹'},
				// {val:'323A', text:'㈺'},
				// {val:'323B', text:'㈻'},
				// {val:'323C', text:'㈼'},
				// {val:'323D', text:'㈽'},
				// {val:'323E', text:'㈾'},
				// {val:'323F', text:'㈿'},
				// {val:'3240', text:'㉀'},
				// {val:'3241', text:'㉁'},
				// {val:'3242', text:'㉂'},
				// {val:'3243', text:'㉃'}
			],
			table1: [
				{classVal:'table11', $col:'1'},
				{classVal:'table12', $col:'2'},
				{classVal:'table13', $col:'3'},
				{classVal:'table14', $col:'4'},
				{classVal:'table15', $col:'5'},
				{classVal:'table16', $col:'6'},
				{classVal:'table17', $col:'7'},
				{classVal:'table18', $col:'8'},
				{classVal:'table19', $col:'9'},
				{classVal:'table110', $col:'10'}
			],
			table2: [
				{classVal:'table21', $col:'1'},
				{classVal:'table22', $col:'2'},
				{classVal:'table23', $col:'3'},
				{classVal:'table24', $col:'4'},
				{classVal:'table25', $col:'5'},
				{classVal:'table26', $col:'6'},
				{classVal:'table27', $col:'7'},
				{classVal:'table28', $col:'8'},
				{classVal:'table29', $col:'9'},
				{classVal:'table210', $col:'10'}
			],
			table3: [
				{classVal:'table31', $col:'1'},
				{classVal:'table32', $col:'2'},
				{classVal:'table33', $col:'3'},
				{classVal:'table34', $col:'4'},
				{classVal:'table35', $col:'5'},
				{classVal:'table36', $col:'6'},
				{classVal:'table37', $col:'7'},
				{classVal:'table38', $col:'8'},
				{classVal:'table39', $col:'9'},
				{classVal:'table310', $col:'10'}
			],
			table4: [
				{classVal:'table41', $col:'1'},
				{classVal:'table42', $col:'2'},
				{classVal:'table43', $col:'3'},
				{classVal:'table44', $col:'4'},
				{classVal:'table45', $col:'5'},
				{classVal:'table46', $col:'6'},
				{classVal:'table47', $col:'7'},
				{classVal:'table48', $col:'8'},
				{classVal:'table49', $col:'9'},
				{classVal:'table410', $col:'10'}
			],
			table5: [
				{classVal:'table51', $col:'1'},
				{classVal:'table52', $col:'2'},
				{classVal:'table53', $col:'3'},
				{classVal:'table54', $col:'4'},
				{classVal:'table55', $col:'5'},
				{classVal:'table56', $col:'6'},
				{classVal:'table57', $col:'7'},
				{classVal:'table58', $col:'8'},
				{classVal:'table59', $col:'9'},
				{classVal:'table510', $col:'10'}
			],
			table6: [
				{classVal:'table61', $col:'1'},
				{classVal:'table62', $col:'2'},
				{classVal:'table63', $col:'3'},
				{classVal:'table64', $col:'4'},
				{classVal:'table65', $col:'5'},
				{classVal:'table66', $col:'6'},
				{classVal:'table67', $col:'7'},
				{classVal:'table68', $col:'8'},
				{classVal:'table69', $col:'9'},
				{classVal:'table610', $col:'10'}
			],
			table7: [
				{classVal:'table71', $col:'1'},
				{classVal:'table72', $col:'2'},
				{classVal:'table73', $col:'3'},
				{classVal:'table74', $col:'4'},
				{classVal:'table75', $col:'5'},
				{classVal:'table76', $col:'6'},
				{classVal:'table77', $col:'7'},
				{classVal:'table78', $col:'8'},
				{classVal:'table79', $col:'9'},
				{classVal:'table710', $col:'10'}
			],
			table8: [
				{classVal:'table81', $col:'1'},
				{classVal:'table82', $col:'2'},
				{classVal:'table83', $col:'3'},
				{classVal:'table84', $col:'4'},
				{classVal:'table85', $col:'5'},
				{classVal:'table86', $col:'6'},
				{classVal:'table87', $col:'7'},
				{classVal:'table88', $col:'8'},
				{classVal:'table89', $col:'9'},
				{classVal:'table810', $col:'10'}
			],
			table9: [
				{classVal:'table91', $col:'1'},
				{classVal:'table92', $col:'2'},
				{classVal:'table93', $col:'3'},
				{classVal:'table94', $col:'4'},
				{classVal:'table95', $col:'5'},
				{classVal:'table96', $col:'6'},
				{classVal:'table97', $col:'7'},
				{classVal:'table98', $col:'8'},
				{classVal:'table99', $col:'9'},
				{classVal:'table910', $col:'10'}
			],
			table10: [
				{classVal:'table101', $col:'1'},
				{classVal:'table102', $col:'2'},
				{classVal:'table103', $col:'3'},
				{classVal:'table104', $col:'4'},
				{classVal:'table105', $col:'5'},
				{classVal:'table106', $col:'6'},
				{classVal:'table107', $col:'7'},
				{classVal:'table108', $col:'8'},
				{classVal:'table109', $col:'9'},
				{classVal:'table1010', $col:'10'}
			],
			shape_basic: [
				{classVal:'shape_btn_basicShapes_ellipse', val:'{"sName":"ellipse","sType":"3"}', $title:'SptEllipse', $IconName:'shape_ellipse', $iconName:'shape_ellipse'},
				{classVal:'shape_btn_basicShapes_triangle', val:'{"sName":"triangle","sType":"5"}', $title:'SptIsoscelesTriangle', $iconName:'shape_triangle'},
				{classVal:'shape_btn_basicShapes_rtTriangle', val:'{"sName":"rtTriangle","sType":"6"}', $title:'SptRightTriangle', $iconName:'shape_rtTriangle'},
				{classVal:'shape_btn_basicShapes_parallelogram', val:'{"sName":"parallelogram","sType":"7"}', $title:'SptParallelogram', $iconName:'shape_parallelogram'},
				{classVal:'shape_btn_basicShapes_trapezoid', val:'{"sName":"trapezoid"}', $title:'SptTrapezoid', $iconName:'shape_trapezoid'},
				{classVal:'shape_btn_basicShapes_diamond', val:'{"sName":"diamond","sType":"4"}', $title:'SptDiamond', $iconName:'shape_diamond'},
				{classVal:'shape_btn_basicShapes_pentagon', val:'{"sName":"pentagon","sType":"56"}', $title:'SptPentagon', $iconName:'shape_pentagon'},
				{classVal:'shape_btn_basicShapes_hexagon', val:'{"sName":"hexagon","sType":"9"}', $title:'SptHexagon', $iconName:'shape_hexagon'},
				{classVal:'shape_btn_basicShapes_heptagon', val:'{"sName":"heptagon","sType":"325"}', $title:'SptHeptagon', $iconName:'shape_heptagon'},
				{classVal:'shape_btn_basicShapes_octagon', val:'{"sName":"octagon","sType":"10"}', $title:'SptOctagon', $iconName:'shape_octagon'},
				{classVal:'shape_btn_basicShapes_decagon', val:'{"sName":"decagon","sType":"326"}', $title:'SptDecagon', $iconName:'shape_decagon'},
				{classVal:'shape_btn_basicShapes_dodecagon', val:'{"sName":"dodecagon","sType":"327"}', $title:'SptDodecagon', $iconName:'shape_dodecagon'},
				{classVal:'shape_btn_basicShapes_pieWedge', val:'{"sName":"pieWedge"}', $title:'shape_description_pieWedge', $iconName:'shape_pieWedge'},
				{classVal:'shape_btn_basicShapes_pie', val:'{"sName":"pie","sType":"308"}', $title:'SptPie', $iconName:'shape_pie'},
				{classVal:'shape_btn_basicShapes_chord', val:'{"sName":"chord","sType":"309"}', $title:'SptChord', $iconName:'shape_chord'},
				{classVal:'shape_btn_basicShapes_teardrop', val:'{"sName":"teardrop","sType":"310"}', $title:'SptTeardrop', $iconName:'shape_teardrop'},
				{classVal:'shape_btn_basicShapes_frame', val:'{"sName":"frame","sType":"311"}', $title:'SptFrame', $iconName:'shape_frame'},
				{classVal:'shape_btn_basicShapes_halfFrame', val:'{"sName":"halfFrame","sType":"312"}', $title:'SptHalfFrame', $iconName:'shape_halfFrame'},
				{classVal:'shape_btn_basicShapes_corner', val:'{"sName":"corner","sType":"313"}', $title:'SptCorner', $iconName:'shape_corner'},
				{classVal:'shape_btn_basicShapes_diagStripe', val:'{"sName":"diagStripe","sType":"314"}', $title:'SptDiagStripe', $iconName:'shape_diagStripe'},
				{classVal:'shape_btn_basicShapes_plus', val:'{"sName":"plus","sType":"11"}', $title:'SptPlus', $iconName:'shape_plus'},
				{classVal:'shape_btn_basicShapes_plaque', val:'{"sName":"plaque","sType":"21"}', $title:'SptPlaque', $iconName:'shape_plaque'},
				{classVal:'shape_btn_basicShapes_can', val:'{"sName":"can","sType":"22"}', $title:'SptCan', $iconName:'shape_can'},
				{classVal:'shape_btn_basicShapes_cube', val:'{"sName":"cube","sType":"16"}', $title:'SptCube', $iconName:'shape_cube'},
				{classVal:'shape_btn_basicShapes_bevel', val:'{"sName":"bevel","sType":"84"}', $title:'SptBevel', $iconName:'shape_bevel'},
				{classVal:'shape_btn_basicShapes_donut', val:'{"sName":"donut","sType":"23"}', $title:'SptDonut', $iconName:'shape_donut'},
				{classVal:'shape_btn_basicShapes_noSmoking', val:'{"sName":"noSmoking","sType":"57"}', $title:'SptNoSmoking', $iconName:'shape_noSmoking'},
				{classVal:'shape_btn_basicShapes_blockArc', val:'{"sName":"blockArc"}', $title:'SptBlockArc', $iconName:'shape_blockArc'},
				{classVal:'shape_btn_basicShapes_foldedCorner', val:'{"sName":"foldedCorner","sType":"65"}', $title:'SptFoldedCorner', $iconName:'shape_foldedCorner'},
				{classVal:'shape_btn_basicShapes_smileyFace', val:'{"sName":"smileyFace","sType":"96"}', $title:'SptSmileyFace', $iconName:'shape_smileyFace'},
				{classVal:'shape_btn_basicShapes_heart', val:'{"sName":"heart","sType":"329"}', $title:'SptHeart', $iconName:'shape_heart'},
				{classVal:'shape_btn_basicShapes_funnel', val:'{"sName":"funnel"}', $title:'shape_description_funnel', $iconName:'shape_funnel'},
				{classVal:'shape_btn_basicShapes_gear6', val:'{"sName":"gear6"}', $title:'shape_description_gear6', $iconName:'shape_gear6'},
				{classVal:'shape_btn_basicShapes_gear9', val:'{"sName":"gear9"}', $title:'shape_description_gear9', $iconName:'shape_gear9'},
				{classVal:'shape_btn_basicShapes_lightningBolt', val:'{"sName":"lightningBolt","sType":"73"}', $title:'SptLightningBolt', $iconName:'shape_lightningBolt'},
				{classVal:'shape_btn_basicShapes_sun', val:'{"sName":"sun","sType":"183"}', $title:'SptSun', $iconName:'shape_sun'},
				{classVal:'shape_btn_basicShapes_moon', val:'{"sName":"moon","sType":"184"}', $title:'SptMoon', $iconName:'shape_moon'},
				{classVal:'shape_btn_basicShapes_cloud', val:'{"sName":"cloud","sType":"328"}', $title:'SptCloud', $iconName:'shape_cloud'},
				{classVal:'shape_btn_basicShapes_arc', val:'{"sName":"arc"}', $title:'SptArc', $iconName:'shape_arc'},
				{classVal:'shape_btn_basicShapes_bracketPair', val:'{"sName":"bracketPair","sType":"185"}', $title:'SptBracketPair', $iconName:'shape_bracketPair'},
				{classVal:'shape_btn_basicShapes_bracePair', val:'{"sName":"bracePair","sType":"186"}', $title:'SptBracePair', $iconName:'shape_bracePair'},
				{classVal:'shape_btn_basicShapes_leftBracket', val:'{"sName":"leftBracket","sType":"85"}', $title:'SptLeftBracket', $iconName:'shape_leftBracket'},
				{classVal:'shape_btn_basicShapes_rightBracket', val:'{"sName":"rightBracket","sType":"86"}', $title:'SptRightBracket', $iconName:'shape_rightBracket'},
				{classVal:'shape_btn_basicShapes_leftBrace', val:'{"sName":"leftBrace","sType":"87"}', $title:'SptLeftBrace', $iconName:'shape_leftBrace'},
				{classVal:'shape_btn_basicShapes_rightBrace', val:'{"sName":"rightBrace","sType":"88"}', $title:'SptRightBrace', $iconName:'shape_rightBrace'}
			],
			shape_lines: [
				{classVal:'shape_btn_lines_line', val:'{"sName":"line"}', $title:'SptLine', $iconName:'shape_line'},
				{classVal:'shape_btn_lines_curvedConnector3', val:'{"sName":"curvedConnector3"}', $title:'SptCurvedConnector3', $iconName:'shape_curvedConnector3'},
				{classVal:'shape_btn_lines_bentConnector3', val:'{"sName":"bentConnector3"}', $title:'SptBentConnector3', $iconName:'shape_bentConnector3'}
			],
			shape_rectangles: [
				{classVal:'shape_btn_rectangles_rect', val:'{"sName":"rect","sType":"1"}', $title:'SptRectangle', $iconName:'shape_rect'},
				{classVal:'shape_btn_rectangles_roundRect', val:'{"sName":"roundRect","sType":"2"}', $title:'SptRoundRectangle', $iconName:'shape_roundRect'},
				{classVal:'shape_btn_rectangles_snip1Rect', val:'{"sName":"snip1Rect","sType":"300"}', $title:'SptSnip1Rectangle', $iconName:'shape_snip1Rect'},
				{classVal:'shape_btn_rectangles_snip2SameRect', val:'{"sName":"snip2SameRect","sType":"301"}', $title:'SptSnip2SameRectangle', $iconName:'shape_snip2SameRect'},
				{classVal:'shape_btn_rectangles_snip2DiagRect', val:'{"sName":"snip2DiagRect","sType":"302"}', $title:'SptSnip2DiagRectangle', $iconName:'shape_snip2DiagRect'},
				{classVal:'shape_btn_rectangles_snipRoundRect', val:'{"sName":"snipRoundRect","sType":"303"}', $title:'SptSnipRoundRectangle', $iconName:'shape_snipRoundRect'},
				{classVal:'shape_btn_rectangles_round1Rect', val:'{"sName":"round1Rect","sType":"304"}', $title:'SptRound1Rectangle', $iconName:'shape_round1Rect'},
				{classVal:'shape_btn_rectangles_round2SameRect', val:'{"sName":"round2SameRect","sType":"305"}', $title:'SptRound2SameRectangle', $iconName:'shape_round2SameRect'},
				{classVal:'shape_btn_rectangles_round2DiagRect', val:'{"sName":"round2DiagRect","sType":"306"}', $title:'SptRound2DiagRectangle', $iconName:'shape_round2DiagRect'}
			],
			shape_block_arrows: [
				{classVal:'shape_btn_blockArrows_rightArrow', val:'{"sName":"rightArrow","sType":"13"}', $title:'SptArrow', $iconName:'shape_rightArrow'},
				{classVal:'shape_btn_blockArrows_leftArrow', val:'{"sName":"leftArrow","sType":"66"}', $title:'SptLeftArrow', $iconName:'shape_leftArrow'},
				{classVal:'shape_btn_blockArrows_upArrow', val:'{"sName":"upArrow","sType":"68"}', $title:'SptUpArrow', $iconName:'shape_upArrow'},
				{classVal:'shape_btn_blockArrows_downArrow', val:'{"sName":"downArrow","sType":"67"}', $title:'SptDownArrow', $iconName:'shape_downArrow'},
				{classVal:'shape_btn_blockArrows_leftRightArrow', val:'{"sName":"leftRightArrow","sType":"69"}', $title:'SptLeftRightArrow', $iconName:'shape_leftRightArrow'},
				{classVal:'shape_btn_blockArrows_upDownArrow', val:'{"sName":"upDownArrow","sType":"70"}', $title:'SptUpDownArrow', $iconName:'shape_upDownArrow'},
				{classVal:'shape_btn_blockArrows_quadArrow', val:'{"sName":"quadArrow","sType":"76"}', $title:'SptQuadArrow', $iconName:'shape_quadArrow'},
				{classVal:'shape_btn_blockArrows_leftRightUpArrow', val:'{"sName":"leftRightUpArrow","sType":"182"}', $title:'SptLeftRightUpArrow', $iconName:'shape_leftRightUpArrow'},
				{classVal:'shape_btn_blockArrows_bentArrow', val:'{"sName":"bentArrow","sType":"91"}', $title:'SptBentArrow', $iconName:'shape_bentArrow'},
				{classVal:'shape_btn_blockArrows_uturnArrow', val:'{"sName":"uturnArrow","sType":"101"}', $title:'SptUturnArrow', $iconName:'shape_uturnArrow'},
				{classVal:'shape_btn_blockArrows_leftUpArrow', val:'{"sName":"leftUpArrow","sType":"89"}', $title:'SptLeftUpArrow', $iconName:'shape_leftUpArrow'},
				{classVal:'shape_btn_blockArrows_bentUpArrow', val:'{"sName":"bentUpArrow","sType":"90"}', $title:'SptBentUpArrow', $iconName:'shape_bentUpArrow'},
				{classVal:'shape_btn_blockArrows_curvedRightArrow', val:'{"sName":"curvedRightArrow","sType":"102"}', $title:'SptCurvedRightArrow', $iconName:'shape_curvedRightArrow'},
				{classVal:'shape_btn_blockArrows_curvedLeftArrow', val:'{"sName":"curvedLeftArrow","sType":"103"}', $title:'SptCurvedLeftArrow', $iconName:'shape_curvedLeftArrow'},
				{classVal:'shape_btn_blockArrows_curvedUpArrow', val:'{"sName":"curvedUpArrow","sType":"104"}', $title:'SptCurvedUpArrow', $iconName:'shape_curvedUpArrow'},
				{classVal:'shape_btn_blockArrows_curvedDownArrow', val:'{"sName":"curvedDownArrow","sType":"105"}', $title:'SptCurvedDownArrow', $iconName:'shape_curvedDownArrow'},
				{classVal:'shape_btn_blockArrows_stripedRightArrow', val:'{"sName":"stripedRightArrow","sType":"93"}', $title:'SptStripedRightArrow', $iconName:'shape_stripedRightArrow'},
				{classVal:'shape_btn_blockArrows_notchedRightArrow', val:'{"sName":"notchedRightArrow","sType":"94"}', $title:'SptNotchedRightArrow', $iconName:'shape_notchedRightArrow'},
				{classVal:'shape_btn_blockArrows_homePlate', val:'{"sName":"homePlate","sType":"15"}', $title:'SptPentagon', $iconName:'shape_homePlate'},
				{classVal:'shape_btn_blockArrows_chevron', val:'{"sName":"chevron","sType":"55"}', $title:'SptChevron', $iconName:'shape_chevron'},
				{classVal:'shape_btn_blockArrows_rightArrowCallout', val:'{"sName":"rightArrowCallout","sType":"78"}', $title:'SptRightArrowCallout', $iconName:'shape_rightArrowCallout'},
				{classVal:'shape_btn_blockArrows_downArrowCallout', val:'{"sName":"downArrowCallout","sType":"80"}', $title:'SptDownArrowCallout', $iconName:'shape_downArrowCallout'},
				{classVal:'shape_btn_blockArrows_leftArrowCallout', val:'{"sName":"leftArrowCallout","sType":"77"}', $title:'SptLeftArrowCallout', $iconName:'shape_leftArrowCallout'},
				{classVal:'shape_btn_blockArrows_upArrowCallout', val:'{"sName":"upArrowCallout","sType":"79"}', $title:'SptUpArrowCallout', $iconName:'shape_upArrowCallout'},
				{classVal:'shape_btn_blockArrows_leftRightArrowCallout', val:'{"sName":"leftRightArrowCallout","sType":"81"}', $title:'SptLeftRightArrowCallout', $iconName:'shape_leftRightArrowCallout'},
				{classVal:'shape_btn_blockArrows_upDownArrowCallout', val:'{"sName":"upDownArrowCallout"}', $title:'SptUpDownArrowCallout', $iconName:'shape_upDownArrowCallout'},
				{classVal:'shape_btn_blockArrows_quadArrowCallout', val:'{"sName":"quadArrowCallout","sType":"83"}', $title:'SptQuadArrowCallout', $iconName:'shape_quadArrowCallout'},
				{classVal:'shape_btn_blockArrows_circularArrow', val:'{"sName":"circularArrow"}', $title:'shape_description_circularArrow', $iconName:'shape_circularArrow'},
				{classVal:'shape_btn_blockArrows_leftCircularArrow', val:'{"sName":"leftCircularArrow"}', $title:'shape_description_leftCircularArrow', $iconName:'shape_leftCircularArrow'},
				{classVal:'shape_btn_blockArrows_swooshArrow', val:'{"sName":"swooshArrow"}', $title:'shape_description_swooshArrow', $iconName:'shape_swooshArrow'},
				{classVal:'shape_btn_blockArrows_leftRightRibbon', val:'{"sName":"leftRightRibbon"}', $title:'shape_description_leftRightRibbon', $iconName:'shape_leftRightRibbon'}
			],
			shape_equation: [
				{classVal:'shape_btn_equationShapes_mathPlus', val:'{"sName":"mathPlus","sType":"315"}', $title:'SptMathPlus', $iconName:'shape_mathPlus'},
				{classVal:'shape_btn_equationShapes_mathMinus', val:'{"sName":"mathMinus","sType":"316"}', $title:'SptMathMinus', $iconName:'shape_mathMinus'},
				{classVal:'shape_btn_equationShapes_mathMultiply', val:'{"sName":"mathMultiply","sType":"317"}', $title:'SptMathMultiply', $iconName:'shape_mathMultiply'},
				{classVal:'shape_btn_equationShapes_mathDivide', val:'{"sName":"mathDivide","sType":"318"}', $title:'SptMathDivide', $iconName:'shape_mathDivide'},
				{classVal:'shape_btn_equationShapes_mathEqual', val:'{"sName":"mathEqual","sType":"319"}', $title:'SptMathEqual', $iconName:'shape_mathEqual'},
				{classVal:'shape_btn_equationShapes_mathNotEqual', val:'{"sName":"mathNotEqual","sType":"320"}', $title:'SptMathNotEqual', $iconName:'shape_mathNotEqual'}
			],
			shape_flowchart: [
				{classVal:'shape_btn_flowchart_flowChartProcess', val:'{"sName":"flowChartProcess","sType":"109"}', $title:'SptFlowChartProcess', $iconName:'shape_flowChartProcess'},
				{classVal:'shape_btn_flowchart_flowChartAlternateProcess', val:'{"sName":"flowChartAlternateProcess","sType":"176"}', $title:'SptFlowChartAlternateProcess', $iconName:'shape_flowChartAlternateProcess'},
				{classVal:'shape_btn_flowchart_flowChartDecision', val:'{"sName":"flowChartDecision","sType":"110"}', $title:'SptFlowChartDecision', $iconName:'shape_flowChartDecision'},
				{classVal:'shape_btn_flowchart_flowChartInputOutput', val:'{"sName":"flowChartInputOutput","sType":"111"}', $title:'SptFlowChartInputOutput', $iconName:'shape_flowChartInputOutput'},
				{classVal:'shape_btn_flowchart_flowChartPredefinedProcess', val:'{"sName":"flowChartPredefinedProcess","sType":"112"}', $title:'SptFlowChartPredefinedProcess', $iconName:'shape_flowChartPredefinedProcess'},
				{classVal:'shape_btn_flowchart_flowChartInternalStorage', val:'{"sName":"flowChartInternalStorage","sType":"113"}', $title:'SptFlowChartInternalStorage', $iconName:'shape_flowChartInternalStorage'},
				{classVal:'shape_btn_flowchart_flowChartDocument', val:'{"sName":"flowChartDocument","sType":"114"}', $title:'SptFlowChartDocument', $iconName:'shape_flowChartDocument'},
				{classVal:'shape_btn_flowchart_flowChartMultidocument', val:'{"sName":"flowChartMultidocument","sType":"115"}', $title:'SptFlowChartMultidocument', $iconName:'shape_flowChartMultidocument'},
				{classVal:'shape_btn_flowchart_flowChartTerminator', val:'{"sName":"flowChartTerminator","sType":"116"}', $title:'SptFlowChartTerminator', $iconName:'shape_flowChartTerminator'},
				{classVal:'shape_btn_flowchart_flowChartPreparation', val:'{"sName":"flowChartPreparation","sType":"117"}', $title:'SptFlowChartPreparation', $iconName:'shape_flowChartPreparation'},
				{classVal:'shape_btn_flowchart_flowChartManualInput', val:'{"sName":"flowChartManualInput","sType":"118"}', $title:'SptFlowChartManualInput', $iconName:'shape_flowChartManualInput'},
				{classVal:'shape_btn_flowchart_flowChartManualOperation', val:'{"sName":"flowChartManualOperation","sType":"119"}', $title:'SptFlowChartManualOperation', $iconName:'shape_flowChartManualOperation'},
				{classVal:'shape_btn_flowchart_flowChartConnector', val:'{"sName":"flowChartConnector","sType":"120"}', $title:'SptFlowChartConnector', $iconName:'shape_flowChartConnector'},
				{classVal:'shape_btn_flowchart_flowChartOffpageConnector', val:'{"sName":"flowChartOffpageConnector","sType":"177"}', $title:'SptFlowChartOffpageConnector', $iconName:'shape_flowChartOffpageConnector'},
				{classVal:'shape_btn_flowchart_flowChartPunchedCard', val:'{"sName":"flowChartPunchedCard","sType":"121"}', $title:'SptFlowChartPunchedCard', $iconName:'shape_flowChartPunchedCard'},
				{classVal:'shape_btn_flowchart_flowChartPunchedTape', val:'{"sName":"flowChartPunchedTape","sType":"122"}', $title:'SptFlowChartPunchedTape', $iconName:'shape_flowChartPunchedTape'},
				{classVal:'shape_btn_flowchart_flowChartSummingJunction', val:'{"sName":"flowChartSummingJunction","sType":"123"}', $title:'SptFlowChartSummingJunction', $iconName:'shape_flowChartSummingJunction'},
				{classVal:'shape_btn_flowchart_flowChartOr', val:'{"sName":"flowChartOr","sType":"124"}', $title:'SptFlowChartOr', $iconName:'shape_flowChartOr'},
				{classVal:'shape_btn_flowchart_flowChartCollate', val:'{"sName":"flowChartCollate","sType":"125"}', $title:'SptFlowChartCollate', $iconName:'shape_flowChartCollate'},
				{classVal:'shape_btn_flowchart_flowChartSort', val:'{"sName":"flowChartSort","sType":"126"}', $title:'SptFlowChartSort', $iconName:'shape_flowChartSort'},
				{classVal:'shape_btn_flowchart_flowChartExtract', val:'{"sName":"flowChartExtract","sType":"127"}', $title:'SptFlowChartExtract', $iconName:'shape_flowChartExtract'},
				{classVal:'shape_btn_flowchart_flowChartMerge', val:'{"sName":"flowChartMerge","sType":"128"}', $title:'SptFlowChartMerge', $iconName:'shape_flowChartMerge'},
				{classVal:'shape_btn_flowchart_flowChartOnlineStorage', val:'{"sName":"flowChartOnlineStorage","sType":"130"}', $title:'SptFlowChartOnlineStorage', $iconName:'shape_flowChartOnlineStorage'},
				{classVal:'shape_btn_flowchart_flowChartDelay', val:'{"sName":"flowChartDelay","sType":"135"}', $title:'SptFlowChartDelay', $iconName:'shape_flowChartDelay'},
				{classVal:'shape_btn_flowchart_flowChartMagneticTape', val:'{"sName":"flowChartMagneticTape","sType":"131"}', $title:'SptFlowChartMagneticTape', $iconName:'shape_flowChartMagneticTape'},
				{classVal:'shape_btn_flowchart_flowChartMagneticDisk', val:'{"sName":"flowChartMagneticDisk","sType":"132"}', $title:'SptFlowChartMagneticDisk', $iconName:'shape_flowChartMagneticDisk'},
				{classVal:'shape_btn_flowchart_flowChartMagneticDrum', val:'{"sName":"flowChartMagneticDrum","sType":"133"}', $title:'SptFlowChartMagneticDrum', $iconName:'shape_flowChartMagneticDrum'},
				{classVal:'shape_btn_flowchart_flowChartDisplay', val:'{"sName":"flowChartDisplay","sType":"134"}', $title:'SptFlowChartDisplay', $iconName:'shape_flowChartDisplay'}
			],
			shape_stars_and_banners: [
				{classVal:'shape_btn_starsAndBanners_irregularSeal1', val:'{"sName":"irregularSeal1","sType":"71"}', $title:'SptIrregularSeal1', $iconName:'shape_irregularSeal1'},
				{classVal:'shape_btn_starsAndBanners_irregularSeal2', val:'{"sName":"irregularSeal2","sType":"72"}', $title:'SptIrregularSeal2', $iconName:'shape_irregularSeal2'},
				{classVal:'shape_btn_starsAndBanners_star4', val:'{"sName":"star4","sType":"187"}', $title:'SptSeal4', $iconName:'shape_star4'},
				{classVal:'shape_btn_starsAndBanners_star5', val:'{"sName":"star5","sType":"12"}', $title:'SptStar', $iconName:'shape_star5'},
				{classVal:'shape_btn_starsAndBanners_star6', val:'{"sName":"star6","sType":"321"}', $title:'SptSeal6', $iconName:'shape_star6'},
				{classVal:'shape_btn_starsAndBanners_star7', val:'{"sName":"star7","sType":"322"}', $title:'SptSeal7', $iconName:'shape_star7'},
				{classVal:'shape_btn_starsAndBanners_star8', val:'{"sName":"star8","sType":"58"}', $title:'SptSeal8', $iconName:'shape_star8'},
				{classVal:'shape_btn_starsAndBanners_star10', val:'{"sName":"star10","sType":"323"}', $title:'SptSeal10', $iconName:'shape_star10'},
				{classVal:'shape_btn_starsAndBanners_star12', val:'{"sName":"star12","sType":"324"}', $title:'SptSeal12', $iconName:'shape_star12'},
				{classVal:'shape_btn_starsAndBanners_star16', val:'{"sName":"star16","sType":"59"}', $title:'SptSeal16', $iconName:'shape_star16'},
				{classVal:'shape_btn_starsAndBanners_star24', val:'{"sName":"star24","sType":"92"}', $title:'SptSeal24', $iconName:'shape_star24'},
				{classVal:'shape_btn_starsAndBanners_star32', val:'{"sName":"star32","sType":"60"}', $title:'SptSeal32', $iconName:'shape_star32'},
				{classVal:'shape_btn_starsAndBanners_ribbon2', val:'{"sName":"ribbon2","sType":"54"}', $title:'SptRibbon2', $iconName:'shape_ribbon2'},
				{classVal:'shape_btn_starsAndBanners_ribbon', val:'{"sName":"ribbon","sType":"53"}', $title:'SptRibbon', $iconName:'shape_ribbon'},
				{classVal:'shape_btn_starsAndBanners_ellipseRibbon2', val:'{"sName":"ellipseRibbon2","sType":"108"}', $title:'SptEllipseRibbon2', $iconName:'shape_ellipseRibbon2'},
				{classVal:'shape_btn_starsAndBanners_ellipseRibbon', val:'{"sName":"ellipseRibbon","sType":"107"}', $title:'SptEllipseRibbon', $iconName:'shape_ellipseRibbon'},
				{classVal:'shape_btn_starsAndBanners_verticalScroll', val:'{"sName":"verticalScroll","sType":"97"}', $title:'SptVerticalScroll', $iconName:'shape_verticalScroll'},
				{classVal:'shape_btn_starsAndBanners_horizontalScroll', val:'{"sName":"horizontalScroll","sType":"98"}', $title:'SptHorizontalScroll', $iconName:'shape_horizontalScroll'},
				{classVal:'shape_btn_starsAndBanners_wave', val:'{"sName":"wave"}', $title:'SptWave', $iconName:'shape_wave'},
				{classVal:'shape_btn_starsAndBanners_doubleWave', val:'{"sName":"doubleWave"}', $title:'SptDoubleWave', $iconName:'shape_doubleWave'}
			],
			shape_callouts: [
				{classVal:'shape_btn_callouts_wedgeRectCallout', val:'{"sName":"wedgeRectCallout","sType":"61"}', $title:'wedgeRectCallout', $iconName:'shape_wedgeRectCallout'},
				{classVal:'shape_btn_callouts_wedgeRoundRectCallout', val:'{"sName":"wedgeRoundRectCallout","sType":"62"}', $title:'SptWedgeRRectCallout', $iconName:'shape_wedgeRoundRectCallout'},
				{classVal:'shape_btn_callouts_wedgeEllipseCallout', val:'{"sName":"wedgeEllipseCallout","sType":"63"}', $title:'SptWedgeEllipseCallout', $iconName:'shape_wedgeEllipseCallout'},
				{classVal:'shape_btn_callouts_cloudCallout', val:'{"sName":"cloudCallout","sType":"106"}', $title:'SptCloudCallout', $iconName:'shape_cloudCallout'},
				{classVal:'shape_btn_callouts_borderCallout1', val:'{"sName":"borderCallout1","sType":"47"}', $title:'SptBorderCallout90', $iconName:'shape_borderCallout1'},
				{classVal:'shape_btn_callouts_borderCallout2', val:'{"sName":"borderCallout2","sType":"48"}', $title:'SptBorderCallout1', $iconName:'shape_borderCallout2'},
				{classVal:'shape_btn_callouts_borderCallout3', val:'{"sName":"borderCallout3","sType":"49"}', $title:'SptBorderCallout2', $iconName:'shape_borderCallout3'},
				{classVal:'shape_btn_callouts_accentCallout1', val:'{"sName":"accentCallout1","sType":"44"}', $title:'SptAccentCallout90', $iconName:'shape_accentCallout1'},
				{classVal:'shape_btn_callouts_accentCallout2', val:'{"sName":"accentCallout2","sType":"45"}', $title:'SptAccentCallout1', $iconName:'shape_accentCallout2'},
				{classVal:'shape_btn_callouts_accentCallout3', val:'{"sName":"accentCallout3","sType":"46"}', $title:'SptAccentCallout2', $iconName:'shape_accentCallout3'},
				{classVal:'shape_btn_callouts_callout1', val:'{"sName":"callout1","sType":"41"}', $title:'SptCallout90', $iconName:'shape_callout1'},
				{classVal:'shape_btn_callouts_callout2', val:'{"sName":"callout2","sType":"42"}', $title:'SptCallout1', $iconName:'shape_callout2'},
				{classVal:'shape_btn_callouts_callout3', val:'{"sName":"callout3","sType":"43"}', $title:'SptCallout2', $iconName:'shape_callout3'},
				{classVal:'shape_btn_callouts_accentBorderCallout1', val:'{"sName":"accentBorderCallout1","sType":"50"}', $title:'SptAccentBorderCallout90', $iconName:'shape_accentBorderCallout1'},
				{classVal:'shape_btn_callouts_accentBorderCallout2', val:'{"sName":"accentBorderCallout2","sType":"51"}', $title:'SptAccentBorderCallout1', $iconName:'shape_accentBorderCallout2'},
				{classVal:'shape_btn_callouts_accentBorderCallout3', val:'{"sName":"accentBorderCallout3","sType":"52"}', $title:'SptAccentBorderCallout2', $iconName:'shape_accentBorderCallout3'}
			],
			shape_action_buttons: [
				{classVal:'shape_btn_actionButtons_actionButtonBackPrevious', val:'{"sName":"actionButtonBackPrevious"}', $title:'shape_description_actionButtonBackPrevious', $iconName:'shape_actionButtonBackPrevious'},
				{classVal:'shape_btn_actionButtons_actionButtonForwardNext', val:'{"sName":"actionButtonForwardNext"}', $title:'shape_description_actionButtonForwardNext', $iconName:'shape_actionButtonForwardNext'},
				{classVal:'shape_btn_actionButtons_actionButtonBeginning', val:'{"sName":"actionButtonBeginning"}', $title:'shape_description_actionButtonBeginning', $iconName:'shape_actionButtonBeginning'},
				{classVal:'shape_btn_actionButtons_actionButtonEnd', val:'{"sName":"actionButtonEnd"}', $title:'shape_description_actionButtonEnd', $iconName:'shape_actionButtonEnd'},
				{classVal:'shape_btn_actionButtons_actionButtonHome', val:'{"sName":"actionButtonHome"}', $title:'shape_description_actionButtonHome', $iconName:'shape_actionButtonHome'},
				{classVal:'shape_btn_actionButtons_actionButtonInformation', val:'{"sName":"actionButtonInformation"}', $title:'shape_description_actionButtonInformation', $iconName:'shape_actionButtonInformation'},
				{classVal:'shape_btn_actionButtons_actionButtonReturn', val:'{"sName":"actionButtonReturn"}', $title:'shape_description_actionButtonReturn', $iconName:'shape_actionButtonReturn'},
				{classVal:'shape_btn_actionButtons_actionButtonMovie', val:'{"sName":"actionButtonMovie"}', $title:'shape_description_actionButtonMovie', $iconName:'shape_actionButtonMovie'},
				{classVal:'shape_btn_actionButtons_actionButtonDocument', val:'{"sName":"actionButtonDocument"}', $title:'shape_description_actionButtonDocument', $iconName:'shape_actionButtonDocument'},
				{classVal:'shape_btn_actionButtons_actionButtonSound', val:'{"sName":"actionButtonSound"}', $title:'shape_description_actionButtonSound', $iconName:'shape_actionButtonSound'},
				{classVal:'shape_btn_actionButtons_actionButtonHelp', val:'{"sName":"actionButtonHelp"}', $title:'shape_description_actionButtonHelp', $iconName:'shape_actionButtonHelp'},
				{classVal:'shape_btn_actionButtons_actionButtonBlank', val:'{"sName":"actionButtonBlank"}', $title:'shape_description_actionButtonBlank', $iconName:'shape_actionButtonBlank'}
			],
			default_colors_webhwp: [
				{inherit:'#FFFFFF', classVal:'color_white'},
				{inherit:'#000000'},
				{inherit:'#FAF3DB'},
				{inherit:'#3A3C84'},
				{inherit:'#6182D6'},
				{inherit:'#FF843A'},
				{inherit:'#B2B2B2'},
				{inherit:'#FFD700'},
				{inherit:'#289B6E'},
				{inherit:'#9D5CBB'}
			],
			extend_palette_colors: [
				{inherit:'#F2F2F2'},
				{inherit:'#808080'},
				{inherit:'#F4E5B2'},
				{inherit:'#D3D3EB'},
				{inherit:'#DFE6F7'},
				{inherit:'#FFE7D8'},
				{inherit:'#F0F0F0'},
				{inherit:'#FFF7CC'},
				{inherit:'#CDF2E4'},
				{inherit:'#EBDEF1'},
				{inherit:'#D9D9D9'},
				{inherit:'#595959'},
				{inherit:'#ECD174'},
				{inherit:'#A6A7D8'},
				{inherit:'#C0CDEF'},
				{inherit:'#FFCEB0'},
				{inherit:'#E0E0E0'},
				{inherit:'#FFEF99'},
				{inherit:'#9BE5C8'},
				{inherit:'#D8BEE4'},
				{inherit:'#BFBFBF'},
				{inherit:'#404040'},
				{inherit:'#CEA61D'},
				{inherit:'#7A7CC4'},
				{inherit:'#A0B4E6'},
				{inherit:'#FFB689'},
				{inherit:'#D1D1D1'},
				{inherit:'#FFE766'},
				{inherit:'#69D8AD'},
				{inherit:'#C49DD6'},
				{inherit:'#A6A6A6'},
				{inherit:'#262626'},
				{inherit:'#67530E'},
				{inherit:'#2B2D63'},
				{inherit:'#3057B9'},
				{inherit:'#EB5800'},
				{inherit:'#858585'},
				{inherit:'#BFA100'},
				{inherit:'#1E7452'},
				{inherit:'#783E94'},
				{inherit:'#808080'},
				{inherit:'#0D0D0D'},
				{inherit:'#292106'},
				{inherit:'#1D1E42'},
				{inherit:'#203A7B'},
				{inherit:'#9C3B00'},
				{inherit:'#595959'},
				{inherit:'#806B00'},
				{inherit:'#144E37'},
				{inherit:'#502962'}
			],
			standard_palette_colors: [
				{inherit:'#000000'},
				{inherit:'#FF0000'},
				{inherit:'#FF6600'},
				{inherit:'#FFFF00'},
				{inherit:'#BAFF1A'},
				{inherit:'#008000'},
				{inherit:'#42C7F1'},
				{inherit:'#0000FF'},
				{inherit:'#1B1760'},
				{inherit:'#800080'}
			],
			color_themes: [
				{$uiValue:'default', classVal:'default on', text:'{ThemeColorDefault}', $iconName:'color_theme_default'},
				{$uiValue:'office', classVal:'office', text:'{ThemeColorOffice}', $iconName:'color_theme_office'},
				{$uiValue:'afterimage', classVal:'afterimage', text:'{ThemeColorAfterimage}', $iconName:'color_theme_afterimage'},
				{$uiValue:'light', classVal:'light', text:'{ThemeColorLight}', $iconName:'color_theme_light'},
				{$uiValue:'orange', classVal:'orange', text:'{ThemeColorOrange}', $iconName:'color_theme_orange'},
				{$uiValue:'yesterday', classVal:'yesterday', text:'{ThemeColorYesterday}', $iconName:'color_theme_yesterday'},
				{$uiValue:'spring', classVal:'spring', text:'{ThemeColorSpring}', $iconName:'color_theme_spring'},
				{$uiValue:'dream', classVal:'dream', text:'{ThemeColorDream}', $iconName:'color_theme_dream'},
				{$uiValue:'forest', classVal:'forest', text:'{ThemeColorForest}', $iconName:'color_theme_forest'},
				{$uiValue:'sea', classVal:'sea', text:'{ThemeColorSea}', $iconName:'color_theme_sea'},
				{$uiValue:'weightlessness', classVal:'weightlessness', text:'{ThemeColorWeightless}', $iconName:'color_theme_weightlessness'},
				{$uiValue:'deepsea', classVal:'deepsea', text:'{ThemeColorDeepSea}', $iconName:'color_theme_deepsea'}
			],
			default_colors: [
				{inherit:'#FFFFFF', classVal:'clolr_white'},
				{inherit:'#000000'},
				{inherit:'#E3DCC1'},
				{inherit:'#1C3D62'},
				{inherit:'#315F97'},
				{inherit:'#C75252'},
				{inherit:'#E9AE2B'},
				{inherit:'#699B37'},
				{inherit:'#358791'},
				{inherit:'#CA56A7'}
			],
			palette_colors: [
				{inherit:'#F2F2F2'},
				{inherit:'#E1E1E1'},
				{inherit:'#FCFCF9'},
				{inherit:'#E2EBF6'},
				{inherit:'#E8EFF7'},
				{inherit:'#F9EEEE'},
				{inherit:'#FDF7EA'},
				{inherit:'#F1F8E8'},
				{inherit:'#E8F6F7'},
				{inherit:'#FAEEF6'},
				{inherit:'#E5E5E5'},
				{inherit:'#C8C8C8'},
				{inherit:'#F9F8F3'},
				{inherit:'#C5D6ED'},
				{inherit:'#D1DEEF'},
				{inherit:'#F3DCDC'},
				{inherit:'#FBEFD4'},
				{inherit:'#E1EFD3'},
				{inherit:'#D2EBEE'},
				{inherit:'#F4DEEE'},
				{inherit:'#D9D9D9'},
				{inherit:'#9B9B9B'},
				{inherit:'#F4F1E6'},
				{inherit:'#87AFDD'},
				{inherit:'#A2BEE0'},
				{inherit:'#E9B9B9'},
				{inherit:'#F6DFAA'},
				{inherit:'#C3E0A6'},
				{inherit:'#A3D7DE'},
				{inherit:'#EABCDC'},
				{inherit:'#CCCCCC'},
				{inherit:'#666666'},
				{inherit:'#EEEADA'},
				{inherit:'#4C89CC'},
				{inherit:'#729DD2'},
				{inherit:'#DD9797'},
				{inherit:'#F2CE80'},
				{inherit:'#A5D07A'},
				{inherit:'#76C3CD'},
				{inherit:'#DF9ACA'},
				{inherit:'#B2B2B2'},
				{inherit:'#4D4D4D'},
				{inherit:'#E9E3CD'},
				{inherit:'#2C639E'},
				{inherit:'#437DC3'},
				{inherit:'#D27575'},
				{inherit:'#EDBE56'},
				{inherit:'#87C04E'},
				{inherit:'#47B0BD'},
				{inherit:'#D478B9'},
				{inherit:'#999999'},
				{inherit:'#333333'},
				{inherit:'#D6CCA4'},
				{inherit:'#193758'},
				{inherit:'#2C5688'},
				{inherit:'#BF3E3E'},
				{inherit:'#E1A217'},
				{inherit:'#5F8C31'},
				{inherit:'#307A82'},
				{inherit:'#C3409C'},
				{inherit:'#808080'},
				{inherit:'#262626'},
				{inherit:'#BCAB6A'},
				{inherit:'#142B45'},
				{inherit:'#22436A'},
				{inherit:'#953030'},
				{inherit:'#AF7E12'},
				{inherit:'#4A6D26'},
				{inherit:'#255E66'},
				{inherit:'#99307A'},
				{inherit:'#545454'},
				{inherit:'#1A1A1A'},
				{inherit:'#918041'},
				{inherit:'#0E1F31'},
				{inherit:'#18304C'},
				{inherit:'#6A2222'},
				{inherit:'#7D5A0D'},
				{inherit:'#354E1B'},
				{inherit:'#1A4449'},
				{inherit:'#6E2257'},
				{inherit:'#1E1E1E'},
				{inherit:'#0D0D0D'},
				{inherit:'#574D27'},
				{inherit:'#08121D'},
				{inherit:'#0F1D2D'},
				{inherit:'#401515'},
				{inherit:'#4B3608'},
				{inherit:'#202F11'},
				{inherit:'#10292C'},
				{inherit:'#421534'}
			],
			default_colors_webshow: [
				{classVal:'bg1_background', val:'bg1'},
				{classVal:'tx1_background', val:'tx1'},
				{classVal:'bg2_background', val:'bg2'},
				{classVal:'tx2_background', val:'tx2'},
				{classVal:'accent1_background', val:'accent1'},
				{classVal:'accent2_background', val:'accent2'},
				{classVal:'accent3_background', val:'accent3'},
				{classVal:'accent4_background', val:'accent4'},
				{classVal:'accent5_background', val:'accent5'},
				{classVal:'accent6_background', val:'accent6'}
			],
			theme_palette_colors: [
				{classVal:'bg1_1_background', val:'bg1_1'},
				{classVal:'tx1_1_background', val:'tx1_1'},
				{classVal:'bg2_1_background', val:'bg2_1'},
				{classVal:'tx2_1_background', val:'tx2_1'},
				{classVal:'accent1_1_background', val:'accent1_1'},
				{classVal:'accent2_1_background', val:'accent2_1'},
				{classVal:'accent3_1_background', val:'accent3_1'},
				{classVal:'accent4_1_background', val:'accent4_1'},
				{classVal:'accent5_1_background', val:'accent5_1'},
				{classVal:'accent6_1_background', val:'accent6_1'},
				{classVal:'bg1_2_background', val:'bg1_2'},
				{classVal:'tx1_2_background', val:'tx1_2'},
				{classVal:'bg2_2_background', val:'bg2_2'},
				{classVal:'tx2_2_background', val:'tx2_2'},
				{classVal:'accent1_2_background', val:'accent1_2'},
				{classVal:'accent2_2_background', val:'accent2_2'},
				{classVal:'accent3_2_background', val:'accent3_2'},
				{classVal:'accent4_2_background', val:'accent4_2'},
				{classVal:'accent5_2_background', val:'accent5_2'},
				{classVal:'accent6_2_background', val:'accent6_2'},
				{classVal:'bg1_3_background', val:'bg1_3'},
				{classVal:'tx1_3_background', val:'tx1_3'},
				{classVal:'bg2_3_background', val:'bg2_3'},
				{classVal:'tx2_3_background', val:'tx2_3'},
				{classVal:'accent1_3_background', val:'accent1_3'},
				{classVal:'accent2_3_background', val:'accent2_3'},
				{classVal:'accent3_3_background', val:'accent3_3'},
				{classVal:'accent4_3_background', val:'accent4_3'},
				{classVal:'accent5_3_background', val:'accent5_3'},
				{classVal:'accent6_3_background', val:'accent6_3'},
				{classVal:'bg1_4_background', val:'bg1_4'},
				{classVal:'tx1_4_background', val:'tx1_4'},
				{classVal:'bg2_4_background', val:'bg2_4'},
				{classVal:'tx2_4_background', val:'tx2_4'},
				{classVal:'accent1_4_background', val:'accent1_4'},
				{classVal:'accent2_4_background', val:'accent2_4'},
				{classVal:'accent3_4_background', val:'accent3_4'},
				{classVal:'accent4_4_background', val:'accent4_4'},
				{classVal:'accent5_4_background', val:'accent5_4'},
				{classVal:'accent6_4_background', val:'accent6_4'},
				{classVal:'bg1_5_background', val:'bg1_5'},
				{classVal:'tx1_5_background', val:'tx1_5'},
				{classVal:'bg2_5_background', val:'bg2_5'},
				{classVal:'tx2_5_background', val:'tx2_5'},
				{classVal:'accent1_5_background', val:'accent1_5'},
				{classVal:'accent2_5_background', val:'accent2_5'},
				{classVal:'accent3_5_background', val:'accent3_5'},
				{classVal:'accent4_5_background', val:'accent4_5'},
				{classVal:'accent5_5_background', val:'accent5_5'},
				{classVal:'accent6_5_background', val:'accent6_5'}
			]
		}
	};
});
