/**
 * Created by hancom on 2017-03-22.
 */
define({
    /*=============================== Resource ===============================*/
// writing law by GT
// Top-down, Grouping, reusable
// indent : hierarchy

    IDS_KEEP_STYLE_LOCAL                        : " 사본",
    IDS_KEEP_STYLE_ENG                          : " Copy",
    IDS_STYLE_INFO_NEXT_STYLE                   : "다음 스타일",
    IDS_STYLE_INFO_PARA_HEADING_BULLET          : "글머리표",
    IDS_STYLE_INFO_PARA_HEADING_BULLET_IMAGE    : "그림 글머리표",
    IDS_STYLE_INFO_PARA_HEADING_NUMBER          : "번호",
    IDS_STYLE_INFO_PARA_HEADING_OUTLINE         : "개요",
    IDS_STYLE_INFO_NONE                         : "없음",
    IDS_STYLE_INFO_PARA_HEADING_TYPE            : "문단 종류",
    IDS_STYLE_INFO_LINE_SPACING                 : "줄간격",
    IDS_STYLE_INFO_ALIGN_TYPE                   : "가운데",
    IDS_STYLE_INFO_INDENTATION_NORMAL           : "보통",
    IDS_STYLE_INFO_INDENTATION_NEGATIVE         : "내어쓰기",
    IDS_STYLE_INFO_INDENTATION_POSITIVE         : "들여쓰기",
    IDS_STYLE_INFO_FIRST_LINE                   : "첫 줄",
    IDS_STYLE_INFO_LEFT_MARGIN                  : "왼쪽 여백",
    IDS_STYLE_INFO_SPACING                      : "자간",
    IDS_STYLE_INFO_RATIO                        : "장평",
    IDS_STYLE_INFO_SIZE                         : "크기",
    IDS_STYLE_INFO_CHAR_NAME                    : "글꼴",
    IDS_STYLE_NAME_NORMAL                       : "바탕글",
    IDS_SHAPE_COMP_NAME_MUNDANLINE              : "문단띠로",
    IDS_SHAPE_COMP_COMMENT_STRING               : "%s 입니다.",
    IDS_SHAPE_COMP_NAME_CONTAINER               : "묶음 개체",
    IDS_MASTERPAGE_LAST                         : "구역 마지막 쪽",
    IDS_MASTERPAGE_BEGIN                        : "구역 임의 쪽",
    IDS_MASTERPAGE_LAST_SHORT                   : "마지막",
    IDS_MASTERPAGE_BEGIN_SHORT                  : "임의",
    IDS_PAGE_TYPE_BOTH                          : "양 쪽",
    IDS_PAGE_TYPE_EVEN                          : "짝수 쪽",
    IDS_PAGE_TYPE_ODD                           : "홀수 쪽",
    IDS_EDIT_DATE                               : "만든 날짜",
    IDS_CTRL_NAME_TABLE                         : "표",
    IDS_SHAPE_COMP_NAME_PICTURE                 : "그림",
    IDS_CTRL_NAME_EQEDIT                        : "수식",
    IDS_CRSREF_UPPOS                            : "위",
    IDS_CRSREF_DOWNPOS                          : "아래",
    IDS_EMPTY_DOC                               : "빈문서 1",
    IDS_FILE_PATH                               : "파일 경로",
    IDS_REVISION_HEAD                           : "고침표",
    IDS_MEMO_HEAD                               : "메모",
    IDS_REVISION_HEAD_PRINT                     : "쪽] [고침표:",
    IDS_MEMO_HEAD_PRINT                         : "쪽] [메모:",
    IDS_MEMO_NOTE                               : "메모 내용",
    IDS_SUMMARY_TITLE                           : "제목",
    IDS_SUMMARY_SUBJECT                         : "주제",
    IDS_SUMMARY_AUTHOR                          : "지은이",
    IDS_SUMMARY_DATE                            : "날짜",
    IDS_SUMMARY_KEYWORDS                        : "키워드",
    IDS_SUMMARY_COMMENTS                        : "기타",
    IDS_USERINFO_USER_NAME                      : "사용자 이름",
    IDS_USERINFO_COMPANY                        : "회사 이름",
    IDS_USERINFO_DEPARTMENT                     : "부서 이름",
    IDS_USERINFO_POSITION                       : "직책 이름",
    IDS_USERINFO_OFFICE_TELEPHONE               : "회사 전화번호",
    IDS_USERINFO_FAX                            : "팩스 번호",
    IDS_USERINFO_HOME_TELEPHONE                 : "집 전화번호",
    IDS_USERINFO_MOBILEPHONE                    : "핸드폰 번호",
    IDS_USERINFO_HOMEPAGE                       : "홈페이지 주소",
    IDS_USERINFO_EMAIL1                         : "전자 우편 주소1",
    IDS_USERINFO_EMAIL2                         : "전자 우편 주소2",
    IDS_USERINFO_ETC                            : "기타",
    IDS_TRACKCHANGE_MEMO_HEAD_PRINT             : "쪽] [변경 추적 안내문]",
    IDS_MEMO_HEAD_INSERT                        : "삽입",
    IDS_MEMO_HEAD_DELETE                        : "삭제",
    IDS_MEMO_HEAD_UPDATE                        : "수정",
    IDS_TRACKCHANGE_MEMO_HEAD                   : "[변경 추적 안내문]",
    IDS_MEMO_HEAD_FORMAT_PRINT                  : "쪽]",
    IDS_FIELD_NAME_REVISION_SIGN_SPACE          : "띄움표",
    IDS_FIELD_NAME_REVISION_SIGN_LINESEPARATE   : "줄 바꿈표",
    IDS_FIELD_NAME_REVISION_SIGN_LINEINSERT     : "줄 비움표",
    IDS_FIELD_NAME_REVISION_SIGN_SYMBOL         : "부호 넣음표",
    IDS_FIELD_NAME_REVISION_SIGN_INSERT         : "넣음표",
    IDS_FIELD_NAME_REVISION_CLIPPING            : "뺌표",
    IDS_FIELD_NAME_REVISION_SPLIT_TRANSFER      : "자리 바꿈 나눔표",
    IDS_FIELD_NAME_REVISION_SPLIT__LINETRANSFER : "줄 서로 바꿈 나눔표",
    IDS_FIELD_NAME_PRIVATE_INFO_SECURITY        : "개인 정보"

});
