define({
    // Saving Status
    ModifyingMessage: "Guardando...",
    ModifiedMessage: "Guardado",
    PeriodicSavedMessage: "Guardado",
    FailedToPeriodicSaveMessage: "Guardando...",

    // Message Box or Message Bar
    OpenFailConversionFailMessage: "Se ha producido un error al abrir el documento. Cierre el documento e intente abrirlo de nuevo.",
    OpenFailInvalidURLMessage: "Se ha producido un error al abrir el documento. Cierre el documento e intente abrirlo de nuevo.",
    OpenFailLockFailMessage: "Se ha producido un error al abrir el documento. Cierre el documento e intente abrirlo de nuevo.",
    OpenFailAnotherUserConvertingMessage: "Se ha producido un error al abrir el documento. Cierre el documento e intente abrirlo de nuevo.",
    OpenFailNotSupportedFormatMessage: "<p style=\"display: inline; margin: 0px\">Este documento contiene características no compatibles. Use el cliente para modificar este documento.&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">Aquí</a>&nbsp;se incluye una lista completa de características no compatibles.</p>",
    OpenFailNotSupportedEnvironmentMessage: "Este navegador no admite la edición en línea.",
    OT3Message: "Sus cambios se han almacenado temporalmente. Haga clic en “Aceptar” para restaurarlos.",
    OT5Message: "Sus cambios se han almacenado temporalmente. Haga clic en “Aceptar” para restaurarlos.",
    ER1Message: "No se han podido guardar los cambios. Inténtelo de nuevo.",
    PleaseWait: "",
    PleaseTryAgain: "",
    PrintFinishMessage: "",
    DeleteSheetTitle: "Advertencia",
    DeleteChartTitle: "Advertencia",
    FormulaValidateErrorMessageCommon: "Hay un error en esta fórmula.",

    AddColumnError: "Supera el número máximo de columnas que se pueden añadir.",
    ArrayFormulaEditError: "No se puede cambiar el contenido de la celda con la fórmula matricial.",
    BrowserZoomErrorTitle: "<p style=\"display: inline; margin: 0px\">El navegador y la pantalla del equipo deben estar definidos con un zoom de 100 %. Para obtener más información, haga clic <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360002932653-Thinkfree-Office-Cell-Online-Limitations\" target=\"_blank\">aquí</a>.</p>",
    CannotGuaranteeEditMessage: "<p style=\"display: inline; margin: 0px\">Este documento supera el límite de tamaño. Consulte <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">esta página</a>. Es posible que se produzca un error al guardar este documento.</p>",
    CopyLimitMessage: "Copiar/Pegar supera el límite de tamaño.",
    DeleteSheetConfirm: "No se puede deshacer la operación de eliminar una hoja. ¿Desea continuar?",
    DragAndDropLimit: "Copiar/Pegar/Mover supera el límite de $$ celdas.",
    FileOpenErrorHugeData: "El archivo excede el número máximo de celdas o de nuevos cálculos de formato condicional.",
    FireFoxZoomError: "Si disminuye el nivel de zoom a menos del 100 % en el navegador Firefox, puede dar lugar a una visualización incorrecta del borde.",
    InvalidSheetChangeError: "La tarea solicitada no puede ejecutarse porque otro usuario ha cambiado la(s) hoja(s).",
    LastVisibleColumnDeleteErrorMessage: "No se puede eliminar la última columna visible de una hoja.",
    LockRefreshFailTitle: "Se ha producido un error.",
    MaxSheetNameError: "Se ha superado el número máximo de caracteres de entrada (31).",
    MergeErrorAutoFilter: "No se pueden combinar celdas que sobrepasen los bordes de un filtro existente.",
    MergeErrorRow: "Las columnas o filas inmovilizadas no se pueden combinar con las normales.",
    OpenFailNotSupportedDataMessage: "<p style=\"display: inline; margin: 0px\">Este documento tiene contenido${UnsupportedProps} que no se puede editar en un navegador. <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">Aquí</a> podrá encontrar una lista de contenido no compatible.</p>",
    OpenFailPasswordMessage: "Este archivo está protegido con contraseña. Los archivos protegidos por contraseña no se pueden editar en línea.",
    OT1Message: "Volviendo a conectar...",
    OT1MessageCannotSync: "Se ha perdido la conexión de red o con el servidor. No se guardará ningún cambio que se haya realizado en el último minuto.  Copie los cambios y actualice el navegador.",
    SynchronizationFailMessage: "Se ha perdido la conexión de red o con el servidor. No se guardará ningún cambio que se haya realizado en el último minuto.  Copie los cambios y actualice el navegador.",
    SynchronizationInProgress: "Sincronizando...",
    WordFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">El tamaño de este documento supera el límite de tamaño. Consulte <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">esta página</a> para obtener detalles.</p>",
    CellFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">El tamaño de este documento supera el límite de tamaño. Consulte <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">esta página</a> para obtener detalles.</p>",
    ShowFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">El tamaño de este documento supera el límite de tamaño. Consulte <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">esta página</a> para obtener detalles.</p>",
    TooManyFormulaError: "<p style=\"display: inline; margin: 0px\">El archivo contiene muchas fórmulas. Puede descargar y editar el archivo con otra aplicación que esté instalada en el equipo. &nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">Aquí</a> podrá encontrar una lista de contenido no compatible.</p>"
});