define({
    // Saving Status
    ModifyingMessage: "Выполняется сохранение…",
    ModifiedMessage: "Сохранено",
    PeriodicSavedMessage: "Сохранено",
    FailedToPeriodicSaveMessage: "Выполняется сохранение…",

    // Message Box or Message Bar
    OpenFailConversionFailMessage: "Во время открытия документа произошла ошибка. Закройте и снова откройте документ.",
    OpenFailInvalidURLMessage: "Во время открытия документа произошла ошибка. Закройте и снова откройте документ.",
    OpenFailLockFailMessage: "Во время открытия документа произошла ошибка. Закройте и снова откройте документ.",
    OpenFailAnotherUserConvertingMessage: "Во время открытия документа произошла ошибка. Закройте и снова откройте документ.",
    OpenFailNotSupportedFormatMessage: "<p style=\"display: inline; margin: 0px\">Этот документ содержит неподдерживаемую функцию. Чтобы отредактировать его, используйте клиент.&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">Вот</a>&nbsp;полный список неподдерживаемых функций.</p>",
    OpenFailNotSupportedEnvironmentMessage: "Этот браузер не поддерживает функцию редактирования в Интернете.",
    OT3Message: "Ваши изменения временно сохранены. Чтобы восстановить их, нажмите кнопку “OK”.",
    OT5Message: "Ваши изменения временно сохранены. Чтобы восстановить их, нажмите кнопку “OK“.",
    ER1Message: "Ваши изменения не удалось сохранить. Повторите попытку.",
    PleaseWait: "",
    PleaseTryAgain: "",
    PrintFinishMessage: "",
    DeleteSheetTitle: "Внимание",
    DeleteChartTitle: "Внимание",
    FormulaValidateErrorMessageCommon: "В этой формуле есть ошибка.",

    AddColumnError: "Максимальное число столбцов, которое можно вставить, превышается.",
    ArrayFormulaEditError: "Содержимое ячейки с формулой массива невозможно изменять.",
    BrowserZoomErrorTitle: "<p style=\"display: inline; margin: 0px\">Для браузера и дисплея компьютера необходимо установить масштаб 100 %. Чтобы получить дополнительную информацию, щелкните <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360002932653-Thinkfree-Office-Cell-Online-Limitations\" target=\"_blank\">здесь</a>.</p>",
    CannotGuaranteeEditMessage: "<p style=\"display: inline; margin: 0px\">Размер этого документа превышает ограничение. Дополнительные сведения см. на <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">этой странице</a>. При сохранении этого документа может произойти ошибка.</p>",
    CopyLimitMessage: "Размер фрагмента, который копируется и вставляется, превышает ограничение.",
    DeleteSheetConfirm: "Невозможно отменить удаление листа. Вы хотите продолжить?",
    DragAndDropLimit: "Размер фрагмента, который копируется, вставляется или перемещается, превышает ограничение, составляющее $$ яч.",
    FileOpenErrorHugeData: "В файле превышено максимальное количество ячеек или пересчетов условного форматирования.",
    FireFoxZoomError: "Если в браузере Firefox снизить уровень масштаба ниже 100 %, границы ячеек могут отображаться неправильно.",
    InvalidSheetChangeError: "Запрошенная задача не может быть выполнена: другой пользователь изменил листы.",
    LastVisibleColumnDeleteErrorMessage: "Последний видимый столбец на листе невозможно удалить.",
    LockRefreshFailTitle: "Произошла ошибка.",
    MaxSheetNameError: "Превышено максимально допустимое число символов (31).",
    MergeErrorAutoFilter: "Ячейки, выходящие за пределы установленного фильтра, невозможно объединить.",
    MergeErrorRow: "Закрепленные столбцы и строки невозможно объединить с обычными столбцами и строками.",
    OpenFailNotSupportedDataMessage: "<p style=\"display: inline; margin: 0px\">Этот документ содержит элементы${UnsupportedProps}, которые невозможно редактировать в браузере. Список неподдерживаемого содержимого можно найти <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">здесь</a>.</p>",
    OpenFailPasswordMessage: "Файл защищен паролем. Файлы, защищенные паролем, невозможно редактировать в Интернете.",
    OT1Message: "Повторное подключение…",
    OT1MessageCannotSync: "Подключение к сети или серверу потеряно. Любые изменения, внесенные за последнюю 1 минуту, не будут сохранены. Скопируйте изменения и обновите окно браузера.",
    SynchronizationFailMessage: "Подключение к сети или серверу потеряно. Любые изменения, внесенные за последнюю 1 минуту, не будут сохранены. Скопируйте изменения и обновите окно браузера.",
    SynchronizationInProgress: "Синхронизация…",
    WordFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">Размер этого документа превышает ограничение. Подробные сведения см. на <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">этой странице</a>.</p>",
    CellFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">Размер этого документа превышает ограничение. Подробные сведения см. на <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">этой странице</a>.</p>",
    ShowFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">Размер этого документа превышает ограничение. Подробные сведения см. на <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">этой странице</a>.</p>",
    TooManyFormulaError: "<p style=\"display: inline; margin: 0px\">Файл содержит много формул. Вы можете скачать и отредактировать файл с помощью другого приложения, установленного на компьютере. Список неподдерживаемого содержимого можно найти&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">здесь</a>.</p>"
});