define({
    // Saving Status
    ModifyingMessage: "Enregistrement...",
    ModifiedMessage: "Enregistré",
    PeriodicSavedMessage: "Enregistré",
    FailedToPeriodicSaveMessage: "Enregistrement...",

    // Message Box or Message Bar
    OpenFailConversionFailMessage: "Une erreur s'est produite lors de l'ouverture du document. Fermez le document et ouvrez-le à nouveau.",
    OpenFailInvalidURLMessage: "Une erreur s'est produite lors de l'ouverture du document. Fermez le document et ouvrez-le à nouveau.",
    OpenFailLockFailMessage: "Une erreur s'est produite lors de l'ouverture du document. Fermez le document et ouvrez-le à nouveau.",
    OpenFailAnotherUserConvertingMessage: "Une erreur s'est produite lors de l'ouverture du document. Fermez le document et ouvrez-le à nouveau.",
    OpenFailNotSupportedFormatMessage: "<p style=\"display: inline; margin: 0px\">Ce document contient des fonctionnalités non prises en charge. Utilisez le client pour modifier ce document.&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">Cette page</a>&nbsp;présente la liste complète des fonctionnalités non prises en charge.</p>",
    OpenFailNotSupportedEnvironmentMessage: "Ce navigateur n'est pas pris en charge pour la modification en ligne.",
    OT3Message: "Vos modifications sont stockées temporairement. Cliquez sur « OK » pour les restaurer.",
    OT5Message: "Vos modifications sont stockées temporairement. Cliquez sur OK pour les restaurer.",
    ER1Message: "Vos modifications n’ont pas pu être enregistrées. Veuillez réessayer.",
    PleaseWait: "",
    PleaseTryAgain: "",
    PrintFinishMessage: "",
    DeleteSheetTitle: "Avertissement",
    DeleteChartTitle: "Avertissement",
    FormulaValidateErrorMessageCommon: "Une erreur a été détectée dans cette formule.",

    AddColumnError: "Le nombre maximal de colonnes pouvant être ajoutées est dépassé.",
    ArrayFormulaEditError: "Impossible de modifier le contenu de la cellule comportant une formule matricielle.",
    BrowserZoomErrorTitle: "<p style=\"display: inline; margin: 0px\">Le niveau de zoom du navigateur et de l’écran de l’ordinateur doit être à 100 %. Cliquez <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360002932653-Thinkfree-Office-Cell-Online-Limitations\" target=\"_blank\">ici</a> pour plus d’informations.</p>",
    CannotGuaranteeEditMessage: "<p style=\"display: inline; margin: 0px\">Ce document dépasse la limite autorisée. Veuillez vous reporter à <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">cette page</a>. Une erreur peut survenir lors de l’enregistrement de ce document.</p>",
    CopyLimitMessage: "Les éléments copiés/collés dépassent la limite autorisée.",
    DeleteSheetConfirm: "Impossible d’annuler l’opération de suppression d’une feuille. Voulez-vous continuer ?",
    DragAndDropLimit: "Les éléments copiés/collés/déplacés dépassent la limite autorisée fixée à $$ cellules.",
    FileOpenErrorHugeData: "Le nombre total maximum de cellules autorisées ou de recalculs de format conditionnel est dépassé.",
    FireFoxZoomError: "Si vous réduisez le niveau de zoom à moins de 100 % dans le navigateur Firefox, les bordures peuvent ne pas apparaître correctement.",
    InvalidSheetChangeError: "Impossible d'exécuter la tâche demandée, car un autre utilisateur a modifié les feuilles.",
    LastVisibleColumnDeleteErrorMessage: "Impossible de supprimer la dernière colonne visible d'une feuille.",
    LockRefreshFailTitle: "Une erreur s'est produite.",
    MaxSheetNameError: "Vous avez dépassé le nombre maximal de caractères autorisés (31).",
    MergeErrorAutoFilter: "Impossible de fusionner les cellules qui traversent les bordures d'un filtre existant.",
    MergeErrorRow: "Les colonnes/lignes figées ne peuvent pas être fusionnées avec des colonnes/lignes normales.",
    OpenFailNotSupportedDataMessage: "<p style=\"display: inline; margin: 0px\">Ce document comporte du contenu${UnsupportedProps} qui ne peut pas être modifié dans un navigateur. Vous trouverez la liste des contenus non pris en charge sur <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">cette page</a>.</p>",
    OpenFailPasswordMessage: "Ce fichier est protégé par mot de passe. Les fichiers protégés par mot de passe ne peuvent pas être modifiés en ligne.",
    OT1Message: "Reconnexion…",
    OT1MessageCannotSync: "La connexion au réseau ou au serveur a été perdue. Les modifications apportées au cours de la dernière minute ne seront pas enregistrées. Copiez vos modifications et actualisez le navigateur.",
    SynchronizationFailMessage: "La connexion au réseau ou au serveur a été perdue. Les modifications apportées au cours de la dernière minute ne seront pas enregistrées. Copiez vos modifications et actualisez le navigateur.",
    SynchronizationInProgress: "Synchronisation…",
    WordFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">La taille du document dépasse la limite autorisée. Pour plus d’informations, reportez-vous à <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">cette page</a>.</p>",
    CellFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">La taille du document dépasse la limite autorisée. Pour plus d’informations, reportez-vous à <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">cette page</a>.</p>",
    ShowFileOpenConstraintMessage: "<p style=\"display: inline; margin: 0px\">La taille du document dépasse la limite autorisée. Pour plus d’informations, reportez-vous à <a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003070954-File-Limitations\" target=\"_blank\">cette page</a>.</p>",
    TooManyFormulaError: "<p style=\"display: inline; margin: 0px\">Le fichier contient un grand nombre de formules. Vous pouvez télécharger et modifier le fichier à l’aide de toute autre application installée sur votre ordinateur. Vous trouverez la liste des contenus non pris en charge sur&nbsp;<a class=\"on_link\" href=\"https://workdocs.thinkfree.com/hc/en-us/articles/360003147033-Unsupported-features\" target=\"_blank\">cette page</a>.</p>"
});